/**
 * Charity platform collection schemas.
 */

export const charitySchemas = [
  {
    name: 'charity_pages',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'json', default: [] },
      { name: 'seoTitle', type: 'string', maxLength: 200 },
      { name: 'seoDescription', type: 'text', maxLength: 300 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
      { name: 'order', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'charity_pages_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'charity_campaigns',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'shortDescription', type: 'text', maxLength: 300 },
      { name: 'category', type: 'string', enum: ['zakaat', 'water', 'food', 'orphans', 'education', 'emergency', 'medical', 'shelter'], required: true, indexed: true },
      { name: 'goalAmount', type: 'number', required: true },
      { name: 'raisedAmount', type: 'number', default: 0 },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'beneficiaryCount', type: 'integer', default: 0 },
      { name: 'imageUrl', type: 'url' },
      { name: 'galleryImages', type: 'array', of: 'url', default: [] },
      { name: 'deadline', type: 'date', indexed: true },
      { name: 'isUrgent', type: 'boolean', default: false, indexed: true },
      { name: 'location', type: 'string' },
      { name: 'status', type: 'string', enum: ['active', 'completed', 'paused', 'archived'], default: 'active', indexed: true },
      { name: 'createdAt', type: 'datetime' },
      { name: 'updatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_camp_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'charity_campaign_updates',
    fields: [
      { name: 'campaignId', type: 'string', required: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'text', required: true },
      { name: 'imageUrl', type: 'url' },
      { name: 'author', type: 'string' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_cu_camp_idx', fields: ['campaignId'] }],
  },
  {
    name: 'charity_donations',
    fields: [
      { name: 'campaignId', type: 'string', indexed: true },
      { name: 'donorName', type: 'string', required: true },
      { name: 'donorEmail', type: 'email', indexed: true },
      { name: 'donorPhone', type: 'phone' },
      { name: 'amount', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'category', type: 'string', enum: ['zakaat', 'sadaqah', 'waqf', 'emergency', 'general'], indexed: true },
      { name: 'type', type: 'string', enum: ['one-time', 'recurring'], default: 'one-time' },
      { name: 'method', type: 'string', enum: ['card', 'bank_transfer', 'cash', 'mobile_money'] },
      { name: 'reference', type: 'string', unique: true, indexed: true },
      { name: 'status', type: 'string', enum: ['pending', 'successful', 'failed'], default: 'pending', indexed: true },
      { name: 'isAnonymous', type: 'boolean', default: false },
      { name: 'message', type: 'text' },
      { name: 'receiptUrl', type: 'url' },
      { name: 'donatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_don_ref_idx', fields: ['reference'], unique: true }],
  },
  {
    name: 'charity_donors',
    fields: [
      { name: 'email', type: 'email', required: true, unique: true, indexed: true },
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'phone', type: 'phone' },
      { name: 'totalDonated', type: 'number', default: 0 },
      { name: 'donationCount', type: 'integer', default: 0 },
      { name: 'firstDonationAt', type: 'datetime' },
      { name: 'lastDonationAt', type: 'datetime' },
      { name: 'isRecurring', type: 'boolean', default: false },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'communicationOptIn', type: 'boolean', default: true },
    ],
    indexes: [{ name: 'charity_donors_email_idx', fields: ['email'], unique: true }],
  },
  {
    name: 'charity_recurring_donations',
    fields: [
      { name: 'donorEmail', type: 'email', required: true, indexed: true },
      { name: 'donorName', type: 'string', required: true },
      { name: 'amount', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'frequency', type: 'string', enum: ['weekly', 'monthly', 'quarterly', 'yearly'], default: 'monthly' },
      { name: 'campaignId', type: 'string', indexed: true },
      { name: 'category', type: 'string' },
      { name: 'nextChargeDate', type: 'date', indexed: true },
      { name: 'status', type: 'string', enum: ['active', 'paused', 'cancelled'], default: 'active', indexed: true },
      { name: 'startedAt', type: 'datetime' },
      { name: 'totalCharged', type: 'number', default: 0 },
    ],
    indexes: [{ name: 'charity_rd_donor_idx', fields: ['donorEmail'] }],
  },
  {
    name: 'charity_volunteers',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'email', type: 'email', required: true, unique: true, indexed: true },
      { name: 'phone', type: 'phone', required: true },
      { name: 'skills', type: 'array', of: 'string', default: [] },
      { name: 'availability', type: 'string', enum: ['weekdays', 'weekends', 'evenings', 'flexible'], default: 'flexible' },
      { name: 'preferredRole', type: 'string', indexed: true },
      { name: 'location', type: 'string' },
      { name: 'bio', type: 'text' },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'active', 'inactive'], default: 'pending', indexed: true },
      { name: 'assignedRole', type: 'string' },
      { name: 'hoursLogged', type: 'number', default: 0 },
      { name: 'joinedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_vol_email_idx', fields: ['email'], unique: true }],
  },
  {
    name: 'charity_volunteer_roles',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 120 },
      { name: 'description', type: 'text' },
      { name: 'requirements', type: 'array', of: 'string', default: [] },
      { name: 'location', type: 'string' },
      { name: 'timeCommitment', type: 'string' },
      { name: 'slotsAvailable', type: 'integer', default: 1 },
      { name: 'slotsFilled', type: 'integer', default: 0 },
      { name: 'status', type: 'string', enum: ['open', 'filled', 'closed'], default: 'open', indexed: true },
    ],
    indexes: [{ name: 'charity_vr_status_idx', fields: ['status'] }],
  },
  {
    name: 'charity_beneficiaries',
    fields: [
      { name: 'name', type: 'string', required: true, encrypted: true },
      { name: 'age', type: 'integer', encrypted: true },
      { name: 'gender', type: 'string', enum: ['male', 'female'], encrypted: true },
      { name: 'familySize', type: 'integer', default: 1 },
      { name: 'location', type: 'string', encrypted: true },
      { name: 'category', type: 'string', enum: ['orphan', 'widow', 'elderly', 'disabled', 'displaced', 'poor'], indexed: true },
      { name: 'needsAssessment', type: 'text', encrypted: true },
      { name: 'assistanceHistory', type: 'array', of: 'json', default: [], encrypted: true },
      { name: 'verificationStatus', type: 'string', enum: ['pending', 'verified', 'rejected'], default: 'pending', indexed: true },
      { name: 'registeredAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_ben_cat_idx', fields: ['category'] }],
  },
  {
    name: 'charity_impact_metrics',
    fields: [
      { name: 'metricKey', type: 'string', required: true, indexed: true },
      { name: 'metricLabel', type: 'string', required: true },
      { name: 'value', type: 'integer', required: true },
      { name: 'unit', type: 'string' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'period', type: 'string' },
      { name: 'updatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_im_key_idx', fields: ['metricKey'] }],
  },
  {
    name: 'charity_success_stories',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'summary', type: 'text', maxLength: 300 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'beneficiaryName', type: 'string' },
      { name: 'location', type: 'string' },
      { name: 'imageUrl', type: 'url' },
      { name: 'galleryImages', type: 'array', of: 'url', default: [] },
      { name: 'beforeImageUrl', type: 'url' },
      { name: 'afterImageUrl', type: 'url' },
      { name: 'metrics', type: 'json', default: {} },
      { name: 'campaignId', type: 'string', indexed: true },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_ss_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'charity_testimonials',
    fields: [
      { name: 'authorName', type: 'string', required: true, maxLength: 120 },
      { name: 'authorRole', type: 'string' },
      { name: 'authorAvatarUrl', type: 'url' },
      { name: 'content', type: 'text', required: true },
      { name: 'rating', type: 'integer', default: 5, minimum: 1, maximum: 5 },
      { name: 'isDonor', type: 'boolean', default: false },
      { name: 'isBeneficiary', type: 'boolean', default: false },
      { name: 'isPartner', type: 'boolean', default: false },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected'], default: 'pending', indexed: true },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_test_status_idx', fields: ['status'] }],
  },
  {
    name: 'charity_blog_posts',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'excerpt', type: 'text', maxLength: 500 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'featuredImageUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'authorName', type: 'string' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime', indexed: true },
      { name: 'views', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'charity_blog_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'charity_faq',
    fields: [
      { name: 'question', type: 'string', required: true, maxLength: 300, searchable: true },
      { name: 'answer', type: 'text', required: true, searchable: true },
      { name: 'category', type: 'string', indexed: true },
      { name: 'order', type: 'integer', default: 0 },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'charity_faq_cat_idx', fields: ['category'] }],
  },
  {
    name: 'charity_partners',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'type', type: 'string', enum: ['corporate', 'ngo', 'government', 'individual', 'religious'], default: 'corporate', indexed: true },
      { name: 'logoUrl', type: 'url' },
      { name: 'websiteUrl', type: 'url' },
      { name: 'description', type: 'text' },
      { name: 'contributionValue', type: 'number', default: 0 },
      { name: 'partnershipStart', type: 'date' },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'charity_part_type_idx', fields: ['type'] }],
  },
  {
    name: 'charity_products',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'name', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'price', type: 'number', required: true },
      { name: 'category', type: 'string', indexed: true },
      { name: 'images', type: 'array', of: 'url', default: [] },
      { name: 'stock', type: 'integer', default: 0 },
      { name: 'sku', type: 'string', unique: true, indexed: true },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'charity_prod_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'charity_orders',
    fields: [
      { name: 'orderNumber', type: 'string', required: true, unique: true, indexed: true },
      { name: 'customerName', type: 'string', required: true },
      { name: 'customerEmail', type: 'email', required: true },
      { name: 'items', type: 'array', of: 'json', default: [] },
      { name: 'total', type: 'number', required: true },
      { name: 'status', type: 'string', enum: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'], default: 'pending', indexed: true },
      { name: 'paymentStatus', type: 'string', enum: ['unpaid', 'paid'], default: 'unpaid' },
      { name: 'placedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_ord_num_idx', fields: ['orderNumber'], unique: true }],
  },
  {
    name: 'charity_reports',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'type', type: 'string', enum: ['financial', 'impact', 'annual', 'campaign', 'donor'], indexed: true },
      { name: 'period', type: 'string' },
      { name: 'summary', type: 'text' },
      { name: 'fileUrl', type: 'url' },
      { name: 'data', type: 'json', default: {} },
      { name: 'generatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'charity_rep_type_idx', fields: ['type'] }],
  },
];
