/**
 * Masjid platform collection schemas.
 */

export const masjidSchemas = [
  {
    name: 'masjid_pages',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'json', default: [] },
      { name: 'seoTitle', type: 'string', maxLength: 200 },
      { name: 'seoDescription', type: 'text', maxLength: 300 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
      { name: 'order', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'masjid_pages_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'masjid_announcements',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'message', type: 'text', required: true },
      { name: 'type', type: 'string', enum: ['info', 'warning', 'urgent', 'success'], default: 'info', indexed: true },
      { name: 'active', type: 'boolean', default: true, indexed: true },
      { name: 'startsAt', type: 'datetime' },
      { name: 'endsAt', type: 'datetime' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'masjid_ann_active_idx', fields: ['active'] }],
  },
  {
    name: 'masjid_prayer_times',
    fields: [
      { name: 'date', type: 'date', required: true, unique: true, indexed: true },
      { name: 'fajrAdhan', type: 'string', required: true },
      { name: 'fajrIqamah', type: 'string', required: true },
      { name: 'sunrise', type: 'string', required: true },
      { name: 'dhuhrAdhan', type: 'string', required: true },
      { name: 'dhuhrIqamah', type: 'string', required: true },
      { name: 'asrAdhan', type: 'string', required: true },
      { name: 'asrIqamah', type: 'string', required: true },
      { name: 'maghribAdhan', type: 'string', required: true },
      { name: 'maghribIqamah', type: 'string', required: true },
      { name: 'ishaAdhan', type: 'string', required: true },
      { name: 'ishaIqamah', type: 'string', required: true },
      { name: 'jumuahAdhan', type: 'string' },
      { name: 'jumuahIqamah', type: 'string' },
    ],
    indexes: [{ name: 'masjid_pt_date_idx', fields: ['date'], unique: true }],
  },
  {
    name: 'masjid_events',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true },
      { name: 'category', type: 'string', enum: ['khutbah', 'halaqah', 'special', 'youth', 'ramadan', 'eid', 'other'], default: 'other', indexed: true },
      { name: 'startDate', type: 'datetime', required: true, indexed: true },
      { name: 'endDate', type: 'datetime' },
      { name: 'location', type: 'string' },
      { name: 'speaker', type: 'string' },
      { name: 'imageUrl', type: 'url' },
      { name: 'isRecurring', type: 'boolean', default: false },
      { name: 'recurrencePattern', type: 'string' },
    ],
    indexes: [{ name: 'masjid_events_start_idx', fields: ['startDate'] }],
  },
  {
    name: 'masjid_audios',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'speaker', type: 'string', required: true, indexed: true },
      { name: 'topic', type: 'string', indexed: true },
      { name: 'category', type: 'string', enum: ['khutbah', 'lecture', 'recitation', 'dua', 'halaqah', 'other'], default: 'lecture', indexed: true },
      { name: 'description', type: 'text' },
      { name: 'audioUrl', type: 'url' },
      { name: 'archiveOrgId', type: 'string' },
      { name: 'duration', type: 'integer', default: 0 },
      { name: 'date', type: 'date', indexed: true },
      { name: 'imageUrl', type: 'url' },
      { name: 'downloads', type: 'integer', default: 0 },
      { name: 'plays', type: 'integer', default: 0 },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [
      { name: 'masjid_audio_speaker_idx', fields: ['speaker'] },
      { name: 'masjid_audio_cat_idx', fields: ['category'] },
    ],
  },
  {
    name: 'masjid_videos',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'description', type: 'text' },
      { name: 'videoUrl', type: 'url' },
      { name: 'youtubeId', type: 'string' },
      { name: 'thumbnailUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'duration', type: 'integer', default: 0 },
      { name: 'date', type: 'date', indexed: true },
      { name: 'views', type: 'integer', default: 0 },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'masjid_vid_cat_idx', fields: ['category'] }],
  },
  {
    name: 'masjid_books',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'author', type: 'string', required: true, indexed: true },
      { name: 'category', type: 'string', indexed: true },
      { name: 'description', type: 'text' },
      { name: 'coverImageUrl', type: 'url' },
      { name: 'pdfUrl', type: 'url' },
      { name: 'isDigital', type: 'boolean', default: true },
      { name: 'price', type: 'number', default: 0 },
      { name: 'stock', type: 'integer', default: 0 },
      { name: 'pages', type: 'integer' },
      { name: 'language', type: 'string', default: 'English' },
      { name: 'available', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'masjid_books_cat_idx', fields: ['category'] }],
  },
  {
    name: 'masjid_blog_posts',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'excerpt', type: 'text', maxLength: 500 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'featuredImageUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'authorName', type: 'string' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime', indexed: true },
      { name: 'views', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'masjid_blog_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'masjid_gallery',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 120 },
      { name: 'description', type: 'text' },
      { name: 'imageUrl', type: 'url', required: true },
      { name: 'videoUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'eventDate', type: 'date' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'masjid_gal_cat_idx', fields: ['category'] }],
  },
  {
    name: 'masjid_donation_campaigns',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'category', type: 'string', enum: ['zakaat', 'sadaqah', 'waqf', 'construction', 'operational', 'emergency'], required: true, indexed: true },
      { name: 'goalAmount', type: 'number', required: true },
      { name: 'raisedAmount', type: 'number', default: 0 },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'imageUrl', type: 'url' },
      { name: 'deadline', type: 'date' },
      { name: 'isUrgent', type: 'boolean', default: false, indexed: true },
      { name: 'status', type: 'string', enum: ['active', 'completed', 'paused', 'archived'], default: 'active', indexed: true },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'masjid_dc_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'masjid_donations',
    fields: [
      { name: 'campaignId', type: 'string', indexed: true },
      { name: 'donorName', type: 'string', required: true },
      { name: 'donorEmail', type: 'email', indexed: true },
      { name: 'donorPhone', type: 'phone' },
      { name: 'amount', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'category', type: 'string', enum: ['zakaat', 'sadaqah', 'waqf', 'construction', 'operational', 'emergency'], indexed: true },
      { name: 'type', type: 'string', enum: ['one-time', 'recurring'], default: 'one-time' },
      { name: 'method', type: 'string', enum: ['card', 'bank_transfer', 'cash', 'mobile_money'] },
      { name: 'reference', type: 'string', unique: true, indexed: true },
      { name: 'status', type: 'string', enum: ['pending', 'successful', 'failed'], default: 'pending', indexed: true },
      { name: 'isAnonymous', type: 'boolean', default: false },
      { name: 'message', type: 'text' },
      { name: 'donatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'masjid_don_ref_idx', fields: ['reference'], unique: true }],
  },
  {
    name: 'masjid_donors',
    fields: [
      { name: 'email', type: 'email', required: true, unique: true, indexed: true },
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'phone', type: 'phone' },
      { name: 'totalDonated', type: 'number', default: 0 },
      { name: 'donationCount', type: 'integer', default: 0 },
      { name: 'firstDonationAt', type: 'datetime' },
      { name: 'lastDonationAt', type: 'datetime' },
      { name: 'isRecurring', type: 'boolean', default: false },
      { name: 'tags', type: 'array', of: 'string', default: [] },
    ],
    indexes: [{ name: 'masjid_donors_email_idx', fields: ['email'], unique: true }],
  },
  {
    name: 'masjid_live_streams',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text' },
      { name: 'streamUrl', type: 'url', required: true },
      { name: 'embedUrl', type: 'url' },
      { name: 'isLive', type: 'boolean', default: false, indexed: true },
      { name: 'scheduledAt', type: 'datetime', indexed: true },
      { name: 'endedAt', type: 'datetime' },
      { name: 'thumbnailUrl', type: 'url' },
    ],
    indexes: [{ name: 'masjid_live_idx', fields: ['isLive'] }],
  },
  {
    name: 'masjid_quran_config',
    fields: [
      { name: 'defaultReciter', type: 'string', required: true },
      { name: 'reciterName', type: 'string' },
      { name: 'streamUrl', type: 'url' },
      { name: 'apiSource', type: 'url' },
      { name: 'playlists', type: 'array', of: 'json', default: [] },
      { name: 'active', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'masjid_quran_active_idx', fields: ['active'] }],
  },
  {
    name: 'masjid_imams',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'title', type: 'string' },
      { name: 'role', type: 'string', enum: ['imam', 'assistant-imam', 'muadhin', 'teacher', 'staff'], default: 'imam', indexed: true },
      { name: 'bio', type: 'text' },
      { name: 'photoUrl', type: 'url' },
      { name: 'email', type: 'email' },
      { name: 'phone', type: 'phone' },
      { name: 'specializations', type: 'array', of: 'string', default: [] },
      { name: 'active', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'masjid_imam_role_idx', fields: ['role'] }],
  },
];
