/**
 * School platform collection schemas.
 */

export const schoolSchemas = [
  // === Content ===
  {
    name: 'school_pages',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'json', default: [] },
      { name: 'seoTitle', type: 'string', maxLength: 200 },
      { name: 'seoDescription', type: 'text', maxLength: 300 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
      { name: 'author', type: 'string' },
      { name: 'order', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'school_pages_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'school_blog_posts',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'excerpt', type: 'text', maxLength: 500 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'featuredImageUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'authorName', type: 'string' },
      { name: 'authorAvatarUrl', type: 'url' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime', indexed: true },
      { name: 'readingTimeMinutes', type: 'integer', default: 5 },
      { name: 'views', type: 'integer', default: 0 },
    ],
    indexes: [
      { name: 'school_blog_slug_idx', fields: ['slug'], unique: true },
      { name: 'school_blog_status_date_idx', fields: ['status', 'publishedAt'] },
    ],
  },
  {
    name: 'school_announcements',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'message', type: 'text', required: true },
      { name: 'type', type: 'string', enum: ['info', 'warning', 'urgent', 'success'], default: 'info', indexed: true },
      { name: 'audience', type: 'string', enum: ['all', 'parents', 'students', 'staff'], default: 'all' },
      { name: 'active', type: 'boolean', default: true, indexed: true },
      { name: 'startsAt', type: 'datetime' },
      { name: 'endsAt', type: 'datetime' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_ann_active_idx', fields: ['active'] }],
  },
  {
    name: 'school_events',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true },
      { name: 'category', type: 'string', enum: ['exam', 'holiday', 'sports', 'parent-teacher', 'cultural', 'other'], default: 'other', indexed: true },
      { name: 'startDate', type: 'datetime', required: true, indexed: true },
      { name: 'endDate', type: 'datetime' },
      { name: 'location', type: 'string' },
      { name: 'imageUrl', type: 'url' },
      { name: 'isRecurring', type: 'boolean', default: false },
      { name: 'recurrencePattern', type: 'string' },
    ],
    indexes: [{ name: 'school_events_start_idx', fields: ['startDate'] }],
  },
  {
    name: 'school_gallery_albums',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 120 },
      { name: 'description', type: 'text' },
      { name: 'coverImageUrl', type: 'url' },
      { name: 'images', type: 'array', of: 'json', default: [] },
      { name: 'category', type: 'string', indexed: true },
      { name: 'eventDate', type: 'date' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_gallery_cat_idx', fields: ['category'] }],
  },
  // === Academic ===
  {
    name: 'school_students',
    fields: [
      { name: 'studentId', type: 'string', required: true, unique: true, indexed: true },
      { name: 'firstName', type: 'string', required: true, maxLength: 60 },
      { name: 'lastName', type: 'string', required: true, maxLength: 60 },
      { name: 'dateOfBirth', type: 'date', required: true },
      { name: 'gender', type: 'string', enum: ['male', 'female'], required: true },
      { name: 'classId', type: 'string', indexed: true },
      { name: 'className', type: 'string' },
      { name: 'enrollmentDate', type: 'date' },
      { name: 'status', type: 'string', enum: ['active', 'graduated', 'transferred', 'inactive'], default: 'active', indexed: true },
      { name: 'guardianName', type: 'string', required: true },
      { name: 'guardianPhone', type: 'phone', required: true },
      { name: 'guardianEmail', type: 'email' },
      { name: 'guardianRelationship', type: 'string' },
      { name: 'address', type: 'text' },
      { name: 'photoUrl', type: 'url' },
      { name: 'medicalInfo', type: 'json', default: {} },
      { name: 'previousSchool', type: 'string' },
    ],
    indexes: [
      { name: 'school_students_id_idx', fields: ['studentId'], unique: true },
      { name: 'school_students_status_idx', fields: ['status'] },
      { name: 'school_students_class_idx', fields: ['classId'] },
    ],
  },
  {
    name: 'school_staff',
    fields: [
      { name: 'staffId', type: 'string', required: true, unique: true, indexed: true },
      { name: 'firstName', type: 'string', required: true, maxLength: 60 },
      { name: 'lastName', type: 'string', required: true, maxLength: 60 },
      { name: 'role', type: 'string', required: true, enum: ['teacher', 'admin', 'principal', 'vice-principal', 'librarian', 'accountant', 'support'], indexed: true },
      { name: 'subjects', type: 'array', of: 'string', default: [] },
      { name: 'qualifications', type: 'text' },
      { name: 'email', type: 'email', required: true, unique: true, indexed: true },
      { name: 'phone', type: 'phone' },
      { name: 'photoUrl', type: 'url' },
      { name: 'bio', type: 'text' },
      { name: 'joinDate', type: 'date' },
      { name: 'status', type: 'string', enum: ['active', 'on-leave', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [
      { name: 'school_staff_id_idx', fields: ['staffId'], unique: true },
      { name: 'school_staff_role_idx', fields: ['role'] },
    ],
  },
  {
    name: 'school_classes',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 60 },
      { name: 'level', type: 'string', required: true, enum: ['creche', 'nursery', 'primary', 'junior-secondary', 'senior-secondary'], indexed: true },
      { name: 'grade', type: 'string' },
      { name: 'teacherId', type: 'string', indexed: true },
      { name: 'teacherName', type: 'string' },
      { name: 'room', type: 'string' },
      { name: 'capacity', type: 'integer', default: 30 },
      { name: 'currentEnrollment', type: 'integer', default: 0 },
      { name: 'subjects', type: 'array', of: 'string', default: [] },
      { name: 'schedule', type: 'json', default: {} },
      { name: 'description', type: 'text' },
      { name: 'active', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'school_classes_level_idx', fields: ['level'] }],
  },
  {
    name: 'school_programs',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 120 },
      { name: 'category', type: 'string', required: true, enum: ['academic', 'islamic-studies', 'extracurricular', 'sports', 'arts'], indexed: true },
      { name: 'description', type: 'text', required: true },
      { name: 'curriculum', type: 'text' },
      { name: 'duration', type: 'string' },
      { name: 'requirements', type: 'array', of: 'string', default: [] },
      { name: 'outcomes', type: 'array', of: 'string', default: [] },
      { name: 'imageUrl', type: 'url' },
      { name: 'instructor', type: 'string' },
      { name: 'fee', type: 'number', default: 0 },
      { name: 'status', type: 'string', enum: ['open', 'closed', 'archived'], default: 'open', indexed: true },
    ],
    indexes: [{ name: 'school_prog_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'school_admission_applications',
    fields: [
      { name: 'applicationId', type: 'string', required: true, unique: true, indexed: true },
      { name: 'studentFirstName', type: 'string', required: true, maxLength: 60 },
      { name: 'studentLastName', type: 'string', required: true, maxLength: 60 },
      { name: 'studentDateOfBirth', type: 'date', required: true },
      { name: 'studentGender', type: 'string', enum: ['male', 'female'], required: true },
      { name: 'appliedClass', type: 'string', required: true, indexed: true },
      { name: 'previousSchool', type: 'string' },
      { name: 'guardianName', type: 'string', required: true },
      { name: 'guardianPhone', type: 'phone', required: true },
      { name: 'guardianEmail', type: 'email', required: true },
      { name: 'guardianOccupation', type: 'string' },
      { name: 'address', type: 'text', required: true },
      { name: 'additionalInfo', type: 'text' },
      { name: 'status', type: 'string', enum: ['pending', 'reviewed', 'accepted', 'rejected', 'waitlisted'], default: 'pending', indexed: true },
      { name: 'submittedAt', type: 'datetime' },
      { name: 'reviewedAt', type: 'datetime' },
      { name: 'reviewNotes', type: 'text' },
    ],
    indexes: [
      { name: 'school_adm_app_id_idx', fields: ['applicationId'], unique: true },
      { name: 'school_adm_app_status_idx', fields: ['status'] },
    ],
  },
  // === LMS ===
  {
    name: 'school_courses',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'shortDescription', type: 'text', maxLength: 300 },
      { name: 'category', type: 'string', indexed: true },
      { name: 'level', type: 'string', enum: ['beginner', 'intermediate', 'advanced'], default: 'beginner', indexed: true },
      { name: 'instructor', type: 'string' },
      { name: 'instructorBio', type: 'text' },
      { name: 'price', type: 'number', default: 0 },
      { name: 'duration', type: 'string' },
      { name: 'thumbnailUrl', type: 'url' },
      { name: 'lessonsCount', type: 'integer', default: 0 },
      { name: 'enrolledCount', type: 'integer', default: 0 },
      { name: 'rating', type: 'number', default: 0 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_courses_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'school_lessons',
    fields: [
      { name: 'courseId', type: 'string', required: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'text' },
      { name: 'videoUrl', type: 'url' },
      { name: 'duration', type: 'integer', default: 0 },
      { name: 'order', type: 'integer', required: true, default: 0 },
      { name: 'resources', type: 'array', of: 'json', default: [] },
      { name: 'isPreview', type: 'boolean', default: false },
    ],
    indexes: [{ name: 'school_lessons_course_idx', fields: ['courseId'] }],
  },
  {
    name: 'school_quizzes',
    fields: [
      { name: 'courseId', type: 'string', indexed: true },
      { name: 'lessonId', type: 'string', indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text' },
      { name: 'questions', type: 'array', of: 'json', default: [] },
      { name: 'timeLimitMinutes', type: 'integer', default: 30 },
      { name: 'passingScore', type: 'integer', default: 70 },
      { name: 'attempts', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'school_quiz_course_idx', fields: ['courseId'] }],
  },
  {
    name: 'school_assignments',
    fields: [
      { name: 'courseId', type: 'string', required: true, indexed: true },
      { name: 'lessonId', type: 'string', indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true },
      { name: 'dueDate', type: 'datetime', indexed: true },
      { name: 'maxScore', type: 'integer', default: 100 },
      { name: 'submissionType', type: 'string', enum: ['text', 'file', 'both'], default: 'text' },
    ],
    indexes: [{ name: 'school_assign_course_idx', fields: ['courseId'] }],
  },
  {
    name: 'school_enrollments',
    fields: [
      { name: 'courseId', type: 'string', required: true, indexed: true },
      { name: 'studentId', type: 'string', required: true, indexed: true },
      { name: 'studentName', type: 'string' },
      { name: 'enrolledAt', type: 'datetime' },
      { name: 'progress', type: 'number', default: 0 },
      { name: 'completedLessons', type: 'array', of: 'string', default: [] },
      { name: 'lastAccessedAt', type: 'datetime' },
      { name: 'status', type: 'string', enum: ['active', 'completed', 'dropped'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'school_enr_course_student_idx', fields: ['courseId', 'studentId'], unique: true }],
  },
  {
    name: 'school_exam_schedules',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'classId', type: 'string', required: true, indexed: true },
      { name: 'subject', type: 'string', required: true },
      { name: 'examDate', type: 'datetime', required: true, indexed: true },
      { name: 'duration', type: 'integer', default: 120 },
      { name: 'room', type: 'string' },
      { name: 'totalMarks', type: 'integer', default: 100 },
      { name: 'status', type: 'string', enum: ['scheduled', 'ongoing', 'completed', 'cancelled'], default: 'scheduled', indexed: true },
    ],
    indexes: [{ name: 'school_exam_date_idx', fields: ['examDate'] }],
  },
  {
    name: 'school_exam_results',
    fields: [
      { name: 'examId', type: 'string', required: true, indexed: true },
      { name: 'studentId', type: 'string', required: true, indexed: true },
      { name: 'studentName', type: 'string' },
      { name: 'score', type: 'integer', required: true },
      { name: 'totalMarks', type: 'integer', default: 100 },
      { name: 'grade', type: 'string' },
      { name: 'remarks', type: 'text' },
      { name: 'publishedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_exam_res_idx', fields: ['examId', 'studentId'], unique: true }],
  },
  // === Finance ===
  {
    name: 'school_fees',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'classLevel', type: 'string', indexed: true },
      { name: 'amount', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'frequency', type: 'string', enum: ['one-time', 'per-term', 'annual'], default: 'per-term' },
      { name: 'category', type: 'string', enum: ['tuition', 'transport', 'uniform', 'books', 'activities', 'other'], indexed: true },
      { name: 'description', type: 'text' },
      { name: 'active', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'school_fees_cat_idx', fields: ['category'] }],
  },
  {
    name: 'school_invoices',
    fields: [
      { name: 'invoiceNumber', type: 'string', required: true, unique: true, indexed: true },
      { name: 'studentId', type: 'string', required: true, indexed: true },
      { name: 'studentName', type: 'string' },
      { name: 'items', type: 'array', of: 'json', default: [] },
      { name: 'totalAmount', type: 'number', required: true },
      { name: 'paidAmount', type: 'number', default: 0 },
      { name: 'status', type: 'string', enum: ['unpaid', 'partial', 'paid', 'overdue'], default: 'unpaid', indexed: true },
      { name: 'dueDate', type: 'date', indexed: true },
      { name: 'issuedAt', type: 'datetime' },
      { name: 'term', type: 'string' },
      { name: 'academicYear', type: 'string' },
    ],
    indexes: [
      { name: 'school_inv_num_idx', fields: ['invoiceNumber'], unique: true },
      { name: 'school_inv_status_idx', fields: ['status'] },
    ],
  },
  {
    name: 'school_payments',
    fields: [
      { name: 'invoiceId', type: 'string', required: true, indexed: true },
      { name: 'studentId', type: 'string', indexed: true },
      { name: 'amount', type: 'number', required: true },
      { name: 'method', type: 'string', enum: ['card', 'bank_transfer', 'cash', 'mobile_money'], required: true },
      { name: 'reference', type: 'string', unique: true, indexed: true },
      { name: 'status', type: 'string', enum: ['pending', 'successful', 'failed'], default: 'pending', indexed: true },
      { name: 'paidAt', type: 'datetime' },
      { name: 'receiptUrl', type: 'url' },
    ],
    indexes: [{ name: 'school_pay_ref_idx', fields: ['reference'], unique: true }],
  },
  // === Shop ===
  {
    name: 'school_products',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'name', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'price', type: 'number', required: true },
      { name: 'compareAtPrice', type: 'number' },
      { name: 'category', type: 'string', enum: ['books', 'uniforms', 'supplies', 'digital', 'other'], indexed: true },
      { name: 'images', type: 'array', of: 'url', default: [] },
      { name: 'stock', type: 'integer', default: 0 },
      { name: 'sku', type: 'string', unique: true, indexed: true },
      { name: 'variants', type: 'array', of: 'json', default: [] },
      { name: 'isDigital', type: 'boolean', default: false },
      { name: 'downloadUrl', type: 'url' },
      { name: 'status', type: 'string', enum: ['active', 'inactive'], default: 'active', indexed: true },
    ],
    indexes: [
      { name: 'school_prod_slug_idx', fields: ['slug'], unique: true },
      { name: 'school_prod_cat_idx', fields: ['category'] },
    ],
  },
  {
    name: 'school_orders',
    fields: [
      { name: 'orderNumber', type: 'string', required: true, unique: true, indexed: true },
      { name: 'customerName', type: 'string', required: true },
      { name: 'customerEmail', type: 'email', required: true },
      { name: 'customerPhone', type: 'phone' },
      { name: 'items', type: 'array', of: 'json', default: [] },
      { name: 'subtotal', type: 'number', required: true },
      { name: 'shipping', type: 'number', default: 0 },
      { name: 'total', type: 'number', required: true },
      { name: 'status', type: 'string', enum: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'], default: 'pending', indexed: true },
      { name: 'paymentStatus', type: 'string', enum: ['unpaid', 'paid', 'refunded'], default: 'unpaid' },
      { name: 'shippingAddress', type: 'json' },
      { name: 'placedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_ord_num_idx', fields: ['orderNumber'], unique: true }],
  },
  // === Library ===
  {
    name: 'school_library_books',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'author', type: 'string', required: true, indexed: true },
      { name: 'isbn', type: 'string', unique: true, indexed: true },
      { name: 'category', type: 'string', indexed: true },
      { name: 'description', type: 'text' },
      { name: 'coverImageUrl', type: 'url' },
      { name: 'pdfUrl', type: 'url' },
      { name: 'pages', type: 'integer' },
      { name: 'language', type: 'string', default: 'English' },
      { name: 'publisher', type: 'string' },
      { name: 'publishYear', type: 'integer' },
      { name: 'isDigital', type: 'boolean', default: true },
      { name: 'available', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'school_lib_cat_idx', fields: ['category'] }],
  },
  {
    name: 'school_wiki_articles',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'category', type: 'string', required: true, indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'author', type: 'string' },
      { name: 'order', type: 'integer', default: 0 },
      { name: 'views', type: 'integer', default: 0 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'updatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_wiki_slug_idx', fields: ['slug'], unique: true }],
  },
  // === Misc ===
  {
    name: 'school_testimonials',
    fields: [
      { name: 'authorName', type: 'string', required: true, maxLength: 120 },
      { name: 'authorRole', type: 'string' },
      { name: 'authorAvatarUrl', type: 'url' },
      { name: 'content', type: 'text', required: true },
      { name: 'rating', type: 'integer', default: 5, minimum: 1, maximum: 5 },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected'], default: 'pending', indexed: true },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_test_status_idx', fields: ['status'] }],
  },
  {
    name: 'school_messages',
    fields: [
      { name: 'studentId', type: 'string', required: true, indexed: true },
      { name: 'studentName', type: 'string' },
      { name: 'teacherId', type: 'string', required: true, indexed: true },
      { name: 'teacherName', type: 'string' },
      { name: 'subject', type: 'string', required: true, maxLength: 200 },
      { name: 'body', type: 'text', required: true },
      { name: 'fromRole', type: 'string', enum: ['student', 'teacher'] },
      { name: 'read', type: 'boolean', default: false },
      { name: 'sentAt', type: 'datetime' },
    ],
    indexes: [{ name: 'school_msg_student_idx', fields: ['studentId'] }],
  },
];
