/**
 * Travels & Tours platform collection schemas.
 */

export const travelsSchemas = [
  {
    name: 'travels_pages',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'json', default: [] },
      { name: 'seoTitle', type: 'string', maxLength: 200 },
      { name: 'seoDescription', type: 'text', maxLength: 300 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
      { name: 'order', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'travels_pages_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'travels_packages',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'shortDescription', type: 'text', maxLength: 300 },
      { name: 'type', type: 'string', enum: ['hajj', 'umrah', 'local-tour', 'international-tour'], required: true, indexed: true },
      { name: 'tier', type: 'string', enum: ['standard', 'deluxe', 'vip'], default: 'standard', indexed: true },
      { name: 'destination', type: 'string', required: true, indexed: true },
      { name: 'duration', type: 'string' },
      { name: 'durationDays', type: 'integer', default: 7 },
      { name: 'basePrice', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'inclusions', type: 'array', of: 'string', default: [] },
      { name: 'exclusions', type: 'array', of: 'string', default: [] },
      { name: 'itinerary', type: 'array', of: 'json', default: [] },
      { name: 'imageUrl', type: 'url' },
      { name: 'galleryImages', type: 'array', of: 'url', default: [] },
      { name: 'capacity', type: 'integer', default: 50 },
      { name: 'availableSlots', type: 'integer', default: 50 },
      { name: 'startDate', type: 'date', indexed: true },
      { name: 'endDate', type: 'date' },
      { name: 'isFeatured', type: 'boolean', default: false, indexed: true },
      { name: 'status', type: 'string', enum: ['active', 'inactive', 'sold-out'], default: 'active', indexed: true },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_pkg_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'travels_itineraries',
    fields: [
      { name: 'packageId', type: 'string', required: true, indexed: true },
      { name: 'day', type: 'integer', required: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true },
      { name: 'activities', type: 'array', of: 'string', default: [] },
      { name: 'meals', type: 'array', of: 'string', default: [] },
      { name: 'accommodation', type: 'string' },
      { name: 'imageUrl', type: 'url' },
    ],
    indexes: [{ name: 'travels_itin_pkg_idx', fields: ['packageId'] }],
  },
  {
    name: 'travels_bookings',
    fields: [
      { name: 'bookingNumber', type: 'string', required: true, unique: true, indexed: true },
      { name: 'packageId', type: 'string', required: true, indexed: true },
      { name: 'packageTitle', type: 'string' },
      { name: 'customerId', type: 'string', required: true, indexed: true },
      { name: 'customerName', type: 'string', required: true },
      { name: 'customerEmail', type: 'email', required: true },
      { name: 'customerPhone', type: 'phone', required: true },
      { name: 'travelers', type: 'array', of: 'json', default: [] },
      { name: 'travelerCount', type: 'integer', default: 1 },
      { name: 'startDate', type: 'date', required: true, indexed: true },
      { name: 'endDate', type: 'date' },
      { name: 'totalAmount', type: 'number', required: true },
      { name: 'paidAmount', type: 'number', default: 0 },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'status', type: 'string', enum: ['pending', 'confirmed', 'completed', 'cancelled'], default: 'pending', indexed: true },
      { name: 'paymentStatus', type: 'string', enum: ['unpaid', 'partial', 'paid', 'refunded'], default: 'unpaid', indexed: true },
      { name: 'specialRequests', type: 'text' },
      { name: 'bookedAt', type: 'datetime' },
      { name: 'confirmedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_book_num_idx', fields: ['bookingNumber'], unique: true }],
  },
  {
    name: 'travels_booking_travelers',
    fields: [
      { name: 'bookingId', type: 'string', required: true, indexed: true },
      { name: 'fullName', type: 'string', required: true, maxLength: 120 },
      { name: 'passportNumber', type: 'string', required: true, encrypted: true },
      { name: 'dateOfBirth', type: 'date', required: true },
      { name: 'gender', type: 'string', enum: ['male', 'female'] },
      { name: 'nationality', type: 'string' },
      { name: 'relationship', type: 'string' },
      { name: 'specialNeeds', type: 'text' },
    ],
    indexes: [{ name: 'travels_bt_book_idx', fields: ['bookingId'] }],
  },
  {
    name: 'travels_payments',
    fields: [
      { name: 'bookingId', type: 'string', required: true, indexed: true },
      { name: 'amount', type: 'number', required: true },
      { name: 'currency', type: 'string', default: 'NGN' },
      { name: 'method', type: 'string', enum: ['card', 'bank_transfer', 'cash', 'mobile_money'], required: true },
      { name: 'reference', type: 'string', unique: true, indexed: true },
      { name: 'status', type: 'string', enum: ['pending', 'successful', 'failed'], default: 'pending', indexed: true },
      { name: 'isInstallment', type: 'boolean', default: false },
      { name: 'installmentNumber', type: 'integer', default: 0 },
      { name: 'paidAt', type: 'datetime' },
      { name: 'receiptUrl', type: 'url' },
    ],
    indexes: [{ name: 'travels_pay_ref_idx', fields: ['reference'], unique: true }],
  },
  {
    name: 'travels_customers',
    fields: [
      { name: 'email', type: 'email', required: true, unique: true, indexed: true },
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'phone', type: 'phone', required: true },
      { name: 'address', type: 'text' },
      { name: 'dateOfBirth', type: 'date' },
      { name: 'gender', type: 'string', enum: ['male', 'female'] },
      { name: 'nationality', type: 'string' },
      { name: 'passportNumber', type: 'string', encrypted: true },
      { name: 'passportExpiry', type: 'date', encrypted: true },
      { name: 'totalBookings', type: 'integer', default: 0 },
      { name: 'totalSpent', type: 'number', default: 0 },
      { name: 'firstBookingAt', type: 'datetime' },
      { name: 'lastBookingAt', type: 'datetime' },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'notes', type: 'text' },
    ],
    indexes: [{ name: 'travels_cust_email_idx', fields: ['email'], unique: true }],
  },
  {
    name: 'travels_documents',
    fields: [
      { name: 'bookingId', type: 'string', required: true, indexed: true },
      { name: 'customerId', type: 'string', indexed: true },
      { name: 'type', type: 'string', enum: ['ticket', 'visa', 'voucher', 'itinerary', 'invoice', 'other'], required: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'fileUrl', type: 'url', required: true },
      { name: 'uploadedAt', type: 'datetime' },
      { name: 'expiresAt', type: 'date' },
    ],
    indexes: [{ name: 'travels_doc_book_idx', fields: ['bookingId'] }],
  },
  {
    name: 'travels_pricing_rules',
    fields: [
      { name: 'packageId', type: 'string', indexed: true },
      { name: 'type', type: 'string', enum: ['early-bird', 'group-discount', 'seasonal-surcharge', 'last-minute', 'custom'], required: true, indexed: true },
      { name: 'ruleName', type: 'string', required: true, maxLength: 120 },
      { name: 'discountPercent', type: 'number', default: 0 },
      { name: 'surchargePercent', type: 'number', default: 0 },
      { name: 'minGroupSize', type: 'integer', default: 1 },
      { name: 'daysBeforeDeparture', type: 'integer' },
      { name: 'startDate', type: 'date' },
      { name: 'endDate', type: 'date' },
      { name: 'active', type: 'boolean', default: true, indexed: true },
    ],
    indexes: [{ name: 'travels_pr_pkg_idx', fields: ['packageId'] }],
  },
  {
    name: 'travels_availability',
    fields: [
      { name: 'packageId', type: 'string', required: true, indexed: true },
      { name: 'date', type: 'date', required: true, indexed: true },
      { name: 'availableSlots', type: 'integer', required: true },
      { name: 'bookedSlots', type: 'integer', default: 0 },
      { name: 'price', type: 'number' },
      { name: 'status', type: 'string', enum: ['open', 'limited', 'closed'], default: 'open', indexed: true },
    ],
    indexes: [{ name: 'travels_avail_pkg_date_idx', fields: ['packageId', 'date'], unique: true }],
  },
  {
    name: 'travels_reviews',
    fields: [
      { name: 'packageId', type: 'string', indexed: true },
      { name: 'bookingId', type: 'string', indexed: true },
      { name: 'customerName', type: 'string', required: true, maxLength: 120 },
      { name: 'customerAvatarUrl', type: 'url' },
      { name: 'rating', type: 'integer', required: true, minimum: 1, maximum: 5, indexed: true },
      { name: 'title', type: 'string', maxLength: 200 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'images', type: 'array', of: 'url', default: [] },
      { name: 'isVerified', type: 'boolean', default: true },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected'], default: 'approved', indexed: true },
      { name: 'submittedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_rev_pkg_idx', fields: ['packageId'] }],
  },
  {
    name: 'travels_blog_posts',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'excerpt', type: 'text', maxLength: 500 },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'featuredImageUrl', type: 'url' },
      { name: 'category', type: 'string', indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'authorName', type: 'string' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime', indexed: true },
      { name: 'views', type: 'integer', default: 0 },
    ],
    indexes: [{ name: 'travels_blog_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'travels_resources',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200, searchable: true },
      { name: 'content', type: 'text', required: true, searchable: true },
      { name: 'category', type: 'string', enum: ['visa', 'passport', 'packing', 'rituals', 'health', 'currency', 'emergency', 'tips'], required: true, indexed: true },
      { name: 'tags', type: 'array', of: 'string', default: [] },
      { name: 'attachments', type: 'array', of: 'json', default: [] },
      { name: 'author', type: 'string' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'updatedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_res_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'travels_courses',
    fields: [
      { name: 'slug', type: 'string', required: true, unique: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'description', type: 'text', required: true, searchable: true },
      { name: 'shortDescription', type: 'text', maxLength: 300 },
      { name: 'category', type: 'string', enum: ['hajj-rituals', 'umrah-guide', 'makkah-history', 'madinah-history', 'practical-tips'], indexed: true },
      { name: 'level', type: 'string', enum: ['beginner', 'intermediate', 'advanced'], default: 'beginner' },
      { name: 'instructor', type: 'string' },
      { name: 'price', type: 'number', default: 0 },
      { name: 'duration', type: 'string' },
      { name: 'thumbnailUrl', type: 'url' },
      { name: 'lessonsCount', type: 'integer', default: 0 },
      { name: 'enrolledCount', type: 'integer', default: 0 },
      { name: 'rating', type: 'number', default: 0 },
      { name: 'status', type: 'string', enum: ['draft', 'published'], default: 'draft', indexed: true },
      { name: 'publishedAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_course_slug_idx', fields: ['slug'], unique: true }],
  },
  {
    name: 'travels_lessons',
    fields: [
      { name: 'courseId', type: 'string', required: true, indexed: true },
      { name: 'title', type: 'string', required: true, maxLength: 200 },
      { name: 'content', type: 'text' },
      { name: 'videoUrl', type: 'url' },
      { name: 'duration', type: 'integer', default: 0 },
      { name: 'order', type: 'integer', required: true, default: 0 },
      { name: 'resources', type: 'array', of: 'json', default: [] },
      { name: 'isPreview', type: 'boolean', default: false },
    ],
    indexes: [{ name: 'travels_lesson_course_idx', fields: ['courseId'] }],
  },
  {
    name: 'travels_enrollments',
    fields: [
      { name: 'courseId', type: 'string', required: true, indexed: true },
      { name: 'customerId', type: 'string', required: true, indexed: true },
      { name: 'customerName', type: 'string' },
      { name: 'enrolledAt', type: 'datetime' },
      { name: 'progress', type: 'number', default: 0 },
      { name: 'completedLessons', type: 'array', of: 'string', default: [] },
      { name: 'lastAccessedAt', type: 'datetime' },
      { name: 'status', type: 'string', enum: ['active', 'completed', 'dropped'], default: 'active', indexed: true },
    ],
    indexes: [{ name: 'travels_enr_idx', fields: ['courseId', 'customerId'], unique: true }],
  },
  {
    name: 'travels_gallery',
    fields: [
      { name: 'title', type: 'string', required: true, maxLength: 120 },
      { name: 'description', type: 'text' },
      { name: 'imageUrl', type: 'url', required: true },
      { name: 'category', type: 'string', indexed: true },
      { name: 'destination', type: 'string' },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_gal_cat_idx', fields: ['category'] }],
  },
  {
    name: 'travels_inquiries',
    fields: [
      { name: 'name', type: 'string', required: true, maxLength: 120 },
      { name: 'email', type: 'email', required: true, indexed: true },
      { name: 'phone', type: 'phone', required: true },
      { name: 'packageId', type: 'string', indexed: true },
      { name: 'subject', type: 'string', required: true, maxLength: 200 },
      { name: 'message', type: 'text', required: true },
      { name: 'preferredDate', type: 'date' },
      { name: 'travelerCount', type: 'integer', default: 1 },
      { name: 'status', type: 'string', enum: ['new', 'responded', 'closed'], default: 'new', indexed: true },
      { name: 'createdAt', type: 'datetime' },
    ],
    indexes: [{ name: 'travels_inq_status_idx', fields: ['status'] }],
  },
];
