/**
 * Charity platform seed data - comprehensive production data.
 */

const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d) => new Date(now.getTime() + d * 86400000).toISOString();

export const charitySeedData = {
  charity_pages: [
    {
      slug: 'about',
      title: 'About Minhaajulhudaa Charity Foundation',
      content: [
        { type: 'hero', title: 'About Us', subtitle: 'Serving humanity with compassion' },
        { type: 'text', body: 'Minhaajulhudaa Charity Foundation was established in 2022 to serve vulnerable communities across Nigeria. Inspired by the Islamic principles of compassion and social justice, we work to alleviate poverty, provide education, ensure access to clean water, and respond to emergencies.' },
        { type: 'text', body: 'Our approach is holistic - we address immediate needs through emergency relief while investing in long-term solutions through education, skills training, and sustainable development projects. We believe in empowering communities rather than creating dependency.' },
        { type: 'text', body: 'We are registered with the Corporate Affairs Commission (RC-2022-0001) and operate with full transparency. All our financial reports are publicly available, and we maintain strict accountability for every donation we receive.' },
      ],
      seoTitle: 'About Minhaajulhudaa Charity',
      seoDescription: 'Learn about our mission to serve humanity with compassion.',
      status: 'published',
      publishedAt: daysAgo(60),
      order: 1,
    },
    {
      slug: 'how-to-help',
      title: 'How to Help',
      content: [
        { type: 'hero', title: 'How You Can Help', subtitle: 'Together we can make a difference' },
        { type: 'text', body: 'There are many ways to support our mission of serving those in need. Whether through financial contributions, volunteering your time, or spreading awareness, every effort counts.' },
      ],
      seoTitle: 'How to Help - Minhaajulhudaa Charity',
      seoDescription: 'Discover ways to support our charitable work.',
      status: 'published',
      publishedAt: daysAgo(60),
      order: 2,
    },
  ],

  charity_campaigns: [
    {
      slug: 'clean-water-for-all',
      title: 'Clean Water for All Communities',
      description: 'Help us build boreholes and water wells in communities lacking access to clean water. Each borehole serves an average of 500 people and lasts 15+ years with proper maintenance. Currently, millions of Nigerians lack access to safe drinking water, leading to waterborne diseases and lost productivity. Your donation will directly fund the construction of water infrastructure in the most needy communities.',
      shortDescription: 'Building boreholes and wells for communities without clean water access.',
      category: 'water',
      goalAmount: 15000000,
      raisedAmount: 9750000,
      currency: 'NGN',
      beneficiaryCount: 2500,
      imageUrl: 'https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=800', 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=800'],
      deadline: '2026-12-31',
      isUrgent: true,
      location: 'Northern Nigeria',
      status: 'active',
      createdAt: daysAgo(45),
      updatedAt: daysAgo(2),
    },
    {
      slug: 'feed-the-fasting',
      title: 'Feed the Fasting: Ramadan Food Program',
      description: 'Provide food packages to families in need during Ramadan. Each package feeds a family of 5 for the entire month and costs ₦25,000. This program distributes rice, beans, cooking oil, dates, and other essentials to families who cannot afford adequate meals for Suhoor and Iftar.',
      shortDescription: 'Providing food packages to families during Ramadan.',
      category: 'food',
      goalAmount: 5000000,
      raisedAmount: 3850000,
      currency: 'NGN',
      beneficiaryCount: 200,
      imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800'],
      deadline: '2026-09-15',
      isUrgent: true,
      location: 'Lagos and Abuja',
      status: 'active',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    {
      slug: 'orphans-education-support',
      title: 'Orphans Education Support Program',
      description: 'Sponsor the education of orphaned children. Your donation covers school fees, uniforms, books, and daily meals. Currently supporting 50 orphans across primary and secondary levels. For ₦50,000 per term, you can sponsor a child\'s complete education.',
      shortDescription: 'Sponsoring education for orphaned children.',
      category: 'orphans',
      goalAmount: 10000000,
      raisedAmount: 6200000,
      currency: 'NGN',
      beneficiaryCount: 50,
      imageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800'],
      deadline: '2026-12-31',
      isUrgent: false,
      location: 'Nationwide',
      status: 'active',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(3),
    },
    {
      slug: 'medical-aid-emergency',
      title: 'Emergency Medical Aid Fund',
      description: 'Provide emergency medical assistance to those who cannot afford critical healthcare. Covers surgeries, treatments, and medications. This fund responds to urgent cases referred by hospitals and community health workers.',
      shortDescription: 'Emergency medical assistance for those in critical need.',
      category: 'medical',
      goalAmount: 8000000,
      raisedAmount: 4150000,
      currency: 'NGN',
      beneficiaryCount: 25,
      imageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800',
      deadline: '2026-12-31',
      isUrgent: true,
      location: 'Nationwide',
      status: 'active',
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      slug: 'skills-training-women',
      title: 'Women\'s Skills Training Program',
      description: 'Empower women with vocational skills including tailoring, catering, and computer literacy. Each training cycle runs for 6 months and graduates 100 women with skills to start their own businesses. Includes starter kits upon graduation.',
      shortDescription: 'Vocational training for women to achieve financial independence.',
      category: 'education',
      goalAmount: 6000000,
      raisedAmount: 2840000,
      currency: 'NGN',
      beneficiaryCount: 100,
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
      deadline: '2026-12-31',
      isUrgent: false,
      location: 'Lagos',
      status: 'active',
      createdAt: daysAgo(40),
      updatedAt: daysAgo(5),
    },
    {
      slug: 'shelter-for-displaced',
      title: 'Shelter for Displaced Families',
      description: 'Provide temporary housing and essential supplies for families displaced by conflict or natural disasters. Each shelter unit costs ₦150,000 and houses a family for up to 6 months.',
      shortDescription: 'Housing support for displaced families.',
      category: 'shelter',
      goalAmount: 12000000,
      raisedAmount: 7800000,
      currency: 'NGN',
      beneficiaryCount: 52,
      imageUrl: 'https://images.unsplash.com/photo-1490511474501-2d3f1dbf2b92?w=800',
      deadline: '2026-12-31',
      isUrgent: true,
      location: 'Northern Nigeria',
      status: 'active',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(2),
    },
  ],

  charity_donations: [
    { campaignId: '', donorName: 'Muhammad Ali', donorEmail: 'muhammad.ali@example.com', donorPhone: '+2348061111111', amount: 100000, currency: 'NGN', category: 'zakaat', type: 'one-time', method: 'card', reference: 'CHR-DON-001', status: 'successful', isAnonymous: false, message: 'May Allah accept', donatedAt: daysAgo(1) },
    { campaignId: '', donorName: 'Anonymous', donorEmail: 'anon@example.com', amount: 50000, currency: 'NGN', category: 'sadaqah', type: 'one-time', method: 'bank_transfer', reference: 'CHR-DON-002', status: 'successful', isAnonymous: true, donatedAt: daysAgo(2) },
    { campaignId: '', donorName: 'Fatima Bello', donorEmail: 'fatima.bello@example.com', donorPhone: '+2348062222222', amount: 25000, currency: 'NGN', category: 'sadaqah', type: 'recurring', method: 'card', reference: 'CHR-DON-003', status: 'successful', isAnonymous: false, message: 'Monthly contribution', donatedAt: daysAgo(3) },
    { campaignId: '', donorName: 'Ibrahim Suleiman', donorEmail: 'ibrahim.s@example.com', donorPhone: '+2348063333333', amount: 200000, currency: 'NGN', category: 'zakaat', type: 'one-time', method: 'bank_transfer', reference: 'CHR-DON-004', status: 'successful', isAnonymous: false, donatedAt: daysAgo(4) },
    { campaignId: '', donorName: 'Anonymous', donorEmail: 'anon2@example.com', amount: 10000, currency: 'NGN', category: 'sadaqah', type: 'one-time', method: 'mobile_money', reference: 'CHR-DON-005', status: 'successful', isAnonymous: true, donatedAt: daysAgo(5) },
    { campaignId: '', donorName: 'Aisha Abdullahi', donorEmail: 'aisha.a@example.com', donorPhone: '+2348064444444', amount: 75000, currency: 'NGN', category: 'general', type: 'one-time', method: 'card', reference: 'CHR-DON-006', status: 'successful', isAnonymous: false, message: 'For the water project', donatedAt: daysAgo(6) },
    { campaignId: '', donorName: 'Abdullah Okafor', donorEmail: 'abdullah.o@example.com', donorPhone: '+2348065555555', amount: 150000, currency: 'NGN', category: 'zakaat', type: 'recurring', method: 'card', reference: 'CHR-DON-007', status: 'successful', isAnonymous: false, donatedAt: daysAgo(7) },
    { campaignId: '', donorName: 'Anonymous', donorEmail: 'anon3@example.com', amount: 5000, currency: 'NGN', category: 'sadaqah', type: 'one-time', method: 'bank_transfer', reference: 'CHR-DON-008', status: 'successful', isAnonymous: true, donatedAt: daysAgo(8) },
  ],

  charity_donors: [
    { email: 'muhammad.ali@example.com', name: 'Muhammad Ali', phone: '+2348061111111', totalDonated: 500000, donationCount: 8, firstDonationAt: daysAgo(200), lastDonationAt: daysAgo(1), isRecurring: false, tags: ['major-donor'], communicationOptIn: true },
    { email: 'fatima.bello@example.com', name: 'Fatima Bello', phone: '+2348062222222', totalDonated: 175000, donationCount: 7, firstDonationAt: daysAgo(150), lastDonationAt: daysAgo(3), isRecurring: true, tags: ['recurring'], communicationOptIn: true },
    { email: 'ibrahim.s@example.com', name: 'Ibrahim Suleiman', phone: '+2348063333333', totalDonated: 600000, donationCount: 4, firstDonationAt: daysAgo(100), lastDonationAt: daysAgo(4), isRecurring: false, tags: ['major-donor', 'zakaat'], communicationOptIn: true },
    { email: 'aisha.a@example.com', name: 'Aisha Abdullahi', phone: '+2348064444444', totalDonated: 225000, donationCount: 3, firstDonationAt: daysAgo(90), lastDonationAt: daysAgo(6), isRecurring: false, tags: [], communicationOptIn: true },
    { email: 'abdullah.o@example.com', name: 'Abdullah Okafor', phone: '+2348065555555', totalDonated: 450000, donationCount: 6, firstDonationAt: daysAgo(180), lastDonationAt: daysAgo(7), isRecurring: true, tags: ['major-donor', 'recurring'], communicationOptIn: true },
  ],

  charity_recurring_donations: [
    { donorEmail: 'fatima.bello@example.com', donorName: 'Fatima Bello', amount: 25000, currency: 'NGN', frequency: 'monthly', campaignId: '', category: 'sadaqah', nextChargeDate: daysAhead(25), status: 'active', startedAt: daysAgo(150), totalCharged: 175000 },
    { donorEmail: 'abdullah.o@example.com', donorName: 'Abdullah Okafor', amount: 150000, currency: 'NGN', frequency: 'monthly', campaignId: '', category: 'zakaat', nextChargeDate: daysAhead(20), status: 'active', startedAt: daysAgo(180), totalCharged: 450000 },
  ],

  charity_volunteers: [
    { name: 'Daud Mohammed', email: 'daud.m@example.com', phone: '+2348071111111', skills: ['First Aid', 'Driving', 'Logistics'], availability: 'weekends', preferredRole: 'field-worker', location: 'Lagos', bio: 'Experienced humanitarian worker with 5 years of field experience.', status: 'active', assignedRole: 'Field Coordinator', hoursLogged: 120, joinedAt: daysAgo(90) },
    { name: 'Maryam Aliyu', email: 'maryam.a@example.com', phone: '+2348072222222', skills: ['Teaching', 'Counseling', 'Social Media'], availability: 'flexible', preferredRole: 'educator', location: 'Lagos', bio: 'Teacher passionate about education access for all children.', status: 'active', assignedRole: 'Education Program Lead', hoursLogged: 85, joinedAt: daysAgo(60) },
    { name: 'Yusuf Bello', email: 'yusuf.b@example.com', phone: '+2348073333333', skills: ['Medical', 'First Aid', 'Nursing'], availability: 'weekdays', preferredRole: 'medical-worker', location: 'Abuja', bio: 'Registered nurse with emergency response experience.', status: 'active', assignedRole: 'Medical Volunteer', hoursLogged: 60, joinedAt: daysAgo(45) },
    { name: 'Khadijah Musa', email: 'khadijah.m@example.com', phone: '+2348074444444', skills: ['Counseling', 'Social Work', 'Languages'], availability: 'evenings', preferredRole: 'counselor', location: 'Lagos', bio: 'Social worker with experience in trauma counseling.', status: 'pending', joinedAt: daysAgo(7) },
    { name: 'Ibrahim Okafor', email: 'ibrahim.o@example.com', phone: '+2348075555555', skills: ['Photography', 'Videography', 'Content Creation'], availability: 'weekends', preferredRole: 'media', location: 'Lagos', bio: 'Media professional wanting to document impact stories.', status: 'active', assignedRole: 'Media Volunteer', hoursLogged: 40, joinedAt: daysAgo(30) },
  ],

  charity_volunteer_roles: [
    { title: 'Field Distribution Worker', description: 'Assist with the distribution of food, supplies, and materials to beneficiaries.', requirements: ['Physical fitness', 'Valid ID', 'Reliability'], location: 'Lagos', timeCommitment: 'Weekends, 4-6 hours', slotsAvailable: 10, slotsFilled: 6, status: 'open' },
    { title: 'Education Program Assistant', description: 'Support teaching and mentoring in our education programs for orphans and vulnerable children.', requirements: ['Teaching experience', 'Patience with children', 'Background check'], location: 'Lagos', timeCommitment: 'Saturdays, 3 hours', slotsAvailable: 5, slotsFilled: 3, status: 'open' },
    { title: 'Medical Volunteer', description: 'Provide basic medical care during outreach programs and emergency response.', requirements: ['Medical qualification', 'Current license', 'First aid certification'], location: 'Various', timeCommitment: 'As needed', slotsAvailable: 8, slotsFilled: 4, status: 'open' },
    { title: 'Social Media Volunteer', description: 'Create content for our social media platforms to raise awareness about our campaigns.', requirements: ['Social media experience', 'Content creation skills', 'Creativity'], location: 'Remote', timeCommitment: 'Flexible, 5 hours/week', slotsAvailable: 3, slotsFilled: 2, status: 'open' },
  ],

  charity_beneficiaries: [
    { name: 'Beneficiary 001', age: 35, gender: 'female', familySize: 6, location: 'Kano', category: 'widow', needsAssessment: 'Family of 6 needs food and education support for children. Husband passed away 2 years ago.', assistanceHistory: [{ type: 'food', date: daysAgo(30), value: 25000 }, { type: 'education', date: daysAgo(60), value: 50000 }], verificationStatus: 'verified', registeredAt: daysAgo(90) },
    { name: 'Beneficiary 002', age: 12, gender: 'male', familySize: 3, location: 'Lagos', category: 'orphan', needsAssessment: 'Orphaned child needs educational support and school supplies.', assistanceHistory: [{ type: 'education', date: daysAgo(45), value: 50000 }], verificationStatus: 'verified', registeredAt: daysAgo(60) },
    { name: 'Beneficiary 003', age: 68, gender: 'male', familySize: 2, location: 'Kaduna', category: 'elderly', needsAssessment: 'Elderly man with medical needs including hypertension medication.', assistanceHistory: [{ type: 'medical', date: daysAgo(15), value: 35000 }], verificationStatus: 'verified', registeredAt: daysAgo(45) },
    { name: 'Beneficiary 004', age: 28, gender: 'female', familySize: 4, location: 'Borno', category: 'displaced', needsAssessment: 'Displaced family needs shelter and basic supplies.', assistanceHistory: [{ type: 'shelter', date: daysAgo(20), value: 150000 }, { type: 'food', date: daysAgo(10), value: 25000 }], verificationStatus: 'verified', registeredAt: daysAgo(30) },
  ],

  charity_impact_metrics: [
    { metricKey: 'families_helped', metricLabel: 'Families Helped', value: 1250, unit: 'families', category: 'general', period: '2026', updatedAt: daysAgo(1) },
    { metricKey: 'meals_served', metricLabel: 'Meals Served', value: 45000, unit: 'meals', category: 'food', period: '2026', updatedAt: daysAgo(1) },
    { metricKey: 'water_wells_built', metricLabel: 'Water Wells Built', value: 12, unit: 'wells', category: 'water', period: '2026', updatedAt: daysAgo(7) },
    { metricKey: 'orphans_sponsored', metricLabel: 'Orphans Sponsored', value: 50, unit: 'children', category: 'orphans', period: '2026', updatedAt: daysAgo(3) },
    { metricKey: 'medical_cases', metricLabel: 'Medical Cases Assisted', value: 25, unit: 'cases', category: 'medical', period: '2026', updatedAt: daysAgo(5) },
    { metricKey: 'women_trained', metricLabel: 'Women Trained', value: 100, unit: 'women', category: 'education', period: '2026', updatedAt: daysAgo(10) },
    { metricKey: 'shelters_provided', metricLabel: 'Shelters Provided', value: 52, unit: 'shelters', category: 'shelter', period: '2026', updatedAt: daysAgo(2) },
    { metricKey: 'volunteers_active', metricLabel: 'Active Volunteers', value: 45, unit: 'volunteers', category: 'general', period: '2026', updatedAt: daysAgo(1) },
  ],

  charity_success_stories: [
    {
      slug: 'aisha-tailoring-business',
      title: 'Aisha\'s Journey to Financial Independence',
      summary: 'How our skills training program helped a widow start a successful tailoring business.',
      content: 'Aisha, a 32-year-old widow and mother of three, lost her husband in 2023. Without a source of income, she struggled to feed her family. When she joined our Women\'s Skills Training Program, she had never used a sewing machine.\n\nSix months later, Aisha graduated with tailoring skills and received a starter kit including a sewing machine, fabric, and basic tools. Today, she runs a successful tailoring business from her home, earning enough to support her family and send her children to school.\n\n"I never imagined I could do this," Aisha says. "The training gave me not just skills, but confidence. Now I can provide for my children without depending on anyone."\n\nAisha now mentors other women in her community and has even hired an assistant. Her story is a testament to the power of empowerment over charity.',
      beneficiaryName: 'Aisha (name changed for privacy)',
      location: 'Lagos, Nigeria',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800'],
      beforeImageUrl: '',
      afterImageUrl: '',
      metrics: { income_increase: '300%', children_in_school: 3, jobs_created: 1 },
      campaignId: '',
      status: 'published',
      publishedAt: daysAgo(15),
    },
    {
      slug: 'borehole-transforms-village',
      title: 'How a Borehole Transformed an Entire Village',
      summary: 'A single water project brought health, education, and economic opportunities to 500 villagers.',
      content: 'The village of Kofar Gabas in Northern Nigeria had no access to clean water. Women and children walked 5 kilometers daily to fetch water from a contaminated river. Waterborne diseases were rampant, and children missed school due to illness.\n\nWhen Minhaajulhudaa Charity Foundation built a borehole in the village, everything changed. Within three months:\n\n- Waterborne diseases dropped by 80%\n- School attendance increased by 45%\n- Women gained 3 hours daily previously spent fetching water\n- A community garden was started using the water supply\n\n"We used to bury our children because of water diseases," says Malam Yusuf, the village head. "Now, our children are healthy and in school. The borehole gave us life."\n\nThis project, funded by donors like you, cost ₦2.5 million but transformed 500 lives. We plan to build 10 more boreholes in similar communities this year.',
      beneficiaryName: 'Village of Kofar Gabas',
      location: 'Northern Nigeria',
      imageUrl: 'https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=800'],
      metrics: { beneficiaries: 500, disease_reduction: '80%', school_attendance_increase: '45%' },
      campaignId: '',
      status: 'published',
      publishedAt: daysAgo(30),
    },
    {
      slug: 'orphan-graduates-top-class',
      title: 'Sponsored Orphan Graduates Top of His Class',
      summary: 'Ahmed, sponsored through our education program, graduates with the highest scores in his school.',
      content: 'Ahmed was 8 years old when he lost his father. His mother, a petty trader, could not afford his school fees. When Minhaajulhudaa Charity Foundation stepped in through the Orphans Education Support Program, Ahmed was given a second chance.\n\nFor three years, we sponsored Ahmed\'s education, providing school fees, uniforms, books, and daily meals. This year, Ahmed graduated from primary school with the highest scores in his entire school.\n\n"I want to become a doctor so I can help people like my father," Ahmed says with a bright smile. "Thank you for giving me the chance to dream."\n\nAhmed\'s story shows how education sponsorship can break the cycle of poverty and create future leaders. With your continued support, we can help more children like Ahmed reach their full potential.',
      beneficiaryName: 'Ahmed (name changed for privacy)',
      location: 'Lagos, Nigeria',
      imageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
      metrics: { years_sponsored: 3, class_rank: 1, graduation_year: 2026 },
      campaignId: '',
      status: 'published',
      publishedAt: daysAgo(20),
    },
  ],

  charity_testimonials: [
    { authorName: 'Dr. Muhammad Ali', authorRole: 'Donor since 2022', authorAvatarUrl: '', content: 'I have been donating to Minhaajulhudaa Charity for over two years. Their transparency and impact are remarkable. I visited one of their water projects and saw firsthand how donations are changing lives. I highly recommend supporting their work.', rating: 5, isDonor: true, isBeneficiary: false, isPartner: false, status: 'approved', createdAt: daysAgo(5) },
    { authorName: 'Malama Fatima', authorRole: 'Beneficiary', authorAvatarUrl: '', content: 'When my husband passed away, I did not know how to feed my children. Minhaajulhudaa Charity provided food, and later enrolled me in their skills training. Today I have my own business. May Allah reward them abundantly.', rating: 5, isDonor: false, isBeneficiary: true, isPartner: false, status: 'approved', createdAt: daysAgo(10) },
    { authorName: 'Alhaji Ibrahim Suleiman', authorRole: 'Corporate Partner', authorAvatarUrl: '', content: 'Our company has partnered with Minhaajulhudaa Charity for our CSR initiatives. Their professionalism and impact measurement are excellent. They provide detailed reports and are always accountable. A trustworthy organization.', rating: 5, isDonor: false, isBeneficiary: false, isPartner: true, status: 'approved', createdAt: daysAgo(15) },
  ],

  charity_blog_posts: [
    {
      slug: 'the-importance-of-sadaqah',
      title: 'The Importance of Sadaqah in Islam',
      excerpt: 'Understanding the spiritual and social benefits of giving charity in Islam.',
      content: 'Sadaqah, derived from the Arabic word "Sidq" (truth), signifies truthful faith through charitable giving. It is a voluntary act of worship that purifies wealth and soul.\n\n## Types of Sadaqah\n1. Sadaqah Wajibah (obligatory) - includes Sadaqat al-Fitr\n2. Sadaqah Mustahabb (voluntary) - any good deed\n3. Sadaqah Jariyah (perpetual) - ongoing charity like building a well\n\n## Benefits of Sadaqah\n- Increases blessings in wealth\n- Protects from calamities\n- Purifies the soul\n- Strengthens community bonds\n- Earns continuous rewards\n\nThe Prophet (PBUH) said: "Charity does not decrease wealth."\n\nAt Minhaajulhudaa Charity, we facilitate various forms of Sadaqah, ensuring your contributions reach those who need them most. Visit our campaigns page to find a cause that resonates with you.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800',
      category: 'education',
      tags: ['sadaqah', 'charity', 'islam'],
      authorName: 'Malik Ibrahim Suleiman',
      status: 'published',
      publishedAt: daysAgo(7),
      views: 234,
    },
    {
      slug: 'volunteer-spotlight-daud',
      title: 'Volunteer Spotlight: Daud Mohammed',
      excerpt: 'Meet one of our dedicated volunteers who has been serving for over 90 days.',
      content: 'Daud Mohammed joined Minhaajulhudaa Charity as a volunteer 90 days ago, and in that time, he has logged over 120 hours of service. As our Field Coordinator, Daud leads distribution efforts and ensures that aid reaches beneficiaries efficiently.\n\n"I started volunteering because I wanted to give back to my community," Daud says. "What I did not expect was how much I would gain in return - the smiles, the gratitude, the sense of purpose."\n\nDaud\'s dedication exemplifies the spirit of service that drives our organization. He is always the first to arrive and the last to leave during distribution events.\n\nIf you are inspired by Daud\'s story and want to make a difference, visit our volunteer page to see available opportunities.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800',
      category: 'volunteers',
      tags: ['volunteer', 'spotlight'],
      authorName: 'Malik Ibrahim Suleiman',
      status: 'published',
      publishedAt: daysAgo(12),
      views: 156,
    },
    {
      slug: 'annual-impact-report-2025',
      title: 'Annual Impact Report 2025',
      excerpt: 'A comprehensive review of our achievements and impact in 2025.',
      content: 'Alhamdulillah, 2025 was a year of significant growth and impact for Minhaajulhudaa Charity Foundation. Here are our key achievements:\n\n## Beneficiaries Reached\n- 1,250 families supported\n- 45,000 meals served\n- 50 orphans sponsored\n- 12 water wells built\n- 25 medical cases assisted\n- 100 women trained\n\n## Financial Summary\n- Total raised: ₦45,000,000\n- Total disbursed: ₦42,300,000\n- Administrative costs: 6%\n\n## Key Projects Completed\n- Kofar Gabas Borehole Project\n- Ramadan Food Distribution\n- Women\'s Skills Training - Cohort 1\n- Orphan Education Support\n\n## Looking Ahead\nIn 2026, we plan to:\n- Build 10 more water wells\n- Sponsor 100 more orphans\n- Train 200 more women\n- Expand to 3 new states\n\nWe thank all our donors, volunteers, and partners for making this possible. Together, we are changing lives.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b42?w=800',
      category: 'reports',
      tags: ['report', 'impact', '2025'],
      authorName: 'Malik Ibrahim Suleiman',
      status: 'published',
      publishedAt: daysAgo(30),
      views: 489,
    },
  ],

  charity_faq: [
    { question: 'Is my donation tax-deductible?', answer: 'Yes, Minhaajulhudaa Charity Foundation is a registered non-profit organization. All donations are tax-deductible. We provide official receipts for all donations.', category: 'donations', order: 1, status: 'active' },
    { question: 'How can I be sure my donation reaches the intended beneficiaries?', answer: 'We maintain full transparency. All our campaigns have progress tracking, and we publish quarterly reports showing how funds were used. Donors can also request specific reports for their contributions.', category: 'donations', order: 2, status: 'active' },
    { question: 'Can I donate to a specific campaign?', answer: 'Yes, you can choose to donate to any of our active campaigns. Simply select the campaign on our donations page and proceed with your contribution.', category: 'donations', order: 3, status: 'active' },
    { question: 'What payment methods do you accept?', answer: 'We accept bank transfers, card payments, and mobile money. For large donations, please contact us directly for personalized assistance.', category: 'donations', order: 4, status: 'active' },
    { question: 'How can I become a volunteer?', answer: 'Visit our How to Help page and fill out the volunteer registration form. Our team will review your application and contact you within 5 business days with available opportunities.', category: 'volunteering', order: 1, status: 'active' },
    { question: 'What skills are you looking for in volunteers?', answer: 'We welcome volunteers with various skills including teaching, medical, logistics, media, counseling, and more. Even if you do not have specialized skills, there are opportunities to help with distribution and events.', category: 'volunteering', order: 2, status: 'active' },
    { question: 'Can I sponsor an orphan long-term?', answer: 'Yes, we offer an orphan sponsorship program where you can sponsor a child\'s education for ₦50,000 per term. This covers school fees, uniforms, books, and daily meals. Contact us for more details.', category: 'programs', order: 1, status: 'active' },
    { question: 'How do you verify beneficiaries?', answer: 'We have a thorough verification process that includes community referrals, home visits, and documentation. Our team works with local leaders and social workers to ensure aid reaches those genuinely in need.', category: 'programs', order: 2, status: 'active' },
  ],

  charity_partners: [
    { name: 'Islamic Relief Nigeria', type: 'ngo', logoUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=400', websiteUrl: 'https://www.islamic-relief.org', description: 'International humanitarian organization partnering on emergency response.', contributionValue: 5000000, partnershipStart: '2023-01-15', status: 'active' },
    { name: 'Lagos State Government', type: 'government', logoUrl: '', websiteUrl: 'https://lagosstate.gov.ng', description: 'Government partner providing regulatory support and access to communities.', contributionValue: 0, partnershipStart: '2022-06-01', status: 'active' },
    { name: 'Dangote Foundation', type: 'corporate', logoUrl: '', websiteUrl: '', description: 'Corporate partner supporting our food security programs.', contributionValue: 10000000, partnershipStart: '2023-03-01', status: 'active' },
    { name: 'Al-Noor Foundation', type: 'ngo', logoUrl: '', websiteUrl: '', description: 'Partner for educational programs and orphan support.', contributionValue: 2000000, partnershipStart: '2024-01-01', status: 'active' },
  ],

  charity_products: [
    { slug: 'charity-tshirt-2026', name: 'Minhaajulhudaa Charity T-Shirt', description: 'Official charity t-shirt. All proceeds support our campaigns.', price: 5000, category: 'apparel', images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'], stock: 100, sku: 'CHR-TS-001', status: 'active' },
    { slug: 'charity-mug', name: 'Charity Supporter Mug', description: 'Show your support with our branded mug. Proceeds fund clean water projects.', price: 2500, category: 'merchandise', images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800'], stock: 75, sku: 'CHR-MG-001', status: 'active' },
    { slug: 'charity-tote-bag', name: 'Reusable Tote Bag', description: 'Eco-friendly tote bag. Proceeds support environmental and community programs.', price: 2000, category: 'merchandise', images: ['https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=800'], stock: 50, sku: 'CHR-TB-001', status: 'active' },
  ],

  charity_reports: [
    { title: 'Annual Impact Report 2025', type: 'annual', period: '2025', summary: 'Comprehensive review of achievements, financial summary, and impact metrics for 2025.', fileUrl: 'https://minhaajulhudaa.com/files/report.pdf', data: { totalRaised: 45000000, totalDisbursed: 42300000, beneficiaries: 1250 }, generatedAt: daysAgo(30) },
    { title: 'Q2 2026 Financial Report', type: 'financial', period: 'Q2 2026', summary: 'Financial breakdown for the second quarter of 2026.', fileUrl: 'https://minhaajulhudaa.com/files/report.pdf', data: { income: 15000000, expenses: 13200000, campaigns: 6 }, generatedAt: daysAgo(10) },
    { title: 'Water Project Impact Report', type: 'impact', period: '2025-2026', summary: 'Detailed report on water well projects, beneficiaries, and outcomes.', fileUrl: 'https://minhaajulhudaa.com/files/report.pdf', data: { wellsBuilt: 12, beneficiaries: 6000 }, generatedAt: daysAgo(7) },
  ],
};
