/**
 * School platform seed data - Minhaajulhudaa Islamic & Arabic School.
 * Islamic and Arabic Studies ONLY (no secular education).
 * Classes: Tamheedy, Ibtidaiyah 1-3, Idadiyah 1-3, Thanawiyyah 1-3 (10 classes total).
 */
const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d) => new Date(now.getTime() + d * 86400000).toISOString();
const today = now.toISOString().split('T')[0];

export const schoolSeedData = {
  school_pages: [
    {
      slug: 'about',
      title: 'About Minhaajulhudaa Islamic & Arabic School',
      content: [
        { type: 'hero', title: 'About Us', subtitle: 'Nurturing minds with Islamic knowledge and Arabic excellence' },
        { type: 'text', body: 'Minhaajulhudaa Islamic & Arabic School was established in 1444 AH (2021 CE) with a vision to provide authentic Islamic education and Arabic language mastery. Our curriculum is purely Islamic and Arabic studies, covering from foundational Tahdheeb to advanced Thanawiyyah level. We do not offer secular education - our focus is entirely on producing scholars of the Qur\'an, Hadith, Fiqh, and Arabic language.' },
        { type: 'text', body: 'Our school follows the traditional Madrasah system adapted for modern times, with structured progression from Tamheedy (Preparatory) through Ibtidaiyah (Elementary), Idadiyah (Intermediate), to Thanawiyyah (Secondary) levels. Each level builds upon the previous, ensuring a comprehensive understanding of Islamic sciences.' },
      ],
      seoTitle: 'About Minhaajulhudaa Islamic & Arabic School',
      seoDescription: 'Authentic Islamic and Arabic education from Tamheedy to Thanawiyyah level.',
      status: 'published',
      publishedAt: daysAgo(30),
      order: 1,
    },
    {
      slug: 'contact',
      title: 'Contact Us',
      content: [
        { type: 'hero', title: 'Get in Touch', subtitle: 'We are here to serve the Ummah' },
        { type: 'text', body: 'Reach out to us for admissions, inquiries, or to schedule a visit to our school.' },
      ],
      seoTitle: 'Contact Minhaajulhudaa Islamic & Arabic School',
      seoDescription: 'Contact information for Minhaajulhudaa School.',
      status: 'published',
      publishedAt: daysAgo(30),
      order: 2,
    },
  ],

  school_blog_posts: [
    {
      slug: 'welcome-to-new-academic-year-1447ah',
      title: 'Welcome to the 1447 AH Academic Year',
      excerpt: 'As we begin a new Hijri academic year, we reflect on our achievements in Islamic education and set new goals for excellence in Arabic and Qur\'anic studies.',
      content: 'Bismillah. As we welcome students back for the 1447 AH academic year, we are filled with gratitude to Allah. Last year, 15 students completed their Hifz of the entire Qur\'an, and 20 students achieved mastery in Arabic grammar (Nahwu and Sarf).\n\nThis year, we are introducing an enhanced Tajweed program with certified Qaris, expanding our Hadith collection in the library, and adding advanced Fiqh studies for our Thanawiyyah students. Our new Tahfeez ul-Qur\'an wing is fully operational.\n\nWe invite parents to join us for the orientation session where we will share detailed plans for the year ahead. Together, we will continue to nurture the next generation of Islamic scholars.',
      featuredImageUrl: '/images/patterns/quran.svg',
      category: 'announcements',
      tags: ['academic-year', 'welcome', '1447ah'],
      authorName: 'Ustadh Abdurrahman Adeyemi',
      status: 'published',
      publishedAt: daysAgo(7),
      readingTimeMinutes: 3,
      views: 245,
    },
    {
      slug: 'hifz-graduation-1447ah',
      title: '15 Students Complete Qur\'an Memorization',
      excerpt: 'Our Hifz program celebrates another milestone as 15 students complete their memorization of the entire Qur\'an with Ijazah.',
      content: 'Alhamdulillah, we are proud to announce that 15 of our students have successfully completed the memorization of the entire Qur\'an with proper Tajweed. This achievement is the result of years of dedicated effort by both students and teachers.\n\nThe graduation ceremony was held in the school mosque, with parents, community members, and visiting scholars in attendance. Each graduate received an Ijazah certificate, linking them to the chain of Qur\'an reciters going back to the Prophet (peace be upon him).\n\nWe ask Allah to make these students a source of benefit for the Ummah and to increase them in knowledge and piety.',
      featuredImageUrl: '/images/patterns/quran.svg',
      category: 'achievements',
      tags: ['hifz', 'graduation', 'quran'],
      authorName: 'Ustadh Yusuf Olatunji',
      status: 'published',
      publishedAt: daysAgo(14),
      readingTimeMinutes: 2,
      views: 312,
    },
    {
      slug: 'arabic-language-immersion-success',
      title: 'Arabic Language Immersion: A Year of Progress',
      excerpt: 'Our Arabic immersion program has shown remarkable results, with students achieving fluency in classical Arabic.',
      content: 'This year, our Arabic Language Immersion program has achieved outstanding results. Students in the Idadiyah level can now read and understand classical Arabic texts, including works of Fiqh, Tafsir, and Hadith commentary.\n\nOur approach combines traditional grammar instruction (Nahwu and Sarf) with conversational practice, literature reading, and composition. Students participate in weekly Arabic-only discussion circles and monthly Arabic poetry competitions.\n\nWe attribute this success to our dedicated teachers, many of whom are graduates of Al-Azhar University and the Islamic University of Madinah.',
      featuredImageUrl: '/images/patterns/books.svg',
      category: 'academic',
      tags: ['arabic', 'language', 'immersion'],
      authorName: 'Mrs. Khadijah Suleiman',
      status: 'published',
      publishedAt: daysAgo(21),
      readingTimeMinutes: 4,
      views: 189,
    },
    {
      slug: 'hadith-memorization-program-launch',
      title: 'New Hadith Memorization Program Launched',
      excerpt: 'We are excited to announce our new Hadith memorization program, focusing on the Forty Hadith of Imam Nawawi.',
      content: 'Bismillah. We are pleased to announce the launch of our Hadith memorization program, beginning with the Forty Hadith of Imam Nawawi (Rahimahullah). This collection is considered essential for every Muslim student of knowledge.\n\nThe program is open to all Idadiyah and Thanawiyyah students. Each week, students will memorize one hadith with its chain of narrators, meaning, and key lessons. Monthly assessments will ensure proper retention.\n\nThis program complements our existing Qur\'an memorization curriculum and helps students develop a comprehensive understanding of Islamic texts.',
      featuredImageUrl: '/images/patterns/books.svg',
      category: 'programs',
      tags: ['hadith', 'memorization', 'nawawi'],
      authorName: 'Ustadh Abdurrahman Adeyemi',
      status: 'published',
      publishedAt: daysAgo(28),
      readingTimeMinutes: 2,
      views: 156,
    },
    {
      slug: 'understanding-tajweed-rules',
      title: 'Understanding Tajweed: The Science of Qur\'an Recitation',
      excerpt: 'A comprehensive guide to the importance of Tajweed and how we teach it at our school.',
      content: 'Tajweed is the science of reciting the Qur\'an as it was revealed to the Prophet Muhammad (peace be upon him). The word Tajweed comes from the Arabic root j-w-d, meaning "to make well" or "to improve."\n\nAt Minhaajulhudaa, we begin Tajweed instruction from the Tamheedy level, teaching children the correct pronunciation of Arabic letters (Makharij) and the basic rules of Noon Sakinah and Tanween.\n\nBy the Ibtidaiyah level, students learn the rules of Madd (elongation), Ghunnah (nasalization), and the categories of Tafkheem and Tarqeeq. In Idadiyah and Thanawiyyah, students study advanced Tajweed including the rules of Waqf (stopping) and the different Qira\'at (recitations).\n\nOur Tajweed teachers hold Ijazah in the Hafs recitation, and we are working toward offering instruction in the other canonical recitations as well.',
      featuredImageUrl: '/images/patterns/quran.svg',
      category: 'education',
      tags: ['tajweed', 'quran', 'recitation'],
      authorName: 'Ustadh Yusuf Olatunji',
      status: 'published',
      publishedAt: daysAgo(35),
      readingTimeMinutes: 5,
      views: 278,
    },
  ],

  school_programs: [
    {
      slug: 'hifz-program',
      title: 'Hifz (Qur\'an Memorization) Program',
      category: 'quran',
      description: 'A structured program for memorizing the entire Qur\'an with proper Tajweed. Students progress through daily memorization targets, regular revision (Muraja\'ah), and monthly assessments. The program is integrated with our regular Islamic studies curriculum.',
      curriculum: 'The program follows a progressive memorization schedule: 2-3 pages daily for beginners, increasing as proficiency grows. Daily revision (Muraja\'ah) of previously memorized portions. Weekly assessment with the lead Hifz teacher. Monthly evaluation with external examiners. Annual certification upon completion.',
      duration: '3-5 years',
      requirements: ['Age 7+', 'Basic Qur\'an reading ability', 'Commitment from student and parents', 'Passing admission assessment'],
      outcomes: ['Ijazah in Qur\'an recitation', 'Certificate of Hifz completion', 'Strong foundation in Tajweed', 'Enhanced memory and discipline'],
      imageUrl: '/images/patterns/quran.svg',
      instructor: 'Ustadh Yusuf Olatunji',
      fee: 50000,
      status: 'open',
    },
    {
      slug: 'arabic-immersion',
      title: 'Arabic Language Immersion Program',
      category: 'arabic',
      description: 'A comprehensive Arabic language program covering Nahwu (grammar), Sarf (morphology), Balaghah (rhetoric), and Adab (literature). Students develop fluency in reading, writing, and speaking classical Arabic.',
      curriculum: 'Foundation: Arabic alphabet, basic reading and writing, simple sentences. Intermediate: Nahwu rules, Sarf patterns, reading short texts. Advanced: Classical Arabic literature, Tafsir texts, Hadith commentary, composition and debate.',
      duration: '6-9 years (across all levels)',
      requirements: ['Age 5+', 'No prior Arabic knowledge required for entry level', 'Commitment to daily practice'],
      outcomes: ['Fluency in classical Arabic', 'Ability to read Islamic texts independently', 'Certificate in Arabic Language', 'Preparation for advanced Islamic studies'],
      imageUrl: '/images/patterns/books.svg',
      instructor: 'Mrs. Khadijah Suleiman',
      fee: 40000,
      status: 'open',
    },
    {
      slug: 'tajweed-program',
      title: 'Tajweed and Qira\'at Program',
      category: 'quran',
      description: 'Specialized program focusing on the science of Tajweed - the proper recitation of the Qur\'an. Covers Makharij (articulation points), Sifat (characteristics of letters), and the rules of recitation.',
      curriculum: 'Level 1: Makharij and basic Sifat. Level 2: Rules of Noon Sakinah, Tanween, and Meem Sakinah. Level 3: Rules of Madd and its categories. Level 4: Advanced Tajweed and introduction to Qira\'at.',
      duration: '2-3 years',
      requirements: ['Age 6+', 'Basic Qur\'an reading ability', 'Passing Tajweed assessment'],
      outcomes: ['Mastery of Tajweed rules', 'Beautiful and correct Qur\'an recitation', 'Preparation for Ijazah certification'],
      imageUrl: '/images/patterns/quran.svg',
      instructor: 'Ustadh Yusuf Olatunji',
      fee: 30000,
      status: 'open',
    },
    {
      slug: 'fiqh-studies',
      title: 'Fiqh (Islamic Jurisprudence) Program',
      category: 'islamic-studies',
      description: 'Comprehensive study of Islamic jurisprudence covering the rulings of Taharah (purification), Salah (prayer), Zakah, Sawm (fasting), and Hajj, based on the primary sources of Qur\'an and Sunnah.',
      curriculum: 'Level 1: Taharah and Salah. Level 2: Zakah and Sawm. Level 3: Hajj and Umrah. Level 4: Mu\'amalat (transactions) and family law. Based on the Maliki school with comparison to other schools.',
      duration: '4-6 years',
      requirements: ['Completion of Ibtidaiyah level', 'Basic Arabic reading ability', 'Understanding of basic Islamic concepts'],
      outcomes: ['Comprehensive understanding of Islamic rulings', 'Ability to apply Fiqh in daily life', 'Certificate in Islamic Jurisprudence'],
      imageUrl: '/images/patterns/arabesque.svg',
      instructor: 'Ustadh Abdurrahman Adeyemi',
      fee: 35000,
      status: 'open',
    },
  ],

  school_classes: [
    {
      slug: 'tamheedy',
      name: 'Tamheedy (Preparatory)',
      level: 'tamheedy',
      grade: 'T',
      teacherId: 'MHS-STAFF/004',
      teacherName: 'Mrs. Aisha Abdullahi',
      room: 'Room 101',
      capacity: 25,
      currentEnrollment: 22,
      subjects: ['Qur\'an Reading', 'Arabic Alphabet', 'Basic Tajweed', 'Islamic Etiquette (Adab)', 'Memorization (Short Surahs)'],
      schedule: 'Mon-Fri, 8:00 AM - 1:00 PM',
      description: 'The Tamheedy class is the foundational level for young learners aged 5-6. Students learn the Arabic alphabet, basic Qur\'an reading, short Surahs from Juz Amma, and essential Islamic manners. This class prepares children for the structured Ibtidaiyah curriculum.',
      active: true,
    },
    {
      slug: 'ibtidaiyah-1',
      name: 'Ibtidaiyah 1 (Elementary 1)',
      level: 'ibtidaiyah',
      grade: 'I1',
      teacherId: 'MHS-STAFF/005',
      teacherName: 'Mrs. Khadijah Suleiman',
      room: 'Room 102',
      capacity: 30,
      currentEnrollment: 28,
      subjects: ['Qur\'an Reading', 'Arabic Grammar (Nahwu)', 'Arabic Morphology (Sarf)', 'Tajweed Basics', 'Tahdheeb', 'Memorization (Juz Amma)'],
      schedule: 'Mon-Fri, 8:00 AM - 2:00 PM',
      description: 'Ibtidaiyah 1 is the first year of elementary Islamic education. Students begin structured Arabic grammar (Nahwu), morphology (Sarf), and Tajweed rules. They continue memorizing Juz Amma and learn Islamic etiquette (Tahdheeb).',
      active: true,
    },
    {
      slug: 'ibtidaiyah-2',
      name: 'Ibtidaiyah 2 (Elementary 2)',
      level: 'ibtidaiyah',
      grade: 'I2',
      teacherId: 'MHS-STAFF/010',
      teacherName: 'Ustadh Yahya Garba',
      room: 'Room 103',
      capacity: 30,
      currentEnrollment: 25,
      subjects: ['Qur\'an Reading', 'Arabic Grammar (Nahwu)', 'Arabic Morphology (Sarf)', 'Tajweed', 'Tahdheeb', 'Memorization', 'Hadith Studies'],
      schedule: 'Mon-Fri, 8:00 AM - 2:00 PM',
      description: 'Ibtidaiyah 2 builds on the foundation of Ibtidaiyah 1, with more advanced Arabic grammar, continued Qur\'an memorization, and introduction to Hadith studies. Students begin reading short Hadith texts in Arabic.',
      active: true,
    },
    {
      slug: 'ibtidaiyah-3',
      name: 'Ibtidaiyah 3 (Elementary 3)',
      level: 'ibtidaiyah',
      grade: 'I3',
      teacherId: 'MHS-STAFF/002',
      teacherName: 'Ustadh Yusuf Olatunji',
      room: 'Room 104',
      capacity: 30,
      currentEnrollment: 26,
      subjects: ['Qur\'an Reading', 'Advanced Arabic Grammar', 'Arabic Morphology', 'Tajweed', 'Tahdheeb', 'Memorization', 'Hadith Studies', 'Seerah (Prophetic Biography)'],
      schedule: 'Mon-Fri, 8:00 AM - 2:30 PM',
      description: 'Ibtidaiyah 3 completes the elementary level. Students achieve fluency in reading Arabic, master basic Tajweed, and are introduced to the Seerah (biography of the Prophet Muhammad, peace be upon him). This class prepares students for the intermediate Idadiyah level.',
      active: true,
    },
    {
      slug: 'idadiyah-1',
      name: 'Idadiyah 1 (Intermediate 1)',
      level: 'idadiyah',
      grade: 'D1',
      teacherId: 'MHS-STAFF/003',
      teacherName: 'Ustadh Muhammad Bashir',
      room: 'Room 201',
      capacity: 35,
      currentEnrollment: 30,
      subjects: ['Qur\'an with Tajweed', 'Advanced Nahwu', 'Advanced Sarf', 'Balaghah (Rhetoric) Introduction', 'Tafsir Introduction', 'Fiqh (Taharah & Salah)', 'Hadith Studies'],
      schedule: 'Mon-Fri, 7:30 AM - 3:00 PM',
      description: 'Idadiyah 1 begins the intermediate level. Students study advanced Arabic grammar and are introduced to Balaghah (rhetoric), Tafsir (Qur\'an exegesis), and Fiqh (Islamic jurisprudence) covering Taharah (purification) and Salah (prayer).',
      active: true,
    },
    {
      slug: 'idadiyah-2',
      name: 'Idadiyah 2 (Intermediate 2)',
      level: 'idadiyah',
      grade: 'D2',
      teacherId: 'MHS-STAFF/006',
      teacherName: 'Ustadh Ibrahim Musa',
      room: 'Room 202',
      capacity: 35,
      currentEnrollment: 28,
      subjects: ['Qur\'an with Tajweed', 'Advanced Nahwu', 'Advanced Sarf', 'Balaghah', 'Tafsir', 'Fiqh (Zakah & Sawm)', 'Hadith Studies', 'Usul al-Fiqh Introduction'],
      schedule: 'Mon-Fri, 7:30 AM - 3:00 PM',
      description: 'Idadiyah 2 continues intermediate studies with more advanced Balaghah, Tafsir of selected Surahs, and Fiqh covering Zakah and Sawm (fasting). Students are introduced to Usul al-Fiqh (principles of Islamic jurisprudence).',
      active: true,
    },
    {
      slug: 'idadiyah-3',
      name: 'Idadiyah 3 (Intermediate 3)',
      level: 'idadiyah',
      grade: 'D3',
      teacherId: 'MHS-STAFF/009',
      teacherName: 'Mrs. Maryam Disu',
      room: 'Room 203',
      capacity: 35,
      currentEnrollment: 25,
      subjects: ['Qur\'an with Tajweed', 'Arabic Literature', 'Balaghah', 'Tafsir', 'Fiqh (Hajj & Umrah)', 'Hadith Studies', 'Usul al-Fiqh', 'Aqeedah (Islamic Creed)'],
      schedule: 'Mon-Fri, 7:30 AM - 3:00 PM',
      description: 'Idadiyah 3 completes the intermediate level. Students study Arabic literature, advanced Tafsir, Fiqh of Hajj and Umrah, and are introduced to Aqeedah (Islamic creed). This class prepares students for the advanced Thanawiyyah level.',
      active: true,
    },
    {
      slug: 'thanawiyyah-1',
      name: 'Thanawiyyah 1 (Secondary 1)',
      level: 'thanawiyyah',
      grade: 'T1',
      teacherId: 'MHS-STAFF/003',
      teacherName: 'Ustadh Muhammad Bashir',
      room: 'Room 301',
      capacity: 30,
      currentEnrollment: 24,
      subjects: ['Advanced Tafsir', 'Advanced Fiqh', 'Usul al-Fiqh', 'Usul al-Hadith', 'Aqeedah', 'Arabic Literature', 'Mustalah al-Hadith', 'Comparative Religion'],
      schedule: 'Mon-Fri, 7:30 AM - 3:30 PM',
      description: 'Thanawiyyah 1 begins the secondary level with advanced Islamic sciences. Students study Usul al-Fiqh (principles of jurisprudence), Usul al-Hadith (principles of Hadith), Mustalah al-Hadith (Hadith terminology), and comparative religion.',
      active: true,
    },
    {
      slug: 'thanawiyyah-2',
      name: 'Thanawiyyah 2 (Secondary 2)',
      level: 'thanawiyyah',
      grade: 'T2',
      teacherId: 'MHS-STAFF/006',
      teacherName: 'Ustadh Ibrahim Musa',
      room: 'Room 302',
      capacity: 30,
      currentEnrollment: 22,
      subjects: ['Advanced Tafsir', 'Advanced Fiqh', 'Usul al-Fiqh', 'Ilm al-Kalam', 'Aqeedah', 'Arabic Literature', 'Siyaq al-Fiqh', 'Research Methods'],
      schedule: 'Mon-Fri, 7:30 AM - 3:30 PM',
      description: 'Thanawiyyah 2 continues with advanced studies including Ilm al-Kalam (theology), Siyaq al-Fiqh (contextual jurisprudence), and research methods in Islamic sciences. Students begin preparing their graduation research.',
      active: true,
    },
    {
      slug: 'thanawiyyah-3',
      name: 'Thanawiyyah 3 (Secondary 3 - Final Year)',
      level: 'thanawiyyah',
      grade: 'T3',
      teacherId: 'MHS-STAFF/009',
      teacherName: 'Mrs. Maryam Disu',
      room: 'Room 303',
      capacity: 30,
      currentEnrollment: 20,
      subjects: ['Advanced Tafsir', 'Advanced Fiqh', 'Ifta (Issuing Rulings)', 'Research Project', 'Comprehensive Review', 'Teaching Practice'],
      schedule: 'Mon-Fri, 7:30 AM - 3:30 PM',
      description: 'Thanawiyyah 3 is the final year. Students study Ifta (the science of issuing Islamic rulings), complete a graduation research project, and participate in teaching practice. Upon completion, students receive the Shahadah Thanawiyyah (Secondary Certificate) qualifying them as Islamic educators.',
      active: true,
    },
  ],

  school_courses: [
    {
      slug: 'introduction-to-nahwu',
      title: 'Introduction to Nahwu (Arabic Grammar)',
      category: 'arabic',
      description: 'A foundational course in Arabic grammar covering the basic rules of sentence structure, noun cases (I\'rab), and verb conjugation.',
      thumbnailUrl: '/images/patterns/books.svg',
      instructorName: 'Mrs. Khadijah Suleiman',
      duration: '12 weeks',
      level: 'beginner',
      price: 15000,
      isFree: false,
      status: 'published',
      lessons: [],
    },
    {
      slug: 'tajweed-rules-comprehensive',
      title: 'Comprehensive Tajweed Rules',
      category: 'quran',
      description: 'A complete course on Tajweed covering all major rules including Makharij, Sifat, Noon Sakinah, Madd, and Waqf.',
      thumbnailUrl: '/images/patterns/quran.svg',
      instructorName: 'Ustadh Yusuf Olatunji',
      duration: '16 weeks',
      level: 'intermediate',
      price: 20000,
      isFree: false,
      status: 'published',
      lessons: [],
    },
    {
      slug: 'fiqh-of-salah',
      title: 'Fiqh of Salah (Prayer)',
      category: 'islamic-studies',
      description: 'Detailed study of the rulings of Salah including conditions, pillars, obligations, and nullifiers of prayer.',
      thumbnailUrl: '/images/patterns/arabesque.svg',
      instructorName: 'Ustadh Abdurrahman Adeyemi',
      duration: '8 weeks',
      level: 'beginner',
      price: 10000,
      isFree: false,
      status: 'published',
      lessons: [],
    },
    {
      slug: 'seerah-of-the-prophet',
      title: 'Seerah: Life of the Prophet Muhammad (PBUH)',
      category: 'islamic-studies',
      description: 'A comprehensive study of the biography of the Prophet Muhammad (peace be upon him) from birth to passing.',
      thumbnailUrl: '/images/patterns/arabesque.svg',
      instructorName: 'Ustadh Abdurrahman Adeyemi',
      duration: '20 weeks',
      level: 'intermediate',
      price: 25000,
      isFree: false,
      status: 'published',
      lessons: [],
    },
    {
      slug: 'arabic-literature-classics',
      title: 'Classical Arabic Literature',
      category: 'arabic',
      description: 'Study of classical Arabic poetry and prose, including pre-Islamic poetry, Quranic style, and golden age literature.',
      thumbnailUrl: '/images/patterns/books.svg',
      instructorName: 'Mrs. Khadijah Suleiman',
      duration: '14 weeks',
      level: 'advanced',
      price: 30000,
      isFree: false,
      status: 'published',
      lessons: [],
    },
  ],

  school_products: [
    { slug: 'mushaf-tajweed-color-coded', name: 'Color-Coded Tajweed Mushaf', description: 'Complete Qur\'an with color-coded Tajweed rules for easy learning.', price: 8500, category: 'quran', stock: 50, sku: 'MSHF-TJW-001', isDigital: false, status: 'active' },
    { slug: 'arabic-grammar-textbook-1', name: 'Arabic Grammar Textbook (Nahwu) - Level 1', description: 'Comprehensive textbook covering basic Arabic grammar rules for Ibtidaiyah students.', price: 3500, category: 'textbooks', stock: 100, sku: 'TXT-NHW-001', isDigital: false, status: 'active' },
    { slug: 'sarf-textbook', name: 'Arabic Morphology (Sarf) Textbook', description: 'Complete guide to Arabic word formation and morphology patterns.', price: 4000, category: 'textbooks', stock: 80, sku: 'TXT-SRF-001', isDigital: false, status: 'active' },
    { slug: 'tajweed-rules-handbook', name: 'Tajweed Rules Handbook', description: 'A compact reference guide to all Tajweed rules with examples.', price: 2000, category: 'reference', stock: 150, sku: 'REF-TJW-001', isDigital: false, status: 'active' },
    { slug: 'hadith-forty-nawawi', name: 'Forty Hadith of Imam Nawawi - Commentary', description: 'Arabic text with comprehensive commentary and explanation.', price: 5000, category: 'hadith', stock: 60, sku: 'BK-HDTH-001', isDigital: false, status: 'active' },
    { slug: 'fiqh-maliki-textbook', name: 'Fiqh al-Ibadat (Maliki School)', description: 'Comprehensive textbook on Islamic rulings of worship according to the Maliki school.', price: 6000, category: 'fiqh', stock: 70, sku: 'TXT-FQH-001', isDigital: false, status: 'active' },
    { slug: 'digital-tajweed-guide', name: 'Digital Tajweed Guide', description: 'Interactive digital guide with audio examples of Tajweed rules.', price: 1500, category: 'digital', stock: 999, sku: 'DGT-TJW-001', isDigital: true, status: 'active' },
    { slug: 'arabic-flashcards', name: 'Arabic Alphabet Flashcards', description: 'Set of 28 flashcards with Arabic letters, pronunciation, and example words.', price: 1500, category: 'learning-aids', stock: 200, sku: 'AID-ABC-001', isDigital: false, status: 'active' },
  ],

  school_library_books: [
    { slug: 'tafsir-ibn-kathir', title: 'Tafsir Ibn Kathir (Abridged)', author: 'Imam Ibn Kathir', isbn: '978-1590040050', category: 'tafsir', description: 'One of the most renowned Tafsir of the Qur\'an, abridged for students.', coverImageUrl: '/images/patterns/books.svg', pages: 800, language: 'Arabic/English', publisher: 'Darussalam', publishYear: 2003, isDigital: false, available: true },
    { slug: 'sahih-al-bukhari', title: 'Sahih al-Bukhari', author: 'Imam al-Bukhari', isbn: '978-9960-717-31-5', category: 'hadith', description: 'The most authentic book after the Qur\'an. Collection of Hadith of the Prophet (PBUH).', coverImageUrl: '/images/patterns/books.svg', pages: 1200, language: 'Arabic', publisher: 'Dar al-Kotob al-Ilmiyah', publishYear: 1999, isDigital: false, available: true },
    { slug: 'sahih-muslim', title: 'Sahih Muslim', author: 'Imam Muslim', isbn: '978-9960-717-32-2', category: 'hadith', description: 'The second most authentic Hadith collection.', coverImageUrl: '/images/patterns/books.svg', pages: 1100, language: 'Arabic', publisher: 'Dar al-Kotob al-Ilmiyah', publishYear: 1999, isDigital: false, available: true },
    { slug: 'al-arabiyyah-bayna-yadayk', title: 'Al-Arabiyyah Bayna Yadayk', author: 'Dr. Muhammad Ali', isbn: '978-9960-9801-1-4', category: 'arabic', description: 'Popular Arabic language learning series for non-native speakers.', coverImageUrl: '/images/patterns/books.svg', pages: 300, language: 'Arabic', publisher: 'Arabic for All', publishYear: 2008, isDigital: false, available: true },
    { slug: 'nahwu-al-wadih', title: 'Al-Nahwu al-Wadih', author: 'Ali al-Jarim & Mustafa Amin', isbn: '978-977-09-0001-1', category: 'arabic', description: 'Classic Arabic grammar textbook used in Islamic schools worldwide.', coverImageUrl: '/images/patterns/books.svg', pages: 400, language: 'Arabic', publisher: 'Dar al-Maarif', publishYear: 2005, isDigital: false, available: true },
    { slug: 'fiqh-us-sunnah', title: 'Fiqh us-Sunnah', author: 'Sayyid Sabiq', isbn: '978-09159577-0-3', category: 'fiqh', description: 'Comprehensive guide to Islamic jurisprudence based on Qur\'an and Sunnah.', coverImageUrl: '/images/patterns/books.svg', pages: 500, language: 'Arabic/English', publisher: 'American Trust Publications', publishYear: 1993, isDigital: false, available: true },
  ],

  school_wiki_articles: [
    {
      slug: 'curriculum-overview',
      title: 'Curriculum Overview',
      category: 'academic',
      content: 'Minhaajulhudaa Islamic & Arabic School offers a purely Islamic and Arabic studies curriculum, covering from Tamheedy (Preparatory) to Thanawiyyah (Secondary) level. Our curriculum includes:\n\n## Qur\'an Studies\n- Reading with Tajweed\n- Memorization (Hifz)\n- Tafsir (Exegesis)\n\n## Arabic Language\n- Nahwu (Grammar)\n- Sarf (Morphology)\n- Balaghah (Rhetoric)\n- Literature\n\n## Islamic Sciences\n- Fiqh (Jurisprudence)\n- Aqeedah (Creed)\n- Hadith Studies\n- Seerah (Prophetic Biography)\n- Usul al-Fiqh\n\n## Levels\n1. Tamheedy (Preparatory)\n2. Ibtidaiyah 1-3 (Elementary)\n3. Idadiyah 1-3 (Intermediate)\n4. Thanawiyyah 1-3 (Secondary)',
      excerpt: 'Overview of our Islamic and Arabic studies curriculum from Tamheedy to Thanawiyyah.',
      status: 'published',
      updatedAt: daysAgo(7),
    },
    {
      slug: 'admission-process-guide',
      title: 'Admission Process Guide',
      category: 'admissions',
      content: '## Admission Process\n\n1. **Application**: Complete the admission form online or at the school office.\n2. **Assessment**: Prospective students undergo an age-appropriate assessment.\n3. **Interview**: Parents and students meet with the admission committee.\n4. **Decision**: Admission decisions are communicated within 2 weeks.\n5. **Registration**: Complete registration and fee payment.\n\n## Required Documents\n- Birth certificate\n- Previous school records (if applicable)\n- Passport photographs\n- Medical information\n\n## Age Requirements\n- Tamheedy: 5-6 years\n- Ibtidaiyah 1: 6-7 years\n- Transfer students: Assessment-based placement',
      excerpt: 'Step-by-step guide to the admission process at Minhaajulhudaa School.',
      status: 'published',
      updatedAt: daysAgo(14),
    },
    {
      slug: 'fee-structure-explained',
      title: 'Fee Structure Explained',
      category: 'fees',
      content: '## Fee Structure (1447 AH / 2026 CE)\n\n### Tuition Fees (Per Term)\n- Tamheedy: 25,000 NGN\n- Ibtidaiyah: 30,000 NGN\n- Idadiyah: 35,000 NGN\n- Thanawiyyah: 40,000 NGN\n\n### Additional Fees\n- Registration (one-time): 5,000 NGN\n- Books and materials: 10,000-15,000 NGN\n- Hifz program (optional): 15,000 NGN\n\n### Payment Schedule\n- Term 1: September\n- Term 2: January\n- Term 3: April\n\n### Discounts\n- Sibling discount: 10% for second child, 15% for third\n- Hifz students: 20% discount on regular tuition',
      excerpt: 'Complete breakdown of tuition and other fees for all levels.',
      status: 'published',
      updatedAt: daysAgo(21),
    },
  ],

  school_announcements: [
    { title: '1447 AH Academic Year Begins', content: 'The new academic year 1447 AH begins on Monday, September 9, 2024. All students should arrive by 7:30 AM.', category: 'academic', priority: 'high', publishedAt: daysAgo(3), status: 'active' },
    { title: 'Hifz Graduation Ceremony', content: 'Our annual Hifz graduation ceremony will be held on Saturday, October 12, 2024, at the school mosque. All parents are invited.', category: 'event', priority: 'high', publishedAt: daysAgo(7), status: 'active' },
    { title: 'Parent-Teacher Meeting', content: 'Scheduled for Friday, October 4, 2024, from 10:00 AM to 1:00 PM. Please confirm attendance.', category: 'academic', priority: 'medium', publishedAt: daysAgo(10), status: 'active' },
  ],

  school_events: [
    { slug: 'hifz-graduation-1447', title: 'Hifz Graduation Ceremony 1447 AH', description: 'Celebrating the completion of Qur\'an memorization by our students.', category: 'ceremony', startDate: daysAhead(30), endDate: daysAhead(30), location: 'School Mosque', speaker: 'Ustadh Abdurrahman Adeyemi', schedule: '10:00 AM - 1:00 PM' },
    { slug: 'arabic-poetry-competition', title: 'Annual Arabic Poetry Competition', description: 'Students showcase their Arabic poetry recitation skills.', category: 'competition', startDate: daysAhead(45), endDate: daysAhead(45), location: 'School Hall', speaker: 'Mrs. Khadijah Suleiman', schedule: '9:00 AM - 12:00 PM' },
    { slug: 'parent-teacher-meeting', title: 'Parent-Teacher Meeting', description: 'Termly meeting to discuss student progress.', category: 'meeting', startDate: daysAhead(14), endDate: daysAhead(14), location: 'School Hall', speaker: 'Ustadh Abdurrahman Adeyemi', schedule: '10:00 AM - 1:00 PM' },
    { slug: 'quran-competition-annual', title: 'Annual Qur\'an Recitation Competition', description: 'Inter-class Qur\'an recitation competition with prizes.', category: 'competition', startDate: daysAhead(60), endDate: daysAhead(60), location: 'School Mosque', speaker: 'Ustadh Yusuf Olatunji', schedule: '9:00 AM - 2:00 PM' },
    { slug: 'hadith-memorization-contest', title: 'Hadith Memorization Contest', description: 'Students compete in memorizing the Forty Hadith of Imam Nawawi.', category: 'competition', startDate: daysAhead(75), endDate: daysAhead(75), location: 'School Hall', speaker: 'Ustadh Abdurrahman Adeyemi', schedule: '10:00 AM - 12:00 PM' },
    { slug: 'open-day-1447', title: 'Open Day for Prospective Parents', description: 'Tour our facilities and learn about our Islamic and Arabic studies programs.', category: 'open-day', startDate: daysAhead(90), endDate: daysAhead(90), location: 'School Campus', speaker: 'Mrs. Maryam Disu', schedule: '10:00 AM - 3:00 PM' },
  ],

  school_gallery_albums: [
    { title: 'Hifz Graduation 1447 AH', description: 'Celebrating our Qur\'an memorization graduates.', coverImageUrl: '/images/patterns/quran.svg', images: [{ url: '/images/patterns/quran.svg', caption: 'Graduates receiving their Ijazah certificates' }], category: 'achievements', eventDate: today, createdAt: daysAgo(14) },
    { title: 'Qur\'an Recitation Competition', description: 'Annual Qur\'an recitation competition highlights.', coverImageUrl: '/images/patterns/quran.svg', images: [{ url: '/images/patterns/quran.svg', caption: 'Students reciting with Tajweed' }], category: 'events', eventDate: today, createdAt: daysAgo(21) },
    { title: 'Arabic Calligraphy Exhibition', description: 'Student Arabic calligraphy works.', coverImageUrl: '/images/patterns/arabesque.svg', images: [{ url: '/images/patterns/arabesque.svg', caption: 'Beautiful calligraphy by students' }], category: 'academic', eventDate: today, createdAt: daysAgo(30) },
  ],

  school_testimonials: [
    { authorName: 'Alhaji Muhammad Ali', role: 'Parent', content: 'My son completed his Hifz at Minhaajulhudaa. The teachers are dedicated and the environment is perfect for Islamic learning.', rating: 5, status: 'approved' },
    { authorName: 'Mrs. Fatima Ibrahim', role: 'Parent', content: 'My daughter can now read and understand Arabic texts independently. The Arabic immersion program is excellent.', rating: 5, status: 'approved' },
    { authorName: 'Ustadh Abdullah Olatunji', role: 'Community Scholar', content: 'The graduates of Minhaajulhudaa are well-prepared for advanced Islamic studies. The curriculum is thorough and authentic.', rating: 5, status: 'approved' },
    { authorName: 'Mrs. Khadijah Bello', role: 'Parent', content: 'The Tahdheeb (Islamic etiquette) program has transformed my children\'s behavior at home. May Allah reward the teachers.', rating: 5, status: 'approved' },
  ],

  school_staff: [
    { staffId: 'MHS-STAFF/001', firstName: 'Abdurrahman', lastName: 'Adeyemi', role: 'principal', subjects: [], qualifications: 'B.Ed Islamic Education, M.Ed Educational Administration, Ijazah in Qur\'an recitation', email: 'school.admin@minhaajulhudaa.org', phone: '+2348000000001', bio: 'With over 20 years of experience in Islamic education, Ustadh Abdurrahman leads our school with wisdom and vision.', joinDate: '2021-01-15', status: 'active' },
    { staffId: 'MHS-STAFF/002', firstName: 'Yusuf', lastName: 'Olatunji', role: 'teacher', subjects: ['Qur\'an', 'Tajweed', 'Hifz'], qualifications: 'B.A Islamic Studies, Ijazah in the 10 recitations of the Qur\'an', email: 'yusuf.olatunji@minhaajulhudaa.org', phone: '+2348011111111', bio: 'Lead Hifz instructor with Ijazah in the canonical recitations of the Qur\'an.', joinDate: '2021-02-01', status: 'active' },
    { staffId: 'MHS-STAFF/003', firstName: 'Muhammad', lastName: 'Bashir', role: 'teacher', subjects: ['Fiqh', 'Usul al-Fiqh', 'Aqeedah'], qualifications: 'B.A Islamic Law, M.A Usul al-Fiqh (Al-Azhar University)', email: 'muhammad.bashir@minhaajulhudaa.org', phone: '+2348012222222', bio: 'Fiqh and Usul al-Fiqh specialist, Al-Azhar graduate.', joinDate: '2021-03-10', status: 'active' },
    { staffId: 'MHS-STAFF/004', firstName: 'Aisha', lastName: 'Abdullahi', role: 'teacher', subjects: ['Tahdheeb', 'Qur\'an Reading'], qualifications: 'B.Ed Islamic Education, Diploma in Child Psychology', email: 'aisha.abdullahi@minhaajulhudaa.org', phone: '+2348013333333', bio: 'Specialist in early Islamic education for young children.', joinDate: '2021-09-01', status: 'active' },
    { staffId: 'MHS-STAFF/005', firstName: 'Khadijah', lastName: 'Suleiman', role: 'teacher', subjects: ['Arabic Language', 'Nahwu', 'Sarf', 'Balaghah'], qualifications: 'B.A Arabic Language, M.A Arabic Literature (Islamic University of Madinah)', email: 'khadijah.suleiman@minhaajulhudaa.org', phone: '+2348014444444', bio: 'Native Arabic speaker with expertise in teaching Arabic to non-native speakers.', joinDate: '2022-01-10', status: 'active' },
    { staffId: 'MHS-STAFF/006', firstName: 'Ibrahim', lastName: 'Musa', role: 'teacher', subjects: ['Hadith', 'Mustalah al-Hadith', 'Tafsir'], qualifications: 'B.A Hadith Sciences, M.A Tafsir (Islamic University of Madinah)', email: 'ibrahim.musa@minhaajulhudaa.org', phone: '+2348015555555', bio: 'Hadith and Tafsir specialist with extensive knowledge of classical commentaries.', joinDate: '2022-09-01', status: 'active' },
    { staffId: 'MHS-STAFF/007', firstName: 'Fatima', lastName: 'Bello', role: 'librarian', subjects: [], qualifications: 'B.Library Science, Diploma in Arabic Manuscripts', email: 'fatima.bello@minhaajulhudaa.org', phone: '+2348016666666', bio: 'Our librarian curates a growing collection of over 3,000 Islamic texts.', joinDate: '2021-09-05', status: 'active' },
    { staffId: 'MHS-STAFF/008', firstName: 'Abdullah', lastName: 'Okafor', role: 'accountant', subjects: [], qualifications: 'B.Sc Accounting, ACA', email: 'abdullah.okafor@minhaajulhudaa.org', phone: '+2348017777777', bio: 'Chartered accountant overseeing school finances and fee management.', joinDate: '2021-04-01', status: 'active' },
    { staffId: 'MHS-STAFF/009', firstName: 'Maryam', lastName: 'Disu', role: 'vice-principal', subjects: [], qualifications: 'B.Ed Islamic Studies, M.Ed Educational Management', email: 'maryam.disu@minhaajulhudaa.org', phone: '+2348018888888', bio: 'Vice Principal Academic, overseeing curriculum and academic standards.', joinDate: '2021-05-15', status: 'active' },
    { staffId: 'MHS-STAFF/010', firstName: 'Yahya', lastName: 'Garba', role: 'teacher', subjects: ['Seerah', 'Tahdheeb', 'Islamic History'], qualifications: 'B.A Islamic History, PGDE', email: 'yahya.garba@minhaajulhudaa.org', phone: '+2348019999999', bio: 'Seerah and Islamic history teacher with a passion for bringing the Prophet\'s life to students.', joinDate: '2023-01-10', status: 'active' },
  ],

  school_students: [
    { studentId: 'MHS/1447/001', firstName: 'Abdullah', lastName: 'Muhammad', dateOfBirth: '2018-03-15', gender: 'male', classId: 'tamheedy', className: 'Tamheedy', enrollmentDate: '2024-09-05', status: 'active', guardianName: 'Muhammad Ali', guardianPhone: '+2348031111111', guardianEmail: 'muhammad.ali@example.com', guardianRelationship: 'father', address: '12 Allen Avenue, Ikeja, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/002', firstName: 'Aisha', lastName: 'Ibrahim', dateOfBirth: '2017-07-22', gender: 'female', classId: 'ibtidaiyah-1', className: 'Ibtidaiyah 1', enrollmentDate: '2023-09-06', status: 'active', guardianName: 'Ibrahim Musa', guardianPhone: '+2348032222222', guardianEmail: 'ibrahim.musa@example.com', guardianRelationship: 'father', address: '5 Adeniyi Jones, Ikeja, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/003', firstName: 'Yusuf', lastName: 'Abdulrahman', dateOfBirth: '2015-11-08', gender: 'male', classId: 'ibtidaiyah-3', className: 'Ibtidaiyah 3', enrollmentDate: '2022-09-07', status: 'active', guardianName: 'Abdulrahman Suleiman', guardianPhone: '+2348033333333', guardianEmail: 'abdulrahman.s@example.com', guardianRelationship: 'father', address: '23 Bourdillon Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/004', firstName: 'Khadijah', lastName: 'Olatunji', dateOfBirth: '2016-01-30', gender: 'female', classId: 'ibtidaiyah-2', className: 'Ibtidaiyah 2', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Olatunji Bello', guardianPhone: '+2348034444444', guardianEmail: 'olatunji.bello@example.com', guardianRelationship: 'father', address: '7A Gerrard Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/005', firstName: 'Maryam', lastName: 'Sani', dateOfBirth: '2013-05-14', gender: 'female', classId: 'idadiyah-2', className: 'Idadiyah 2', enrollmentDate: '2021-09-09', status: 'active', guardianName: 'Sani Garba', guardianPhone: '+2348035555555', guardianEmail: 'sani.garba@example.com', guardianRelationship: 'father', address: '15 Cameroun Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/006', firstName: 'Ibrahim', lastName: 'Bashir', dateOfBirth: '2014-09-03', gender: 'male', classId: 'idadiyah-1', className: 'Idadiyah 1', enrollmentDate: '2022-09-07', status: 'active', guardianName: 'Bashir Abdullahi', guardianPhone: '+2348036666666', guardianEmail: 'bashir.a@example.com', guardianRelationship: 'father', address: '44 Alexander Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/007', firstName: 'Fatima', lastName: 'Adeyemi', dateOfBirth: '2019-02-18', gender: 'female', classId: 'tamheedy', className: 'Tamheedy', enrollmentDate: '2024-09-02', status: 'active', guardianName: 'Adeyemi Kazeem', guardianPhone: '+2348037777777', guardianEmail: 'adeyemi.k@example.com', guardianRelationship: 'father', address: '8 Milverton Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/008', firstName: 'Dawud', lastName: 'Okafor', dateOfBirth: '2016-06-25', gender: 'male', classId: 'ibtidaiyah-2', className: 'Ibtidaiyah 2', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Okafor Musa', guardianPhone: '+2348038888888', guardianEmail: 'okafor.musa@example.com', guardianRelationship: 'father', address: '31 Thompson Avenue, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/009', firstName: 'Zainab', lastName: 'Tanko', dateOfBirth: '2014-12-11', gender: 'female', classId: 'idadiyah-1', className: 'Idadiyah 1', enrollmentDate: '2022-09-07', status: 'active', guardianName: 'Tanko Yusuf', guardianPhone: '+2348039999999', guardianEmail: 'tanko.yusuf@example.com', guardianRelationship: 'father', address: '19 Bank Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/010', firstName: 'Umar', lastName: 'Disu', dateOfBirth: '2017-08-07', gender: 'male', classId: 'ibtidaiyah-1', className: 'Ibtidaiyah 1', enrollmentDate: '2023-09-06', status: 'active', guardianName: 'Disu Ibrahim', guardianPhone: '+2348041111111', guardianEmail: 'disu.i@example.com', guardianRelationship: 'father', address: '2 Ruxton Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/011', firstName: 'Hafsa', lastName: 'Bello', dateOfBirth: '2015-04-19', gender: 'female', classId: 'ibtidaiyah-3', className: 'Ibtidaiyah 3', enrollmentDate: '2022-09-07', status: 'active', guardianName: 'Bello Muhammad', guardianPhone: '+2348042222222', guardianEmail: 'bello.m@example.com', guardianRelationship: 'father', address: '26 Glover Road, Ikoyi, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/012', firstName: 'Aliyu', lastName: 'Garba', dateOfBirth: '2012-10-02', gender: 'male', classId: 'thanawiyyah-1', className: 'Thanawiyyah 1', enrollmentDate: '2020-09-10', status: 'active', guardianName: 'Garba Sani', guardianPhone: '+2348043333333', guardianEmail: 'garba.sani@example.com', guardianRelationship: 'father', address: '5 Kakawa Street, Lagos Island', previousSchool: '' },
    { studentId: 'MHS/1447/013', firstName: 'Safiya', lastName: 'Mohammed', dateOfBirth: '2018-11-23', gender: 'female', classId: 'tamheedy', className: 'Tamheedy', enrollmentDate: '2024-09-05', status: 'active', guardianName: 'Mohammed Abubakar', guardianPhone: '+2348044444444', guardianEmail: 'mohammed.a@example.com', guardianRelationship: 'father', address: '11 Ikorodu Road, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/014', firstName: 'Bilal', lastName: 'Sulaiman', dateOfBirth: '2016-03-30', gender: 'male', classId: 'ibtidaiyah-2', className: 'Ibtidaiyah 2', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Sulaiman Adamu', guardianPhone: '+2348045555555', guardianEmail: 'sulaiman.a@example.com', guardianRelationship: 'father', address: '18 Agege Motor Road, Lagos', previousSchool: '' },
    { studentId: 'MHS/1447/015', firstName: 'Ruqayyah', lastName: 'Musa', dateOfBirth: '2013-07-15', gender: 'female', classId: 'idadiyah-2', className: 'Idadiyah 2', enrollmentDate: '2021-09-09', status: 'active', guardianName: 'Musa Abdullahi', guardianPhone: '+2348046666666', guardianEmail: 'musa.a@example.com', guardianRelationship: 'father', address: '7 Broad Street, Lagos Island', previousSchool: '' },
  ],

  school_lessons: [
    { title: 'Introduction to Arabic Alphabet', courseId: 'introduction-to-nahwu', duration: '45 min', type: 'video', order: 1, isFree: true },
    { title: 'Types of Words in Arabic (Ism, Fi\'l, Harf)', courseId: 'introduction-to-nahwu', duration: '60 min', type: 'video', order: 2, isFree: false },
    { title: 'I\'rab (Noun Cases)', courseId: 'introduction-to-nahwu', duration: '50 min', type: 'video', order: 3, isFree: false },
    { title: 'Makharij (Articulation Points)', courseId: 'tajweed-rules-comprehensive', duration: '40 min', type: 'video', order: 1, isFree: true },
    { title: 'Sifat (Characteristics of Letters)', courseId: 'tajweed-rules-comprehensive', duration: '55 min', type: 'video', order: 2, isFree: false },
    { title: 'Rules of Noon Sakinah', courseId: 'tajweed-rules-comprehensive', duration: '45 min', type: 'video', order: 3, isFree: false },
    { title: 'Conditions of Salah', courseId: 'fiqh-of-salah', duration: '40 min', type: 'video', order: 1, isFree: true },
    { title: 'Pillars of Salah', courseId: 'fiqh-of-salah', duration: '50 min', type: 'video', order: 2, isFree: false },
  ],

  school_quizzes: [
    { title: 'Arabic Alphabet Quiz', courseId: 'introduction-to-nahwu', lessonId: 1, questions: [{ question: 'How many letters are in the Arabic alphabet?', options: ['26', '28', '29', '30'], correctAnswer: 1 }] },
    { title: 'Tajweed Basics Quiz', courseId: 'tajweed-rules-comprehensive', lessonId: 1, questions: [{ question: 'What does Tajweed mean?', options: ['To recite quickly', 'To recite properly', 'To memorize', 'To translate'], correctAnswer: 1 }] },
  ],

  school_assignments: [
    { title: 'Memorize Surah Al-Fatihah with Tajweed', courseId: 'tajweed-rules-comprehensive', lessonId: 1, dueDate: daysAhead(7), description: 'Memorize Surah Al-Fatihah and recite it with proper Tajweed rules.' },
    { title: 'Identify I\'rab in 10 Sentences', courseId: 'introduction-to-nahwu', lessonId: 3, dueDate: daysAhead(10), description: 'Read the assigned Arabic sentences and identify the I\'rab of each noun.' },
  ],

  school_enrollments: [
    { studentId: 'MHS/1447/001', courseId: 'introduction-to-nahwu', enrolledAt: daysAgo(30), progress: 30, status: 'active' },
    { studentId: 'MHS/1447/005', courseId: 'tajweed-rules-comprehensive', enrolledAt: daysAgo(20), progress: 60, status: 'active' },
    { studentId: 'MHS/1447/012', courseId: 'fiqh-of-salah', enrolledAt: daysAgo(15), progress: 100, status: 'completed' },
  ],

  school_exam_schedules: [
    { title: 'Mid-Term Tajweed Exam', classId: 'ibtidaiyah-1', date: daysAhead(21), duration: '60 min', totalMarks: 50, description: 'Practical and written exam on Tajweed rules.' },
    { title: 'Nahwu Final Exam', classId: 'idadiyah-1', date: daysAhead(60), duration: '90 min', totalMarks: 100, description: 'Comprehensive Arabic grammar exam.' },
  ],

  school_exam_results: [
    { studentId: 'MHS/1447/005', examId: 1, marks: 45, grade: 'A', remarks: 'Excellent performance in Tajweed.' },
    { studentId: 'MHS/1447/012', examId: 2, marks: 92, grade: 'A+', remarks: 'Outstanding understanding of Nahwu.' },
  ],

  school_fees: [
    { name: 'Tamheedy Tuition', classId: 'tamheedy', amount: 25000, frequency: 'per-term', description: 'Tuition for Tamheedy level' },
    { name: 'Ibtidaiyah Tuition', classId: 'ibtidaiyah-1', amount: 30000, frequency: 'per-term', description: 'Tuition for Ibtidaiyah level' },
    { name: 'Idadiyah Tuition', classId: 'idadiyah-1', amount: 35000, frequency: 'per-term', description: 'Tuition for Idadiyah level' },
    { name: 'Thanawiyyah Tuition', classId: 'thanawiyyah-1', amount: 40000, frequency: 'per-term', description: 'Tuition for Thanawiyyah level' },
    { name: 'Hifz Program Fee', classId: 'hifz-program', amount: 15000, frequency: 'per-term', description: 'Additional fee for Hifz program' },
    { name: 'Registration Fee', classId: 'all', amount: 5000, frequency: 'one-time', description: 'One-time registration fee' },
  ],

  school_invoices: [
    { invoiceNumber: 'INV-1447-001', studentId: 'MHS/1447/001', studentName: 'Abdullah Muhammad', amount: 30000, status: 'paid', dueDate: daysAgo(30), paidDate: daysAgo(25), description: 'Term 1 Tuition + Registration' },
    { invoiceNumber: 'INV-1447-002', studentId: 'MHS/1447/005', studentName: 'Maryam Sani', amount: 35000, status: 'paid', dueDate: daysAgo(30), paidDate: daysAgo(28), description: 'Term 1 Tuition' },
    { invoiceNumber: 'INV-1447-003', studentId: 'MHS/1447/012', studentName: 'Aliyu Garba', amount: 55000, status: 'pending', dueDate: daysAhead(7), description: 'Term 1 Tuition + Hifz Program' },
  ],

  school_payments: [
    { invoiceId: 'INV-1447-001', studentId: 'MHS/1447/001', amount: 30000, method: 'bank_transfer', reference: 'TRF-001', status: 'confirmed', paidAt: daysAgo(25) },
    { invoiceId: 'INV-1447-002', studentId: 'MHS/1447/005', amount: 35000, method: 'cash', reference: 'CASH-001', status: 'confirmed', paidAt: daysAgo(28) },
  ],

  school_orders: [
    { orderNumber: 'ORD-001', customerName: 'Muhammad Ali', customerEmail: 'muhammad.ali@example.com', customerPhone: '+2348031111111', items: [{ name: 'Mushaf Tajweed Color-Coded', quantity: 1, price: 8500 }], total: 8500, status: 'completed', paymentStatus: 'paid', orderedAt: daysAgo(10) },
    { orderNumber: 'ORD-002', customerName: 'Ibrahim Musa', customerEmail: 'ibrahim.musa@example.com', customerPhone: '+2348032222222', items: [{ name: 'Arabic Grammar Textbook', quantity: 1, price: 3500 }, { name: 'Sarf Textbook', quantity: 1, price: 4000 }], total: 7500, status: 'completed', paymentStatus: 'paid', orderedAt: daysAgo(7) },
  ],

  school_admission_applications: [
    { applicationId: 'MHS-APP/1447/001', studentFirstName: 'Abdullah', studentLastName: 'Muhammad', studentDateOfBirth: '2018-03-15', studentGender: 'male', appliedClass: 'Tamheedy', guardianName: 'Muhammad Ali', guardianPhone: '+2348031111111', guardianEmail: 'muhammad.ali@example.com', address: '12 Allen Avenue, Ikeja, Lagos', status: 'approved', submittedAt: daysAgo(60) },
    { applicationId: 'MHS-APP/1447/002', studentFirstName: 'Aisha', studentLastName: 'Ibrahim', studentDateOfBirth: '2017-07-22', studentGender: 'female', appliedClass: 'Ibtidaiyah 1', guardianName: 'Ibrahim Musa', guardianPhone: '+2348032222222', guardianEmail: 'ibrahim.musa@example.com', address: '5 Adeniyi Jones, Ikeja, Lagos', status: 'approved', submittedAt: daysAgo(45) },
    { applicationId: 'MHS-APP/1447/003', studentFirstName: 'Yusuf', studentLastName: 'Abdulrahman', studentDateOfBirth: '2015-11-08', studentGender: 'male', appliedClass: 'Ibtidaiyah 3', guardianName: 'Abdulrahman Suleiman', guardianPhone: '+2348033333333', guardianEmail: 'abdulrahman.s@example.com', address: '23 Bourdillon Road, Ikoyi, Lagos', status: 'pending', submittedAt: daysAgo(10) },
    { applicationId: 'MHS-APP/1447/004', studentFirstName: 'Fatima', studentLastName: 'Okafor', studentDateOfBirth: '2019-02-18', studentGender: 'female', appliedClass: 'Tamheedy', guardianName: 'Okafor Ismail', guardianPhone: '+2348045555555', guardianEmail: 'okafor.ismail@example.com', address: '31 Thompson Avenue, Ikoyi, Lagos', status: 'pending', submittedAt: daysAgo(5) },
  ],

  school_messages: [
    { studentId: 'MHS/1447/001', from: 'teacher', fromName: 'Mrs. Aisha Abdullahi', subject: 'Abdullah\'s Progress', message: 'Abdullah is doing well in his Qur\'an reading. He has memorized Surah Al-Fatihah and Al-Ikhlas.', read: false, sentAt: daysAgo(3) },
    { studentId: 'MHS/1447/005', from: 'admin', fromName: 'Admin Office', subject: 'Fee Payment Reminder', message: 'This is a reminder that Term 1 fees are due by the end of this week.', read: false, sentAt: daysAgo(5) },
  ],
};
