/**
 * School platform seed data - comprehensive production data.
 */

const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d) => new Date(now.getTime() + d * 86400000).toISOString();
const today = now.toISOString().split('T')[0];

export const schoolSeedData = {
  school_pages: [
    {
      slug: 'about',
      title: 'About Minhaajulhudaa School',
      content: [
        { type: 'hero', title: 'About Us', subtitle: 'Nurturing minds with knowledge and faith' },
        { type: 'text', body: 'Minhaajulhudaa School was established in 2021 with a vision to provide quality education that combines academic excellence with authentic Islamic values. Our curriculum integrates the Nigerian national curriculum with comprehensive Islamic studies, Arabic language, and Qur\'an memorization programs.' },
        { type: 'text', body: 'We believe every child is unique and deserves an education that develops their intellectual, spiritual, physical, and social potential. Our dedicated teachers create a nurturing environment where students thrive academically and grow as conscientious Muslims.' },
      ],
      seoTitle: 'About Minhaajulhudaa School',
      seoDescription: 'Learn about Minhaajulhudaa School - providing quality Islamic education since 2021.',
      status: 'published',
      publishedAt: daysAgo(30),
      order: 1,
    },
    {
      slug: 'contact',
      title: 'Contact Us',
      content: [
        { type: 'hero', title: 'Get in Touch', subtitle: 'We are here to help' },
        { type: 'text', body: 'Reach out to us for admissions, inquiries, or to schedule a visit to our campus.' },
      ],
      seoTitle: 'Contact Minhaajulhudaa School',
      seoDescription: 'Contact information for Minhaajulhudaa School.',
      status: 'published',
      publishedAt: daysAgo(30),
      order: 2,
    },
  ],

  school_blog_posts: [
    {
      slug: 'welcome-to-new-academic-year-2026',
      title: 'Welcome to the 2026 Academic Year',
      excerpt: 'As we begin a new academic year, we reflect on our achievements and set new goals for excellence.',
      content: 'Bismillah. As we welcome students back for the 2026 academic year, we are filled with gratitude and excitement. Last year, our students achieved remarkable success in both academic and Islamic studies. 95% of our graduating class passed their WAEC examinations with distinctions, and 12 students completed their Hifz of the Qur\'an.\n\nThis year, we are introducing new programs including advanced robotics, enhanced Arabic language immersion, and a dedicated Tajweed program. Our new science laboratory is fully equipped, and we have expanded our library with over 500 new titles.\n\nWe invite parents to join us for the orientation session on Saturday where we will share detailed plans for the year ahead. Together, we will continue to nurture the next generation of knowledgeable, God-conscious leaders.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
      category: 'announcements',
      tags: ['academic-year', 'welcome', '2026'],
      authorName: 'Ustadh Abdurrahman Adeyemi',
      authorAvatarUrl: '',
      status: 'published',
      publishedAt: daysAgo(7),
      readingTimeMinutes: 3,
      views: 245,
    },
    {
      slug: 'hifz-graduation-ceremony-2026',
      title: '12 Students Complete Qur\'an Memorization',
      excerpt: 'Our Hifz program celebrates another milestone as 12 students complete their memorization of the entire Qur\'an.',
      content: 'Alhamdulillah, we are proud to announce that 12 of our students have successfully completed the memorization of the entire Qur\'an. This achievement represents years of dedication, early morning revisions, and unwavering commitment from both students and their teachers.\n\nThe graduation ceremony was held at the school auditorium, attended by parents, staff, and distinguished guests including renowned scholars. Each graduate received a certificate of completion and a special gift.\n\nOur Hifz program, led by Ustadh Yusuf Olatunji, follows a structured curriculum that allows students to memorize at their own pace while maintaining their regular academic studies. We enroll new students into the program every term.\n\nWe ask Allah to make these students among those who recite the Qur\'an with understanding and act upon its teachings.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      category: 'achievements',
      tags: ['hifz', 'quran', 'graduation'],
      authorName: 'Ustadh Abdurrahman Adeyemi',
      status: 'published',
      publishedAt: daysAgo(14),
      readingTimeMinutes: 4,
      views: 412,
    },
    {
      slug: 'science-fair-2026-highlights',
      title: 'Annual Science Fair Showcases Student Innovation',
      excerpt: 'Students from primary to senior secondary presented innovative projects at our annual science fair.',
      content: 'Our annual science fair was a tremendous success, with over 60 projects presented by students across all levels. The projects ranged from simple experiments by primary students to complex engineering solutions by senior secondary students.\n\nNotable projects included a solar-powered water purification system, a mobile app for tracking salah times, and a hydroponic farming setup. The winning project, by our SS2 students, was an automated greenhouse monitoring system.\n\nThe science fair is part of our commitment to STEM education alongside Islamic studies. We believe that understanding Allah\'s creation through science deepens our faith and enables us to serve humanity better.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
      category: 'events',
      tags: ['science', 'stem', 'innovation'],
      authorName: 'Ustadh Muhammad Bashir',
      status: 'published',
      publishedAt: daysAgo(21),
      readingTimeMinutes: 3,
      views: 187,
    },
    {
      slug: 'parent-teacher-conference-guide',
      title: 'A Guide to Productive Parent-Teacher Conferences',
      excerpt: 'Tips for parents to make the most of parent-teacher conferences and support their children\'s education.',
      content: 'Parent-teacher conferences are valuable opportunities to discuss your child\'s progress and collaborate with teachers. Here are some tips to make these meetings productive:\n\n1. Prepare questions in advance about academic progress, behavior, and social development.\n2. Share information about your child\'s home life that may affect their school performance.\n3. Discuss both strengths and areas for improvement.\n4. Agree on specific action steps and follow up.\n5. Maintain open communication throughout the term.\n\nAt Minhaajulhudaa School, we value the partnership between parents and teachers. Together, we can provide the best educational experience for our students.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800',
      category: 'parenting',
      tags: ['parents', 'tips', 'partnership'],
      authorName: 'Mrs. Aisha Abdullahi',
      status: 'published',
      publishedAt: daysAgo(35),
      readingTimeMinutes: 2,
      views: 156,
    },
    {
      slug: 'arabic-language-immersion-program',
      title: 'New Arabic Language Immersion Program',
      excerpt: 'We are launching an enhanced Arabic immersion program to help students achieve fluency.',
      content: 'Arabic is the language of the Qur\'an and a gateway to understanding Islamic texts. This term, we are launching an enhanced Arabic immersion program across all levels.\n\nThe program includes daily conversational Arabic sessions, Arabic-only zones in designated areas of the school, and cultural activities that bring the language to life. We have also partnered with native Arabic speakers to provide authentic learning experiences.\n\nOur goal is for every student to achieve conversational fluency by the time they graduate, enabling them to understand the Qur\'an directly and engage with Arabic-speaking communities worldwide.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1453749024858-4bca89bd9edc?w=800',
      category: 'programs',
      tags: ['arabic', 'language', 'immersion'],
      authorName: 'Ustadh Abdurrahman Adeyemi',
      status: 'published',
      publishedAt: daysAgo(42),
      readingTimeMinutes: 3,
      views: 203,
    },
  ],

  school_announcements: [
    {
      title: 'School Resumes for Term 1',
      message: 'All students are expected to resume for the first term on Monday, September 8, 2026. Assembly begins at 7:30 AM.',
      type: 'info',
      audience: 'all',
      active: true,
      startsAt: daysAgo(3),
      endsAt: daysAhead(14),
      createdAt: daysAgo(3),
    },
    {
      title: 'Parent-Teacher Conference',
      message: 'The mid-term parent-teacher conference is scheduled for Saturday, October 15, 2026, from 9 AM to 2 PM. Please book your slot through the parent portal.',
      type: 'info',
      audience: 'parents',
      active: true,
      startsAt: daysAgo(1),
      endsAt: daysAhead(30),
      createdAt: daysAgo(1),
    },
    {
      title: 'Holiday Reminder',
      message: 'The school will be on Eid break from Friday to Tuesday. Classes resume on Wednesday. We wish all our families a blessed Eid.',
      type: 'success',
      audience: 'all',
      active: true,
      startsAt: daysAgo(5),
      endsAt: daysAhead(7),
      createdAt: daysAgo(5),
    },
  ],

  school_events: [
    {
      title: 'Term 1 Resumption',
      description: 'First day of the 2026/2027 academic year. Students should arrive by 7:30 AM for assembly.',
      category: 'other',
      startDate: daysAhead(7),
      endDate: daysAhead(7),
      location: 'School Assembly Hall',
      imageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
    },
    {
      title: 'Annual Qur\'an Competition',
      description: 'Inter-house Qur\'an recitation competition. Categories include Tajweed, Memorization, and Tafsir.',
      category: 'cultural',
      startDate: daysAhead(21),
      endDate: daysAhead(21),
      location: 'School Auditorium',
      imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
    },
    {
      title: 'Mid-Term Parent-Teacher Conference',
      description: 'Opportunity for parents to meet with teachers and discuss student progress.',
      category: 'parent-teacher',
      startDate: daysAhead(45),
      endDate: daysAhead(45),
      location: 'Various Classrooms',
    },
    {
      title: 'Sports Day',
      description: 'Annual inter-house sports competition featuring athletics, football, and traditional games.',
      category: 'sports',
      startDate: daysAhead(60),
      endDate: daysAhead(60),
      location: 'School Sports Field',
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    },
    {
      title: 'End of Term Examinations',
      description: 'First term examinations across all subjects. Schedule will be shared two weeks prior.',
      category: 'exam',
      startDate: daysAhead(75),
      endDate: daysAhead(82),
      location: 'Examination Halls',
    },
    {
      title: 'Cultural Day',
      description: 'Celebration of Nigerian and Islamic cultures with food, music, and traditional attire.',
      category: 'cultural',
      startDate: daysAhead(50),
      endDate: daysAhead(50),
      location: 'School Grounds',
      imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
    },
  ],

  school_gallery_albums: [
    {
      title: 'Science Fair 2026',
      description: 'Highlights from our annual science fair showcasing student projects.',
      coverImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
      images: [
        { url: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800', caption: 'Student presenting robotics project' },
        { url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800', caption: 'Chemistry experiment demonstration' },
      ],
      category: 'events',
      eventDate: today,
      createdAt: daysAgo(21),
    },
    {
      title: 'Hifz Graduation',
      description: 'Celebrating our Qur\'an memorization graduates.',
      coverImageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      images: [
        { url: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800', caption: 'Graduates with their certificates' },
      ],
      category: 'achievements',
      eventDate: today,
      createdAt: daysAgo(14),
    },
    {
      title: 'Campus Life',
      description: 'Everyday moments at Minhaajulhudaa School.',
      coverImageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
      images: [
        { url: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800', caption: 'Students in class' },
        { url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800', caption: 'Library study session' },
      ],
      category: 'campus',
      eventDate: today,
      createdAt: daysAgo(10),
    },
  ],

  school_students: [
    { studentId: 'MHS/2026/001', firstName: 'Abdullah', lastName: 'Muhammad', dateOfBirth: '2015-03-15', gender: 'male', classId: 'cls-primary-3', className: 'Primary 3', enrollmentDate: '2022-09-05', status: 'active', guardianName: 'Muhammad Ali', guardianPhone: '+2348031111111', guardianEmail: 'muhammad.ali@example.com', guardianRelationship: 'father', address: '12 Allen Avenue, Ikeja, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: 'Bright Beginnings' },
    { studentId: 'MHS/2026/002', firstName: 'Aisha', lastName: 'Ibrahim', dateOfBirth: '2014-07-22', gender: 'female', classId: 'cls-primary-4', className: 'Primary 4', enrollmentDate: '2021-09-06', status: 'active', guardianName: 'Ibrahim Musa', guardianPhone: '+2348032222222', guardianEmail: 'ibrahim.musa@example.com', guardianRelationship: 'father', address: '5 Adeniyi Jones, Ikeja, Lagos', photoUrl: '', medicalInfo: { allergies: ['peanuts'] }, previousSchool: 'Greenwood Academy' },
    { studentId: 'MHS/2026/003', firstName: 'Yusuf', lastName: 'Abdulrahman', dateOfBirth: '2012-11-08', gender: 'male', classId: 'cls-jss-2', className: 'JSS 2', enrollmentDate: '2020-09-07', status: 'active', guardianName: 'Abdulrahman Suleiman', guardianPhone: '+2348033333333', guardianEmail: 'abdulrahman.s@example.com', guardianRelationship: 'father', address: '23 Bourdillon Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: 'Command Day Secondary School' },
    { studentId: 'MHS/2026/004', firstName: 'Khadijah', lastName: 'Olatunji', dateOfBirth: '2013-01-30', gender: 'female', classId: 'cls-jss-1', className: 'JSS 1', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Olatunji Bello', guardianPhone: '+2348034444444', guardianEmail: 'olatunji.bello@example.com', guardianRelationship: 'father', address: '7A Gerrard Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/005', firstName: 'Maryam', lastName: 'Sani', dateOfBirth: '2010-05-14', gender: 'female', classId: 'cls-sss-2', className: 'SSS 2 Science', enrollmentDate: '2019-09-09', status: 'active', guardianName: 'Sani Garba', guardianPhone: '+2348035555555', guardianEmail: 'sani.garba@example.com', guardianRelationship: 'father', address: '15 Cameroun Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: { asthma: true }, previousSchool: 'Federal Government College' },
    { studentId: 'MHS/2026/006', firstName: 'Ibrahim', lastName: 'Bashir', dateOfBirth: '2011-09-03', gender: 'male', classId: 'cls-sss-1', className: 'SSS 1 Science', enrollmentDate: '2020-09-07', status: 'active', guardianName: 'Bashir Abdullahi', guardianPhone: '+2348036666666', guardianEmail: 'bashir.a@example.com', guardianRelationship: 'father', address: '44 Alexander Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/007', firstName: 'Fatima', lastName: 'Adeyemi', dateOfBirth: '2016-02-18', gender: 'female', classId: 'cls-primary-1', className: 'Primary 1', enrollmentDate: '2024-09-02', status: 'active', guardianName: 'Adeyemi Kazeem', guardianPhone: '+2348037777777', guardianEmail: 'adeyemi.k@example.com', guardianRelationship: 'father', address: '8 Milverton Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/008', firstName: 'Dawud', lastName: 'Okafor', dateOfBirth: '2013-06-25', gender: 'male', classId: 'cls-jss-1', className: 'JSS 1', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Okafor Musa', guardianPhone: '+2348038888888', guardianEmail: 'okafor.musa@example.com', guardianRelationship: 'father', address: '31 Thompson Avenue, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/009', firstName: 'Zainab', lastName: 'Tanko', dateOfBirth: '2011-12-11', gender: 'female', classId: 'cls-sss-1', className: 'SSS 1 Arts', enrollmentDate: '2020-09-07', status: 'active', guardianName: 'Tanko Yusuf', guardianPhone: '+2348039999999', guardianEmail: 'tanko.yusuf@example.com', guardianRelationship: 'father', address: '19 Bank Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/010', firstName: 'Umar', lastName: 'Disu', dateOfBirth: '2014-08-07', gender: 'male', classId: 'cls-primary-4', className: 'Primary 4', enrollmentDate: '2021-09-06', status: 'active', guardianName: 'Disu Ibrahim', guardianPhone: '+2348041111111', guardianEmail: 'disu.i@example.com', guardianRelationship: 'father', address: '2 Ruxton Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/011', firstName: 'Hafsa', lastName: 'Bello', dateOfBirth: '2012-04-19', gender: 'female', classId: 'cls-jss-2', className: 'JSS 2', enrollmentDate: '2020-09-07', status: 'active', guardianName: 'Bello Muhammad', guardianPhone: '+2348042222222', guardianEmail: 'bello.m@example.com', guardianRelationship: 'father', address: '26 Glover Road, Ikoyi, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/012', firstName: 'Aliyu', lastName: 'Garba', dateOfBirth: '2009-10-02', gender: 'male', classId: 'cls-sss-3', className: 'SSS 3 Science', enrollmentDate: '2018-09-10', status: 'active', guardianName: 'Garba Sani', guardianPhone: '+2348043333333', guardianEmail: 'garba.sani@example.com', guardianRelationship: 'father', address: '5 Kakawa Street, Lagos Island', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/013', firstName: 'Safiya', lastName: 'Mohammed', dateOfBirth: '2015-11-23', gender: 'female', classId: 'cls-primary-3', className: 'Primary 3', enrollmentDate: '2022-09-05', status: 'active', guardianName: 'Mohammed Abubakar', guardianPhone: '+2348044444444', guardianEmail: 'mohammed.a@example.com', guardianRelationship: 'father', address: '11 Ikorodu Road, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/014', firstName: 'Bilal', lastName: 'Sulaiman', dateOfBirth: '2013-03-30', gender: 'male', classId: 'cls-jss-1', className: 'JSS 1', enrollmentDate: '2023-09-04', status: 'active', guardianName: 'Sulaiman Adamu', guardianPhone: '+2348045555555', guardianEmail: 'sulaiman.a@example.com', guardianRelationship: 'father', address: '18 Agege Motor Road, Lagos', photoUrl: '', medicalInfo: {}, previousSchool: '' },
    { studentId: 'MHS/2026/015', firstName: 'Ruqayyah', lastName: 'Musa', dateOfBirth: '2010-07-15', gender: 'female', classId: 'cls-sss-2', className: 'SSS 2 Arts', enrollmentDate: '2019-09-09', status: 'active', guardianName: 'Musa Abdullahi', guardianPhone: '+2348046666666', guardianEmail: 'musa.a@example.com', guardianRelationship: 'father', address: '7 Broad Street, Lagos Island', photoUrl: '', medicalInfo: {}, previousSchool: '' },
  ],

  school_staff: [
    { staffId: 'MHS-STAFF/001', firstName: 'Abdurrahman', lastName: 'Adeyemi', role: 'principal', subjects: [], qualifications: 'B.Ed Educational Administration, M.Ed Islamic Education', email: 'school.admin@minhaajulhudaa.com', phone: '+2348000000001', photoUrl: '', bio: 'With over 20 years of experience in Islamic education, Ustadh Abdurrahman leads our school with wisdom and vision.', joinDate: '2021-01-15', status: 'active' },
    { staffId: 'MHS-STAFF/002', firstName: 'Yusuf', lastName: 'Olatunji', role: 'teacher', subjects: ['Qur\'an', 'Tajweed', 'Hifz'], qualifications: 'B.A Islamic Studies, Ijazah in Qur\'an recitation', email: 'yusuf.olatunji@minhaajulhudaa.com', phone: '+2348011111111', photoUrl: '', bio: 'Lead Hifz instructor with Ijazah in the 10 recitations of the Qur\'an.', joinDate: '2021-02-01', status: 'active' },
    { staffId: 'MHS-STAFF/003', firstName: 'Muhammad', lastName: 'Bashir', role: 'teacher', subjects: ['Mathematics', 'Physics', 'Robotics'], qualifications: 'B.Sc Mathematics, M.Sc Physics Education', email: 'muhammad.bashir@minhaajulhudaa.com', phone: '+2348012222222', photoUrl: '', bio: 'STEM coordinator passionate about making science accessible to all students.', joinDate: '2021-03-10', status: 'active' },
    { staffId: 'MHS-STAFF/004', firstName: 'Aisha', lastName: 'Abdullahi', role: 'teacher', subjects: ['English Language', 'Literature'], qualifications: 'B.A English, PGDE', email: 'aisha.abdullahi@minhaajulhudaa.com', phone: '+2348013333333', photoUrl: '', bio: 'English and Literature teacher with a passion for developing young writers.', joinDate: '2021-09-01', status: 'active' },
    { staffId: 'MHS-STAFF/005', firstName: 'Khadijah', lastName: 'Suleiman', role: 'teacher', subjects: ['Arabic Language', 'Islamic Studies'], qualifications: 'B.A Arabic Language, Diploma in Shariah', email: 'khadijah.suleiman@minhaajulhudaa.com', phone: '+2348014444444', photoUrl: '', bio: 'Native Arabic speaker with expertise in teaching Arabic to non-native speakers.', joinDate: '2022-01-10', status: 'active' },
    { staffId: 'MHS-STAFF/006', firstName: 'Ibrahim', lastName: 'Musa', role: 'teacher', subjects: ['Biology', 'Chemistry'], qualifications: 'B.Sc Biology, M.Sc Chemistry', email: 'ibrahim.musa@minhaajulhudaa.com', phone: '+2348015555555', photoUrl: '', bio: 'Science teacher with research experience in environmental science.', joinDate: '2022-09-01', status: 'active' },
    { staffId: 'MHS-STAFF/007', firstName: 'Fatima', lastName: 'Bello', role: 'librarian', subjects: [], qualifications: 'B.Library Science', email: 'fatima.bello@minhaajulhudaa.com', phone: '+2348016666666', photoUrl: '', bio: 'Our librarian curates a growing collection of over 5,000 titles.', joinDate: '2021-09-05', status: 'active' },
    { staffId: 'MHS-STAFF/008', firstName: 'Abdullah', lastName: 'Okafor', role: 'accountant', subjects: [], qualifications: 'B.Sc Accounting, ACA', email: 'abdullah.okafor@minhaajulhudaa.com', phone: '+2348017777777', photoUrl: '', bio: 'Chartered accountant overseeing school finances and fee management.', joinDate: '2021-04-01', status: 'active' },
    { staffId: 'MHS-STAFF/009', firstName: 'Maryam', lastName: 'Disu', role: 'vice-principal', subjects: [], qualifications: 'B.Ed, M.Ed Educational Management', email: 'maryam.disu@minhaajulhudaa.com', phone: '+2348018888888', photoUrl: '', bio: 'Vice Principal Academic, overseeing curriculum and academic standards.', joinDate: '2021-05-15', status: 'active' },
    { staffId: 'MHS-STAFF/010', firstName: 'Yahya', lastName: 'Garba', role: 'teacher', subjects: ['Geography', 'Civic Education'], qualifications: 'B.Sc Geography, PGDE', email: 'yahya.garba@minhaajulhudaa.com', phone: '+2348019999999', photoUrl: '', bio: 'Geography and civic education teacher with field research experience.', joinDate: '2023-01-10', status: 'active' },
  ],

  school_classes: [
    { name: 'Primary 1', level: 'primary', grade: 'P1', teacherId: 'MHS-STAFF/004', teacherName: 'Mrs. Aisha Abdullahi', room: 'Room 101', capacity: 25, currentEnrollment: 22, subjects: ['English', 'Mathematics', 'Basic Science', 'Islamic Studies', 'Arabic', 'Qur\'an'], schedule: { days: ['Mon-Fri'], time: '8:00 AM - 2:00 PM' }, description: 'Foundation class for young learners.', active: true },
    { name: 'Primary 3', level: 'primary', grade: 'P3', teacherId: 'MHS-STAFF/010', teacherName: 'Ustadh Yahya Garba', room: 'Room 103', capacity: 30, currentEnrollment: 28, subjects: ['English', 'Mathematics', 'Basic Science', 'Islamic Studies', 'Arabic', 'Qur\'an', 'Social Studies'], schedule: { days: ['Mon-Fri'], time: '8:00 AM - 2:00 PM' }, description: 'Lower primary class building on foundational skills.', active: true },
    { name: 'Primary 4', level: 'primary', grade: 'P4', teacherId: 'MHS-STAFF/005', teacherName: 'Mrs. Khadijah Suleiman', room: 'Room 104', capacity: 30, currentEnrollment: 27, subjects: ['English', 'Mathematics', 'Basic Science', 'Islamic Studies', 'Arabic', 'Qur\'an', 'Social Studies', 'Computer Science'], schedule: { days: ['Mon-Fri'], time: '8:00 AM - 2:30 PM' }, description: 'Upper primary class preparing for junior secondary.', active: true },
    { name: 'JSS 1', level: 'junior-secondary', grade: 'J1', teacherId: 'MHS-STAFF/003', teacherName: 'Ustadh Muhammad Bashir', room: 'Room 201', capacity: 35, currentEnrollment: 32, subjects: ['English', 'Mathematics', 'Basic Science', 'Basic Technology', 'Islamic Studies', 'Arabic', 'Qur\'an', 'Social Studies', 'Computer Science', 'Agricultural Science'], schedule: { days: ['Mon-Fri'], time: '7:30 AM - 3:00 PM' }, description: 'Entry into junior secondary education.', active: true },
    { name: 'JSS 2', level: 'junior-secondary', grade: 'J2', teacherId: 'MHS-STAFF/006', teacherName: 'Ustadh Ibrahim Musa', room: 'Room 202', capacity: 35, currentEnrollment: 30, subjects: ['English', 'Mathematics', 'Basic Science', 'Basic Technology', 'Islamic Studies', 'Arabic', 'Qur\'an', 'Social Studies', 'Computer Science', 'Agricultural Science', 'French'], schedule: { days: ['Mon-Fri'], time: '7:30 AM - 3:00 PM' }, description: 'Continued junior secondary education.', active: true },
    { name: 'SSS 1 Science', level: 'senior-secondary', grade: 'S1', teacherId: 'MHS-STAFF/003', teacherName: 'Ustadh Muhammad Bashir', room: 'Room 301', capacity: 30, currentEnrollment: 28, subjects: ['English', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Islamic Studies', 'Arabic', 'Computer Science'], schedule: { days: ['Mon-Fri'], time: '7:30 AM - 3:30 PM' }, description: 'Senior secondary science track.', active: true },
    { name: 'SSS 2 Science', level: 'senior-secondary', grade: 'S2', teacherId: 'MHS-STAFF/006', teacherName: 'Ustadh Ibrahim Musa', room: 'Room 302', capacity: 30, currentEnrollment: 26, subjects: ['English', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Islamic Studies', 'Arabic', 'Computer Science'], schedule: { days: ['Mon-Fri'], time: '7:30 AM - 3:30 PM' }, description: 'Senior secondary science track, year 2.', active: true },
    { name: 'SSS 3 Science', level: 'senior-secondary', grade: 'S3', teacherId: 'MHS-STAFF/009', teacherName: 'Mrs. Maryam Disu', room: 'Room 303', capacity: 30, currentEnrollment: 24, subjects: ['English', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Islamic Studies', 'Arabic', 'Computer Science'], schedule: { days: ['Mon-Fri'], time: '7:30 AM - 3:30 PM' }, description: 'Final year senior secondary, WAEC preparation.', active: true },
  ],

  school_programs: [
    {
      slug: 'hifz-program',
      title: 'Hifz (Qur\'an Memorization) Program',
      category: 'islamic-studies',
      description: 'A structured program for memorizing the entire Qur\'an with proper Tajweed, integrated with regular academic studies.',
      curriculum: 'The program follows a progressive memorization schedule: 2-3 pages daily for beginners, increasing as proficiency grows. Daily revision (Muraja\'ah) of previously memorized portions. Weekly assessment with the lead Hifz teacher. Monthly evaluation with external examiners. Annual certification upon completion.',
      duration: '3-5 years',
      requirements: ['Age 7+', 'Basic Qur\'an reading ability', 'Commitment from student and parents', 'Passing admission assessment'],
      outcomes: ['Ijazah in Qur\'an recitation', 'Certificate of Hifz completion', 'Strong foundation in Tajweed', 'Enhanced memory and discipline'],
      imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      instructor: 'Ustadh Yusuf Olatunji',
      fee: 50000,
      status: 'open',
    },
    {
      slug: 'arabic-immersion',
      title: 'Arabic Language Immersion',
      category: 'islamic-studies',
      description: 'An enhanced Arabic language program designed to achieve conversational fluency and Qur\'anic comprehension.',
      curriculum: 'Daily conversational Arabic sessions, Arabic-only zones, cultural activities, weekly Arabic storytelling, and integration with Islamic Studies. Uses modern communicative language teaching methods.',
      duration: 'Ongoing (all levels)',
      requirements: ['Enrolled student', 'Commitment to practice'],
      outcomes: ['Conversational fluency', 'Qur\'anic Arabic comprehension', 'Cultural understanding', 'Preparation for advanced Arabic studies'],
      imageUrl: 'https://images.unsplash.com/photo-1453749024858-4bca89bd9edc?w=800',
      instructor: 'Mrs. Khadijah Suleiman',
      fee: 0,
      status: 'open',
    },
    {
      slug: 'stem-robotics',
      title: 'STEM & Robotics Program',
      category: 'extracurricular',
      description: 'Hands-on program exploring science, technology, engineering, and mathematics through robotics and coding.',
      curriculum: 'Weekly sessions covering block-based coding, introduction to Python, robotics building and programming, participation in local and national robotics competitions.',
      duration: '1 academic year',
      requirements: ['Age 10+', 'Basic computer literacy', 'Science aptitude'],
      outcomes: ['Coding proficiency', 'Robotics building skills', 'Problem-solving abilities', 'Competition experience'],
      imageUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800',
      instructor: 'Ustadh Muhammad Bashir',
      fee: 30000,
      status: 'open',
    },
    {
      slug: 'sports-academy',
      title: 'Sports Academy',
      category: 'sports',
      description: 'Comprehensive sports program developing physical fitness, teamwork, and competitive skills.',
      curriculum: 'Football, basketball, athletics, swimming, and traditional sports. Training sessions three times weekly with certified coaches.',
      duration: 'Ongoing',
      requirements: ['Medical fitness clearance', 'Sports attire'],
      outcomes: ['Physical fitness', 'Teamwork skills', 'Competitive experience', 'Sportsmanship'],
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      instructor: 'Coach Abdullah Hassan',
      fee: 20000,
      status: 'open',
    },
  ],

  school_admission_applications: [
    {
      applicationId: 'MHS-APP/2026/001',
      studentFirstName: 'Hamzah', studentLastName: 'Abdullah', studentDateOfBirth: '2019-04-12', studentGender: 'male',
      appliedClass: 'Primary 1', previousSchool: 'Happy Tots Nursery',
      guardianName: 'Abdullah Ibrahim', guardianPhone: '+2348051111111', guardianEmail: 'abdullah.ibrahim@example.com',
      guardianOccupation: 'Doctor', address: '15 Adeola Odeku Street, Victoria Island, Lagos',
      additionalInfo: 'Hamzah is an active child who loves reading and puzzles.',
      status: 'pending', submittedAt: daysAgo(2),
    },
    {
      applicationId: 'MHS-APP/2026/002',
      studentFirstName: 'Aaminah', studentLastName: 'Yusuf', studentDateOfBirth: '2017-08-25', studentGender: 'female',
      appliedClass: 'Primary 3', previousSchool: 'Greenfield Academy',
      guardianName: 'Yusuf Bello', guardianPhone: '+2348052222222', guardianEmail: 'yusuf.bello@example.com',
      guardianOccupation: 'Engineer', address: '8 Akin Adesola Street, Victoria Island, Lagos',
      additionalInfo: 'Aaminah has memorized Juz Amma and is eager to continue her Hifz journey.',
      status: 'reviewed', submittedAt: daysAgo(5), reviewedAt: daysAgo(1),
      reviewNotes: 'Strong candidate. Recommended for admission assessment.',
    },
    {
      applicationId: 'MHS-APP/2026/003',
      studentFirstName: 'Mu\'adh', studentLastName: 'Suleiman', studentDateOfBirth: '2014-01-18', studentGender: 'male',
      appliedClass: 'JSS 1', previousSchool: 'Al-Noor Academy',
      guardianName: 'Suleiman Garba', guardianPhone: '+2348053333333', guardianEmail: 'suleiman.garba@example.com',
      guardianOccupation: 'Architect', address: '23 Norman Williams Street, Ikoyi, Lagos',
      additionalInfo: 'Transferring from Al-Noor Academy. Mu\'adh excels in mathematics.',
      status: 'accepted', submittedAt: daysAgo(10), reviewedAt: daysAgo(7),
      reviewNotes: 'Excellent academic record. Admission approved.',
    },
    {
      applicationId: 'MHS-APP/2026/004',
      studentFirstName: 'Sumayyah', studentLastName: 'Adamu', studentDateOfBirth: '2013-11-30', studentGender: 'female',
      appliedClass: 'JSS 2', previousSchool: 'Command Day School',
      guardianName: 'Adamu Musa', guardianPhone: '+2348054444444', guardianEmail: 'adamu.musa@example.com',
      guardianOccupation: 'Civil Servant', address: '5 Cameron Road, Ikoyi, Lagos',
      additionalInfo: 'Looking for a school with strong Islamic values.',
      status: 'pending', submittedAt: daysAgo(1),
    },
  ],

  school_courses: [
    {
      slug: 'introduction-to-tajweed',
      title: 'Introduction to Tajweed: The Art of Qur\'an Recitation',
      description: 'Learn the fundamental rules of Tajweed to recite the Qur\'an correctly and beautifully. This course covers the articulation points of letters, characteristics of letters, and basic rules of recitation.',
      shortDescription: 'Master the basics of Tajweed for beautiful Qur\'an recitation.',
      category: 'quran',
      level: 'beginner',
      instructor: 'Ustadh Yusuf Olatunji',
      instructorBio: 'Holder of Ijazah in the 10 recitations of the Qur\'an with over 15 years of teaching experience.',
      price: 0,
      duration: '8 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      lessonsCount: 12,
      enrolledCount: 145,
      rating: 4.9,
      status: 'published',
      publishedAt: daysAgo(30),
    },
    {
      slug: 'arabic-for-beginners',
      title: 'Arabic for Beginners: Reading and Writing',
      description: 'Start your journey with the Arabic language. Learn to read, write, and pronounce Arabic letters and basic words. This course is perfect for absolute beginners.',
      shortDescription: 'Learn to read and write Arabic from scratch.',
      category: 'arabic',
      level: 'beginner',
      instructor: 'Mrs. Khadijah Suleiman',
      instructorBio: 'Native Arabic speaker with expertise in teaching Arabic to non-native speakers.',
      price: 0,
      duration: '10 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1453749024858-4bca89bd9edc?w=800',
      lessonsCount: 15,
      enrolledCount: 203,
      rating: 4.8,
      status: 'published',
      publishedAt: daysAgo(45),
    },
    {
      slug: 'seerah-of-the-prophet',
      title: 'Seerah: Life of the Prophet Muhammad (PBUH)',
      description: 'Explore the beautiful life of the Prophet Muhammad (peace be upon him) from birth to his final days. Learn lessons applicable to modern life.',
      shortDescription: 'Journey through the life of the Beloved Prophet (PBUH).',
      category: 'islamic-studies',
      level: 'intermediate',
      instructor: 'Ustadh Abdurrahman Adeyemi',
      instructorBio: 'Principal with M.Ed in Islamic Education and 20+ years of teaching experience.',
      price: 0,
      duration: '12 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800',
      lessonsCount: 20,
      enrolledCount: 178,
      rating: 5.0,
      status: 'published',
      publishedAt: daysAgo(60),
    },
    {
      slug: 'basic-mathematics-jss',
      title: 'Basic Mathematics for JSS',
      description: 'Comprehensive mathematics course covering the JSS curriculum including algebra, geometry, and statistics.',
      shortDescription: 'Master JSS-level mathematics fundamentals.',
      category: 'academic',
      level: 'intermediate',
      instructor: 'Ustadh Muhammad Bashir',
      instructorBio: 'STEM coordinator with M.Sc in Physics Education.',
      price: 0,
      duration: 'Ongoing',
      thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
      lessonsCount: 18,
      enrolledCount: 92,
      rating: 4.7,
      status: 'published',
      publishedAt: daysAgo(20),
    },
    {
      slug: 'introduction-to-coding',
      title: 'Introduction to Coding with Scratch',
      description: 'Learn programming fundamentals using Scratch. Create animations, games, and interactive stories while developing problem-solving skills.',
      shortDescription: 'Start coding with fun, visual programming.',
      category: 'technology',
      level: 'beginner',
      instructor: 'Ustadh Muhammad Bashir',
      instructorBio: 'STEM coordinator passionate about making technology accessible.',
      price: 15000,
      duration: '6 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?w=800',
      lessonsCount: 10,
      enrolledCount: 67,
      rating: 4.6,
      status: 'published',
      publishedAt: daysAgo(15),
    },
  ],

  school_lessons: [
    // Tajweed course lessons
    { courseId: 'course-tajweed-001', title: 'Introduction to Tajweed', content: 'What is Tajweed and why is it important? Understanding the obligation of reciting the Qur\'an correctly.', videoUrl: '', duration: 25, order: 1, resources: [], isPreview: true },
    { courseId: 'course-tajweed-001', title: 'Articulation Points (Makharij) - Part 1', content: 'Learn the articulation points of Arabic letters from the throat and tongue.', videoUrl: '', duration: 35, order: 2, resources: [{ type: 'pdf', url: '#', title: 'Makharij Chart' }] },
    { courseId: 'course-tajweed-001', title: 'Articulation Points (Makharij) - Part 2', content: 'Continue learning the articulation points of remaining letters.', videoUrl: '', duration: 32, order: 3, resources: [] },
    { courseId: 'course-tajweed-001', title: 'Characteristics of Letters (Sifat) - Part 1', content: 'Understanding the permanent and temporary characteristics of Arabic letters.', videoUrl: '', duration: 40, order: 4, resources: [] },
    // Arabic course lessons
    { courseId: 'course-arabic-001', title: 'The Arabic Alphabet', content: 'Learn to recognize, pronounce, and write all 28 Arabic letters.', videoUrl: '', duration: 30, order: 1, resources: [], isPreview: true },
    { courseId: 'course-arabic-001', title: 'Vowel Marks (Harakat)', content: 'Learn the Fatha, Kasra, Damma, and Sukun vowel marks.', videoUrl: '', duration: 25, order: 2, resources: [] },
    { courseId: 'course-arabic-001', title: 'Joining Letters', content: 'How letters join to form words in Arabic script.', videoUrl: '', duration: 35, order: 3, resources: [] },
  ],

  school_products: [
    { slug: 'school-uniform-primary', name: 'School Uniform - Primary', description: 'Official school uniform set for primary students. Includes shirt, trousers/skirt, and blazer.', price: 15000, compareAtPrice: 18000, category: 'uniforms', images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800'], stock: 50, sku: 'UNI-PRI-001', variants: [{ name: 'Size', options: ['6', '8', '10', '12', '14'] }], isDigital: false, status: 'active' },
    { slug: 'school-uniform-secondary', name: 'School Uniform - Secondary', description: 'Official school uniform set for secondary students. Includes shirt, trousers/skirt, and blazer.', price: 18000, category: 'uniforms', images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800'], stock: 40, sku: 'UNI-SEC-001', variants: [{ name: 'Size', options: ['S', 'M', 'L', 'XL'] }], isDigital: false, status: 'active' },
    { slug: 'quran-textbook-grade1', name: 'Qur\'an Studies Textbook - Grade 1', description: 'Comprehensive Qur\'an studies textbook for Grade 1 students following the Minhaajulhudaa curriculum.', price: 3500, category: 'books', images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800'], stock: 100, sku: 'BK-QUR-G1-001', isDigital: false, status: 'active' },
    { slug: 'arabic-textbook-beginners', name: 'Arabic Language for Beginners', description: 'Foundational Arabic language textbook with exercises and audio companion.', price: 4500, category: 'books', images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800'], stock: 75, sku: 'BK-ARA-001', isDigital: false, status: 'active' },
    { slug: 'mathematics-workbook-jss', name: 'Mathematics Workbook - JSS', description: 'Practice workbook covering the complete JSS mathematics curriculum with 500+ problems.', price: 3000, category: 'books', images: ['https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800'], stock: 80, sku: 'BK-MAT-JSS-001', isDigital: false, status: 'active' },
    { slug: 'school-bag-official', name: 'Official School Bag', description: 'Durable, branded school bag with multiple compartments and ergonomic design.', price: 8000, compareAtPrice: 10000, category: 'supplies', images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'], stock: 60, sku: 'SUP-BAG-001', isDigital: false, status: 'active' },
    { slug: 'sports-kit', name: 'Sports Kit', description: 'Complete sports kit including jersey, shorts, and socks with school branding.', price: 6000, category: 'supplies', images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800'], stock: 45, sku: 'SUP-SPT-001', isDigital: false, status: 'active' },
    { slug: 'digital-tajweed-guide', name: 'Digital Tajweed Guide (PDF)', description: 'Comprehensive digital guide to Tajweed rules with audio examples and practice exercises.', price: 2000, category: 'digital', images: ['https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800'], stock: 999, sku: 'DIG-TAJ-001', isDigital: true, downloadUrl: 'https://minhaajulhudaa.com/files/tajweed-guide.pdf', status: 'active' },
  ],

  school_library_books: [
    { title: 'Tafsir Ibn Kathir (Abridged)', author: 'Ibn Kathir', isbn: '978-1591440208', category: 'quran', description: 'A comprehensive tafsir of the Qur\'an, abridged for accessibility.', coverImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400', pdfUrl: '', pages: 800, language: 'English', publisher: 'Darussalam', publishYear: 2003, isDigital: true, available: true },
    { title: 'Riyad as-Saliheen', author: 'Imam Nawawi', isbn: '978-1591440475', category: 'hadith', description: 'Collection of hadiths on ethics, manners, and worship.', coverImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400', pdfUrl: '', pages: 700, language: 'English', publisher: 'Darussalam', publishYear: 1999, isDigital: true, available: true },
    { title: 'Arabic Course for English-Speaking Students', author: 'Dr. V. Abdur Rahim', isbn: '978-1872531519', category: 'arabic', description: 'Three-volume Arabic language course widely used in Islamic universities.', coverImageUrl: 'https://images.unsplash.com/photo-1453749024858-4bca89bd9edc?w=400', pdfUrl: '', pages: 450, language: 'English/Arabic', publisher: 'UK Islamic Academy', publishYear: 2003, isDigital: false, available: true },
    { title: 'Sealed Nectar (Ar-Raheeq Al-Makhtum)', author: 'Safiur-Rahman Mubarakpuri', isbn: '978-1591440710', category: 'seerah', description: 'Award-winning biography of the Prophet Muhammad (PBUH).', coverImageUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=400', pdfUrl: '', pages: 500, language: 'English', publisher: 'Darussalam', publishYear: 2002, isDigital: true, available: true },
    { title: 'Foundation Mathematics for JSS', author: 'M. A. Adeyemi', isbn: '978-9781234567', category: 'academic', description: 'Comprehensive mathematics textbook aligned with the JSS curriculum.', coverImageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400', pdfUrl: '', pages: 320, language: 'English', publisher: 'Minhaajulhudaa Press', publishYear: 2024, isDigital: false, available: true },
    { title: 'Innovative Science for Senior Secondary', author: 'Dr. A. B. Mohammed', isbn: '978-9782345678', category: 'academic', description: 'Integrated science textbook covering physics, chemistry, and biology.', coverImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400', pdfUrl: '', pages: 400, language: 'English', publisher: 'Minhaajulhudaa Press', publishYear: 2024, isDigital: false, available: true },
  ],

  school_wiki_articles: [
    {
      slug: 'admission-process-guide',
      title: 'School Admission Process: A Complete Guide',
      content: 'This guide walks you through the complete admission process at Minhaajulhudaa School, from application to enrollment.\n\n## Step 1: Application\nComplete the online admission form available on our website. You will need to provide student information, guardian details, and previous school records.\n\n## Step 2: Assessment\nAfter reviewing your application, we will invite the student for an assessment. The assessment evaluates academic readiness and Qur\'an reading ability.\n\n## Step 3: Interview\nSelected students and their parents will be invited for an interview with the admission committee.\n\n## Step 4: Admission Decision\nDecisions are communicated within two weeks of the interview. Accepted students receive an admission letter with enrollment details.\n\n## Step 5: Enrollment\nComplete the enrollment by paying the required fees and submitting remaining documents.',
      category: 'admissions',
      tags: ['admission', 'guide', 'process'],
      author: 'Admission Office',
      order: 1,
      views: 542,
      status: 'published',
      updatedAt: daysAgo(5),
    },
    {
      slug: 'fee-structure-explained',
      title: 'Understanding Our Fee Structure',
      content: 'A detailed breakdown of school fees and payment options.\n\n## Tuition Fees\nTuition varies by level:\n- Primary: ₦150,000 per term\n- Junior Secondary: ₦180,000 per term\n- Senior Secondary: ₦200,000 per term\n\n## Additional Fees\n- Registration (one-time): ₦20,000\n- Uniform: ₦15,000 - ₦18,000\n- Books: ₦10,000 - ₦20,000\n- Sports: ₦5,000 per term\n- Transportation (optional): ₦30,000 per term\n\n## Payment Options\n- Full term payment\n- Installment plan (3 installments)\n- Sibling discount (10% for 2nd child, 15% for 3rd+)\n\n## Scholarships\nWe offer merit-based scholarships for outstanding students and need-based financial aid.',
      category: 'finance',
      tags: ['fees', 'payment', 'tuition'],
      author: 'Finance Office',
      order: 2,
      views: 387,
      status: 'published',
      updatedAt: daysAgo(10),
    },
    {
      slug: 'curriculum-overview',
      title: 'Our Curriculum Overview',
      content: 'Minhaajulhudaa School offers an integrated curriculum combining the Nigerian national curriculum with comprehensive Islamic studies.\n\n## Academic Subjects\nEnglish, Mathematics, Sciences, Social Studies, Computer Science, and Languages.\n\n## Islamic Studies\nQur\'an (recitation and memorization), Tajweed, Arabic Language, Islamic History, Fiqh, and Akhlaq.\n\n## Extracurricular\nSports, Robotics, Debating, Arts, and Community Service.\n\n## Assessment\nContinuous assessment (40%) and termly examinations (60%).',
      category: 'academics',
      tags: ['curriculum', 'academics'],
      author: 'Academic Office',
      order: 3,
      views: 298,
      status: 'published',
      updatedAt: daysAgo(15),
    },
  ],

  school_testimonials: [
    { authorName: 'Dr. Muhammad Ali', authorRole: 'Parent of Abdullah (Primary 3)', authorAvatarUrl: '', content: 'Minhaajulhudaa School has been a blessing for our family. My son has not only excelled academically but has also developed a deep love for the Qur\'an. The teachers are dedicated and genuinely care about each student\'s spiritual and academic growth.', rating: 5, status: 'approved', createdAt: daysAgo(7) },
    { authorName: 'Mrs. Aisha Bello', authorRole: 'Parent of Khadijah (JSS 1)', authorAvatarUrl: '', content: 'The Arabic immersion program is exceptional. My daughter can now converse in Arabic and understands much of what she recites from the Qur\'an. The school\'s holistic approach to education is truly commendable.', rating: 5, status: 'approved', createdAt: daysAgo(14) },
    { authorName: 'Engineer Yusuf Garba', authorRole: 'Parent of Maryam (SSS 2)', authorAvatarUrl: '', content: 'As a parent, I appreciate the balance between academic rigor and Islamic values. Maryam scored 8 distinctions in her WAEC and credits the school\'s supportive environment. The science laboratories are well-equipped.', rating: 5, status: 'approved', createdAt: daysAgo(21) },
    { authorName: 'Alhaji Ibrahim Musa', authorRole: 'Parent of two alumni', authorAvatarUrl: '', content: 'Both my children graduated from Minhaajulhudaa and are now studying at top universities. The foundation they received here - both academic and moral - has been invaluable. I highly recommend this school.', rating: 5, status: 'approved', createdAt: daysAgo(30) },
  ],

  school_fees: [
    { name: 'Primary School Tuition', classLevel: 'primary', amount: 150000, currency: 'NGN', frequency: 'per-term', category: 'tuition', description: 'Tuition fee for primary school students per term.', active: true },
    { name: 'Junior Secondary Tuition', classLevel: 'junior-secondary', amount: 180000, currency: 'NGN', frequency: 'per-term', category: 'tuition', description: 'Tuition fee for junior secondary students per term.', active: true },
    { name: 'Senior Secondary Tuition', classLevel: 'senior-secondary', amount: 200000, currency: 'NGN', frequency: 'per-term', category: 'tuition', description: 'Tuition fee for senior secondary students per term.', active: true },
    { name: 'Registration Fee', amount: 20000, currency: 'NGN', frequency: 'one-time', category: 'tuition', description: 'One-time registration fee for new students.', active: true },
    { name: 'Transportation', amount: 30000, currency: 'NGN', frequency: 'per-term', category: 'transport', description: 'Optional school bus service per term.', active: true },
    { name: 'Sports Fee', amount: 5000, currency: 'NGN', frequency: 'per-term', category: 'activities', description: 'Sports and physical education fee per term.', active: true },
  ],

  school_quizzes: [
    { courseId: 'course-tajweed-001', lessonId: 'lesson-tajweed-001', title: 'Tajweed Basics Quiz', description: 'Test your understanding of basic Tajweed concepts.', questions: [{ question: 'What does Tajweed mean?', options: ['Beautiful recitation', 'Rules of recitation', 'Memorization', 'Translation'], correct: 1 }, { question: 'How many articulation points (Makharij) are there?', options: ['5', '12', '17', '28'], correct: 2 }], timeLimitMinutes: 15, passingScore: 70, attempts: 45 },
    { courseId: 'course-arabic-001', title: 'Arabic Alphabet Quiz', description: 'Test your knowledge of the Arabic alphabet.', questions: [{ question: 'How many letters are in the Arabic alphabet?', options: ['26', '28', '30', '32'], correct: 1 }, { question: 'Which letter is pronounced from the throat?', options: ['ب', 'ت', 'ع', 'م'], correct: 2 }], timeLimitMinutes: 10, passingScore: 70, attempts: 67 },
  ],
};
