/**
 * Shared seed data - admin users, platform settings.
 */
import bcrypt from 'bcryptjs';

const ADMIN_PASSWORD = process.env.ADMIN_SEED_PASSWORD || 'ChangeMe@2026';
const passwordHash = bcrypt.hashSync(ADMIN_PASSWORD, 10);

export const sharedSeedData = {
  platform_admins: [
    {
      email: 'admin@minhaajulhudaa.com',
      passwordHash,
      name: 'Super Admin',
      role: 'super_admin',
      platforms: ['school', 'masjid', 'charity', 'travels'],
      avatarUrl: '',
      phone: '+2348000000000',
      lastLoginAt: null,
      active: true,
      metadata: { title: 'System Administrator' },
    },
    {
      email: 'school.admin@minhaajulhudaa.com',
      passwordHash,
      name: 'Ustadh Abdurrahman Adeyemi',
      role: 'platform_admin',
      platforms: ['school'],
      phone: '+2348000000001',
      active: true,
      metadata: { title: 'School Principal' },
    },
    {
      email: 'masjid.admin@minhaajulhudaa.com',
      passwordHash,
      name: 'Imam Yusuf Olatunji',
      role: 'platform_admin',
      platforms: ['masjid'],
      phone: '+2348000000002',
      active: true,
      metadata: { title: 'Masjid Administrator' },
    },
    {
      email: 'charity.admin@minhaajulhudaa.com',
      passwordHash,
      name: 'Malik Ibrahim Suleiman',
      role: 'platform_admin',
      platforms: ['charity'],
      phone: '+2348000000003',
      active: true,
      metadata: { title: 'Charity Director' },
    },
    {
      email: 'travels.admin@minhaajulhudaa.com',
      passwordHash,
      name: 'Ustadh Dawud Okafor',
      role: 'platform_admin',
      platforms: ['travels'],
      phone: '+2348000000004',
      active: true,
      metadata: { title: 'Travels Manager' },
    },
  ],

  platform_settings: [
    {
      platform: 'global',
      siteName: 'Minhaajulhudaa',
      tagline: 'Guiding to the Right Path',
      description: 'A multi-platform Islamic organization serving the Ummah through education, worship, charity, and sacred journeys.',
      logoUrl: 'https://minhaajulhudaa.com/favicon.svg',
      primaryColor: '#05B34D',
      accentColor: '#F2B91C',
      contactEmail: 'info@minhaajulhudaa.com',
      contactPhone: '+2348000000000',
      address: 'Minhaajulhudaa Complex, Lagos, Nigeria',
      location: { type: 'Point', coordinates: [3.3792, 6.5244] },
      socialLinks: {
        twitter: 'https://twitter.com/minhaajulhudaa',
        facebook: 'https://facebook.com/minhaajulhudaa',
        instagram: 'https://instagram.com/minhaajulhudaa',
        youtube: 'https://youtube.com/@minhaajulhudaa',
      },
      paymentConfig: { provider: 'paystack', currency: 'NGN' },
      metadata: { established: '2020' },
    },
    {
      platform: 'school',
      siteName: 'Minhaajulhudaa School',
      tagline: 'Islamic Education Excellence',
      description: 'Nurturing minds with knowledge and faith - combining academic excellence with Islamic values.',
      contactEmail: 'school@minhaajulhudaa.com',
      contactPhone: '+2348000000001',
      address: 'Minhaajulhudaa School Campus, Lagos',
      socialLinks: {},
      paymentConfig: { provider: 'paystack', currency: 'NGN' },
      metadata: { established: '2021', levels: ['Primary', 'Junior Secondary', 'Senior Secondary'] },
    },
    {
      platform: 'masjid',
      siteName: 'Minhaajulhudaa Masjid',
      tagline: 'Community & Worship',
      description: 'A center for prayer, learning, and community - serving the Ummah with devotion.',
      contactEmail: 'masjid@minhaajulhudaa.com',
      contactPhone: '+2348000000002',
      address: 'Minhaajulhudaa Masjid, Lagos',
      socialLinks: {},
      paymentConfig: { provider: 'paystack', currency: 'NGN' },
      metadata: { capacity: 2000, established: '2020' },
    },
    {
      platform: 'charity',
      siteName: 'Minhaajulhudaa Charity Foundation',
      tagline: 'Serving Humanity',
      description: 'Bringing relief and hope to those in need - following the prophetic example of compassion.',
      contactEmail: 'charity@minhaajulhudaa.com',
      contactPhone: '+2348000000003',
      address: 'Minhaajulhudaa Charity Office, Lagos',
      socialLinks: {},
      paymentConfig: { provider: 'paystack', currency: 'NGN' },
      metadata: { established: '2022', registrationNumber: 'RC-2022-0001' },
    },
    {
      platform: 'travels',
      siteName: 'Minhaajulhudaa Travels & Tours',
      tagline: 'Hajj & Umrah Services',
      description: 'Your trusted partner for sacred journeys - making Hajj and Umrah accessible and meaningful.',
      contactEmail: 'travels@minhaajulhudaa.com',
      contactPhone: '+2348000000004',
      address: 'Minhaajulhudaa Travels Office, Lagos',
      socialLinks: {},
      paymentConfig: { provider: 'paystack', currency: 'NGN' },
      metadata: { established: '2023', licensed: true },
    },
  ],

  contact_submissions: [
    {
      platform: 'school',
      name: 'Fatima Bello',
      email: 'fatima.bello@example.com',
      phone: '+2348031234567',
      subject: 'Admission Inquiry for my son',
      message: 'I would like to inquire about admission for my 7-year-old son into primary 2. What are the requirements?',
      status: 'new',
      department: 'admissions',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      platform: 'masjid',
      name: 'Ahmed Tanko',
      email: 'ahmed.tanko@example.com',
      phone: '+2348057654321',
      subject: 'Jumuah prayer timing',
      message: 'What time does the Jumuah prayer start?',
      status: 'new',
      department: 'general',
      createdAt: new Date(Date.now() - 43200000).toISOString(),
    },
    {
      platform: 'charity',
      name: 'Khadijah Mohammed',
      email: 'khadijah.m@example.com',
      phone: '+2348079876543',
      subject: 'Volunteer opportunity',
      message: 'I am interested in volunteering for the food distribution program. How can I sign up?',
      status: 'new',
      department: 'volunteers',
      createdAt: new Date(Date.now() - 21600000).toISOString(),
    },
    {
      platform: 'travels',
      name: 'Ibrahim Aliyu',
      email: 'ibrahim.aliyu@example.com',
      phone: '+2348091234567',
      subject: 'Umrah package inquiry',
      message: 'I am interested in the December Umrah package for a family of 4. Can you provide details?',
      status: 'new',
      department: 'bookings',
      createdAt: new Date(Date.now() - 10800000).toISOString(),
    },
  ],
};
