/**
 * Travels & Tours platform seed data - comprehensive production data.
 */

const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d) => new Date(now.getTime() + d * 86400000).toISOString();

export const travelsSeedData = {
  travels_pages: [
    {
      slug: 'about',
      title: 'About Minhaajulhudaa Travels & Tours',
      content: [
        { type: 'hero', title: 'About Us', subtitle: 'Your trusted partner for sacred journeys' },
        { type: 'text', body: 'Minhaajulhudaa Travels & Tours was established in 2023 to provide Muslims with seamless, spiritually fulfilling Hajj and Umrah experiences. We are a licensed travel agency specializing in Islamic tourism, with a commitment to making the sacred journeys accessible, affordable, and meaningful.' },
        { type: 'text', body: 'Our team includes experienced Hajj and Umrah guides who have performed the pilgrimage multiple times. We handle every aspect of your journey - from visa processing and flight bookings to accommodation, transportation, and guided tours of the holy sites.' },
        { type: 'text', body: 'We also offer local and international Islamic tours to historical sites, Islamic landmarks, and Muslim-friendly destinations. Our pre-travel education program ensures that every pilgrim is spiritually and practically prepared for their sacred journey.' },
      ],
      seoTitle: 'About Minhaajulhudaa Travels',
      seoDescription: 'Licensed Hajj and Umrah travel agency.',
      status: 'published',
      publishedAt: daysAgo(60),
      order: 1,
    },
  ],

  travels_packages: [
    {
      slug: 'umrah-standard-2026',
      title: 'Umrah Standard Package - December 2026',
      description: 'Our most popular Umrah package offering comfortable accommodation and comprehensive services at an affordable price. Perfect for first-time pilgrims and families. This package includes everything you need for a smooth and spiritually fulfilling Umrah experience.',
      shortDescription: 'Comfortable and affordable Umrah package for individuals and families.',
      type: 'umrah',
      tier: 'standard',
      destination: 'Makkah & Madinah, Saudi Arabia',
      duration: '10 days',
      durationDays: 10,
      basePrice: 2500000,
      currency: 'NGN',
      inclusions: ['Return economy flights from Lagos', '4-star hotel in Makkah (5 nights)', '4-star hotel in Madinah (4 nights)', 'Daily breakfast and dinner', 'Air-conditioned transport', 'Visa processing', 'Guided ziyarah tours', 'English-speaking guide', 'Travel insurance'],
      exclusions: ['Personal expenses', 'Additional meals', 'Laundry', 'Phone calls', 'Optional tours'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800', 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800'],
      capacity: 50,
      availableSlots: 32,
      startDate: '2026-12-15',
      endDate: '2026-12-25',
      isFeatured: true,
      status: 'active',
      createdAt: daysAgo(30),
    },
    {
      slug: 'umrah-deluxe-2026',
      title: 'Umrah Deluxe Package - December 2026',
      description: 'Enhanced Umrah experience with premium accommodation closer to the Haram. Enjoy 5-star hotels, upgraded meals, and smaller group sizes for a more personalized experience.',
      shortDescription: 'Premium Umrah package with 5-star accommodation near the Haram.',
      type: 'umrah',
      tier: 'deluxe',
      destination: 'Makkah & Madinah, Saudi Arabia',
      duration: '12 days',
      durationDays: 12,
      basePrice: 4000000,
      currency: 'NGN',
      inclusions: ['Return business class flights from Lagos', '5-star hotel in Makkah (6 nights, 200m from Haram)', '5-star hotel in Madinah (5 nights, 300m from Masjid Nabawi)', 'All meals (breakfast, lunch, dinner)', 'Private air-conditioned transport', 'Express visa processing', 'Private guided ziyarah tours', 'Dedicated English-speaking guide', 'Premium travel insurance', 'Welcome gift package'],
      exclusions: ['Personal expenses', 'Optional premium tours'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      galleryImages: ['https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800'],
      capacity: 30,
      availableSlots: 18,
      startDate: '2026-12-15',
      endDate: '2026-12-27',
      isFeatured: true,
      status: 'active',
      createdAt: daysAgo(30),
    },
    {
      slug: 'umrah-vip-2026',
      title: 'Umrah VIP Package - Private Journey',
      description: 'The ultimate Umrah experience with private transport, luxury accommodation, and personalized service throughout your journey. Ideal for families and those seeking maximum comfort and convenience.',
      shortDescription: 'Luxury private Umrah experience with premium services.',
      type: 'umrah',
      tier: 'vip',
      destination: 'Makkah & Madinah, Saudi Arabia',
      duration: '14 days',
      durationDays: 14,
      basePrice: 7500000,
      currency: 'NGN',
      inclusions: ['Private return business class flights', 'Luxury 5-star hotel in Makkah (7 nights, Haram view)', 'Luxury 5-star hotel in Madinah (6 nights, Nabawi view)', 'All gourmet meals', 'Private luxury transport', 'Fast-track visa processing', 'Private guided tours', 'Dedicated scholar guide', 'VIP travel insurance', 'Personal concierge', 'Return airport transfers (private)'],
      exclusions: ['Personal expenses'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800',
      galleryImages: [],
      capacity: 15,
      availableSlots: 8,
      startDate: '2026-12-10',
      endDate: '2026-12-24',
      isFeatured: true,
      status: 'active',
      createdAt: daysAgo(30),
    },
    {
      slug: 'hajj-standard-2027',
      title: 'Hajj Standard Package 2027',
      description: 'Complete Hajj package with all necessary arrangements for fulfilling the fifth pillar of Islam. Includes accommodation, transport, guided rituals, and pre-Hajj education.',
      shortDescription: 'Complete Hajj package with comprehensive services.',
      type: 'hajj',
      tier: 'standard',
      destination: 'Makkah, Madinah & Mina, Saudi Arabia',
      duration: '25 days',
      durationDays: 25,
      basePrice: 6500000,
      currency: 'NGN',
      inclusions: ['Return flights from Lagos', '4-star hotel in Makkah', '4-star hotel in Madinah', 'Mina and Arafat accommodation (AC tents)', 'All meals during Hajj days', 'Air-conditioned transport', 'Visa processing', 'Guided Hajj rituals', 'Scholar accompaniment', 'Travel insurance'],
      exclusions: ['Personal expenses', 'Additional tours'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800',
      galleryImages: [],
      capacity: 100,
      availableSlots: 75,
      startDate: '2027-06-15',
      endDate: '2027-07-10',
      isFeatured: true,
      status: 'active',
      createdAt: daysAgo(60),
    },
    {
      slug: 'local-tour-historical-lagos',
      title: 'Islamic Heritage Tour of Lagos',
      description: 'Discover the Islamic history of Lagos through this guided tour of historical mosques, Islamic centers, and cultural landmarks. Perfect for families and educational groups.',
      shortDescription: 'One-day Islamic heritage tour of Lagos.',
      type: 'local-tour',
      tier: 'standard',
      destination: 'Lagos, Nigeria',
      duration: '1 day',
      durationDays: 1,
      basePrice: 25000,
      currency: 'NGN',
      inclusions: ['Air-conditioned bus', 'Professional guide', 'Lunch', 'Entrance fees', 'Bottled water'],
      exclusions: ['Personal expenses', 'Souvenirs'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800',
      galleryImages: [],
      capacity: 40,
      availableSlots: 35,
      startDate: '2026-09-20',
      endDate: '2026-09-20',
      isFeatured: false,
      status: 'active',
      createdAt: daysAgo(20),
    },
    {
      slug: 'international-tour-turkey',
      title: 'Islamic Heritage Tour of Turkey',
      description: 'Explore the rich Islamic heritage of Turkey, visiting historical mosques, palaces, and Islamic landmarks in Istanbul, Bursa, and Konya. 7-day guided tour.',
      shortDescription: '7-day Islamic heritage tour of Turkey.',
      type: 'international-tour',
      tier: 'deluxe',
      destination: 'Istanbul, Bursa & Konya, Turkey',
      duration: '7 days',
      durationDays: 7,
      basePrice: 1800000,
      currency: 'NGN',
      inclusions: ['Return flights from Lagos', '4-star hotels', 'Daily breakfast and dinner', 'Air-conditioned transport', 'English-speaking guide', 'Entrance fees', 'Travel insurance'],
      exclusions: ['Visa fee', 'Personal expenses', 'Optional tours', 'Lunch'],
      itinerary: [],
      imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
      galleryImages: [],
      capacity: 25,
      availableSlots: 20,
      startDate: '2026-11-01',
      endDate: '2026-11-07',
      isFeatured: false,
      status: 'active',
      createdAt: daysAgo(15),
    },
  ],

  travels_itineraries: [
    { packageId: 'pkg-umrah-standard', day: 1, title: 'Departure from Lagos', description: 'Depart from Murtala Muhammed International Airport, Lagos. Arrive in Jeddah, transfer to Makkah hotel.', activities: ['Airport check-in', 'Flight to Jeddah', 'Transfer to Makkah', 'Check-in and rest'], meals: ['Dinner'], accommodation: '4-star Hotel, Makkah' },
    { packageId: 'pkg-umrah-standard', day: 2, title: 'Performing Umrah', description: 'Perform Umrah rituals with guidance from our experienced scholar.', activities: ['Ihram preparation', 'Tawaf', 'Sa\'i', 'Halq/Taqseer', 'Rest'], meals: ['Breakfast', 'Dinner'], accommodation: '4-star Hotel, Makkah' },
    { packageId: 'pkg-umrah-standard', day: 3, title: 'Makkah Ziyarah', description: 'Guided tour of significant Islamic sites in Makkah.', activities: ['Visit Jabal al-Nour', 'Visit Cave of Hira', 'Visit Arafat', 'Visit Muzdalifah', 'Visit Mina'], meals: ['Breakfast', 'Dinner'], accommodation: '4-star Hotel, Makkah' },
    { packageId: 'pkg-umrah-standard', day: 6, title: 'Travel to Madinah', description: 'Travel to Madinah and check into hotel near Masjid Nabawi.', activities: ['Checkout from Makkah hotel', 'Travel to Madinah', 'Check-in to Madinah hotel', 'Visit Masjid Nabawi'], meals: ['Breakfast', 'Dinner'], accommodation: '4-star Hotel, Madinah' },
    { packageId: 'pkg-umrah-standard', day: 7, title: 'Madinah Ziyarah', description: 'Guided tour of significant Islamic sites in Madinah.', activities: ['Visit Masjid Quba', 'Visit Uhud', 'Visit Baqi Cemetery', 'Visit Masjid Qiblatain'], meals: ['Breakfast', 'Dinner'], accommodation: '4-star Hotel, Madinah' },
    { packageId: 'pkg-umrah-standard', day: 10, title: 'Return to Lagos', description: 'Final prayers at Masjid Nabawi, then travel to Jeddah for return flight.', activities: ['Morning prayers', 'Checkout', 'Travel to Jeddah', 'Flight to Lagos'], meals: ['Breakfast'], accommodation: 'N/A' },
  ],

  travels_bookings: [
    {
      bookingNumber: 'MHS-TRV/2026/001',
      packageId: '', packageTitle: 'Umrah Standard Package - December 2026',
      customerId: 'customer-001', customerName: 'Muhammad Ali', customerEmail: 'muhammad.ali@example.com', customerPhone: '+2348031111111',
      travelers: [{ fullName: 'Muhammad Ali', passportNumber: 'A12345678', dateOfBirth: '1980-05-15', gender: 'male', nationality: 'Nigerian', relationship: 'self' }],
      travelerCount: 1,
      startDate: '2026-12-15', endDate: '2026-12-25',
      totalAmount: 2500000, paidAmount: 2500000, currency: 'NGN',
      status: 'confirmed', paymentStatus: 'paid',
      specialRequests: 'Vegetarian meals preferred',
      bookedAt: daysAgo(5), confirmedAt: daysAgo(4),
    },
    {
      bookingNumber: 'MHS-TRV/2026/002',
      packageId: '', packageTitle: 'Umrah Deluxe Package - December 2026',
      customerId: 'customer-001', customerName: 'Ibrahim Suleiman', customerEmail: 'ibrahim.s@example.com', customerPhone: '+2348032222222',
      travelers: [
        { fullName: 'Ibrahim Suleiman', passportNumber: 'B23456789', dateOfBirth: '1975-08-20', gender: 'male', nationality: 'Nigerian', relationship: 'self' },
        { fullName: 'Fatima Suleiman', passportNumber: 'B23456790', dateOfBirth: '1980-03-12', gender: 'female', nationality: 'Nigerian', relationship: 'spouse' },
      ],
      travelerCount: 2,
      startDate: '2026-12-15', endDate: '2026-12-27',
      totalAmount: 8000000, paidAmount: 4000000, currency: 'NGN',
      status: 'confirmed', paymentStatus: 'partial',
      bookedAt: daysAgo(7), confirmedAt: daysAgo(6),
    },
    {
      bookingNumber: 'MHS-TRV/2026/003',
      packageId: '', packageTitle: 'Umrah Standard Package - December 2026',
      customerId: 'customer-001', customerName: 'Abdullah Okafor', customerEmail: 'abdullah.o@example.com', customerPhone: '+2348033333333',
      travelers: [
        { fullName: 'Abdullah Okafor', passportNumber: 'C34567890', dateOfBirth: '1985-11-05', gender: 'male', nationality: 'Nigerian', relationship: 'self' },
        { fullName: 'Aisha Okafor', passportNumber: 'C34567891', dateOfBirth: '1990-07-18', gender: 'female', nationality: 'Nigerian', relationship: 'spouse' },
        { fullName: 'Ali Okafor', passportNumber: 'C34567892', dateOfBirth: '2015-04-22', gender: 'male', nationality: 'Nigerian', relationship: 'son' },
      ],
      travelerCount: 3,
      startDate: '2026-12-15', endDate: '2026-12-25',
      totalAmount: 7500000, paidAmount: 3000000, currency: 'NGN',
      status: 'pending', paymentStatus: 'partial',
      specialRequests: 'Family room needed',
      bookedAt: daysAgo(2),
    },
    {
      bookingNumber: 'MHS-TRV/2026/004',
      packageId: '', packageTitle: 'Islamic Heritage Tour of Turkey',
      customerId: 'customer-001', customerName: 'Yusuf Bello', customerEmail: 'yusuf.b@example.com', customerPhone: '+2348034444444',
      travelers: [{ fullName: 'Yusuf Bello', passportNumber: 'D45678901', dateOfBirth: '1978-12-10', gender: 'male', nationality: 'Nigerian', relationship: 'self' }],
      travelerCount: 1,
      startDate: '2026-11-01', endDate: '2026-11-07',
      totalAmount: 1800000, paidAmount: 1800000, currency: 'NGN',
      status: 'confirmed', paymentStatus: 'paid',
      bookedAt: daysAgo(10), confirmedAt: daysAgo(9),
    },
    {
      bookingNumber: 'MHS-TRV/2026/005',
      packageId: '', packageTitle: 'Umrah VIP Package - Private Journey',
      customerId: 'customer-001', customerName: 'Alhaji Garba Sani', customerEmail: 'garba.s@example.com', customerPhone: '+2348035555555',
      travelers: [
        { fullName: 'Garba Sani', passportNumber: 'E56789012', dateOfBirth: '1965-09-15', gender: 'male', nationality: 'Nigerian', relationship: 'self' },
        { fullName: 'Maryam Sani', passportNumber: 'E56789013', dateOfBirth: '1970-01-20', gender: 'female', nationality: 'Nigerian', relationship: 'spouse' },
      ],
      travelerCount: 2,
      startDate: '2026-12-10', endDate: '2026-12-24',
      totalAmount: 15000000, paidAmount: 7500000, currency: 'NGN',
      status: 'confirmed', paymentStatus: 'partial',
      bookedAt: daysAgo(3), confirmedAt: daysAgo(2),
    },
  ],

  travels_customers: [
    { email: 'muhammad.ali@example.com', name: 'Muhammad Ali', phone: '+2348031111111', address: '12 Allen Avenue, Ikeja, Lagos', dateOfBirth: '1980-05-15', gender: 'male', nationality: 'Nigerian', passportNumber: 'A12345678', passportExpiry: '2028-05-14', totalBookings: 2, totalSpent: 4500000, firstBookingAt: daysAgo(180), lastBookingAt: daysAgo(5), tags: ['repeat-customer'], notes: 'Prefers standard packages' },
    { email: 'ibrahim.s@example.com', name: 'Ibrahim Suleiman', phone: '+2348032222222', address: '5 Adeniyi Jones, Ikeja, Lagos', dateOfBirth: '1975-08-20', gender: 'male', nationality: 'Nigerian', passportNumber: 'B23456789', passportExpiry: '2027-08-19', totalBookings: 3, totalSpent: 12000000, firstBookingAt: daysAgo(365), lastBookingAt: daysAgo(7), tags: ['vip', 'repeat-customer'], notes: 'Prefers deluxe packages' },
    { email: 'abdullah.o@example.com', name: 'Abdullah Okafor', phone: '+2348033333333', address: '31 Thompson Avenue, Ikoyi, Lagos', dateOfBirth: '1985-11-05', gender: 'male', nationality: 'Nigerian', passportNumber: 'C34567890', passportExpiry: '2029-11-04', totalBookings: 1, totalSpent: 7500000, firstBookingAt: daysAgo(2), lastBookingAt: daysAgo(2), tags: ['family-booking'], notes: 'First-time customer with family' },
    { email: 'yusuf.b@example.com', name: 'Yusuf Bello', phone: '+2348034444444', address: '23 Bourdillon Road, Ikoyi, Lagos', dateOfBirth: '1978-12-10', gender: 'male', nationality: 'Nigerian', passportNumber: 'D45678901', passportExpiry: '2028-12-09', totalBookings: 2, totalSpent: 2500000, firstBookingAt: daysAgo(90), lastBookingAt: daysAgo(10), tags: ['repeat-customer'], notes: 'Interested in international tours' },
    { email: 'garba.s@example.com', name: 'Garba Sani', phone: '+2348035555555', address: '15 Cameroun Road, Ikoyi, Lagos', dateOfBirth: '1965-09-15', gender: 'male', nationality: 'Nigerian', passportNumber: 'E56789012', passportExpiry: '2027-09-14', totalBookings: 5, totalSpent: 35000000, firstBookingAt: daysAgo(500), lastBookingAt: daysAgo(3), tags: ['vip', 'frequent-traveler'], notes: 'Always books VIP packages' },
  ],

  travels_payments: [
    { bookingId: '', amount: 2500000, currency: 'NGN', method: 'bank_transfer', reference: 'TRV-PAY-001', status: 'successful', isInstallment: false, installmentNumber: 0, paidAt: daysAgo(4) },
    { bookingId: '', amount: 4000000, currency: 'NGN', method: 'card', reference: 'TRV-PAY-002', status: 'successful', isInstallment: true, installmentNumber: 1, paidAt: daysAgo(6) },
    { bookingId: '', amount: 3000000, currency: 'NGN', method: 'bank_transfer', reference: 'TRV-PAY-003', status: 'successful', isInstallment: true, installmentNumber: 1, paidAt: daysAgo(2) },
    { bookingId: '', amount: 1800000, currency: 'NGN', method: 'card', reference: 'TRV-PAY-004', status: 'successful', isInstallment: false, installmentNumber: 0, paidAt: daysAgo(9) },
    { bookingId: '', amount: 7500000, currency: 'NGN', method: 'bank_transfer', reference: 'TRV-PAY-005', status: 'successful', isInstallment: true, installmentNumber: 1, paidAt: daysAgo(2) },
  ],

  travels_reviews: [
    { packageId: '', bookingId: '', customerName: 'Muhammad Ali', customerAvatarUrl: '', rating: 5, title: 'Excellent Umrah Experience', content: 'Minhaajulhudaa Travels made my Umrah journey smooth and spiritually fulfilling. The accommodation was excellent, the guide was knowledgeable, and every detail was taken care of. Highly recommended!', images: [], isVerified: true, status: 'approved', submittedAt: daysAgo(180) },
    { packageId: '', bookingId: '', customerName: 'Ibrahim Suleiman', customerAvatarUrl: '', rating: 5, title: 'Best Decision Ever', content: 'My wife and I had an amazing Umrah experience with Minhaajulhudaa. The deluxe package was worth every penny - the hotel was steps away from the Haram. The staff were professional and caring.', images: [], isVerified: true, status: 'approved', submittedAt: daysAgo(120) },
    { packageId: '', bookingId: '', customerName: 'Garba Sani', customerAvatarUrl: '', rating: 5, title: 'VIP Treatment Throughout', content: 'This is my 5th trip with Minhaajulhudaa and they never disappoint. The VIP package was exceptional - private transport, luxury hotels, and the scholar guide was very knowledgeable. Thank you for making Hajj and Umrah so accessible.', images: [], isVerified: true, status: 'approved', submittedAt: daysAgo(60) },
    { packageId: '', bookingId: '', customerName: 'Yusuf Bello', customerAvatarUrl: '', rating: 4, title: 'Great Turkey Tour', content: 'The Islamic heritage tour of Turkey was eye-opening. The hotels were good, the guide was excellent, and the itinerary was well-planned. Only suggestion would be to include more free time for personal exploration.', images: [], isVerified: true, status: 'approved', submittedAt: daysAgo(30) },
  ],

  travels_blog_posts: [
    {
      slug: 'how-to-prepare-for-umrah',
      title: 'How to Prepare for Your First Umrah',
      excerpt: 'A comprehensive guide covering everything you need to know before your first Umrah.',
      content: 'Performing Umrah for the first time is a deeply spiritual experience. Proper preparation ensures you can focus on worship without worries. Here is a comprehensive guide:\n\n## Spiritual Preparation\n- Increase your knowledge of Umrah rituals\n- Make tawbah and mend relationships\n- Learn the relevant duas\n- Prepare your heart with reflection\n\n## Documentation\n- Valid passport (6+ months validity)\n- Passport-size photographs\n- Vaccination certificates\n- Visa application (handled by us)\n\n## Physical Preparation\n- Increase walking to build stamina\n- Get a medical check-up\n- Pack comfortable walking shoes\n- Prepare for heat (light, breathable clothing)\n\n## What to Pack\n- Ihram clothing (2 sets)\n- Comfortable walking shoes\n- Prayer mat (travel size)\n- Quran and dua book\n- Toiletries (unscented)\n- Medications\n- Power adapter\n\n## During Umrah\n- Follow your guide\'s instructions\n- Stay hydrated\n- Be patient with crowds\n- Make plenty of dua\n\nAt Minhaajulhudaa Travels, we provide pre-departure briefings for all our packages to ensure you are fully prepared.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800',
      category: 'guides',
      tags: ['umrah', 'preparation', 'guide'],
      authorName: 'Ustadh Dawud Okafor',
      status: 'published',
      publishedAt: daysAgo(7),
      views: 423,
    },
    {
      slug: 'best-time-for-umrah',
      title: 'Best Times to Perform Umrah',
      excerpt: 'Understanding the different seasons for Umrah and choosing the right time for you.',
      content: 'Choosing the right time for Umrah can significantly impact your experience. Here is a guide to the different seasons:\n\n## Ramadan (Most Rewarding)\nThe reward of Umrah in Ramadan equals that of Hajj. However, it is the busiest and most expensive time. Book 3-4 months in advance.\n\n## December Holidays (Popular)\nSchool holidays make December a popular time for families. Weather is pleasant in Saudi Arabia.\n\n## Summer (Less Crowded)\nSummer months (June-August) are less crowded but extremely hot. Not recommended for elderly or those with health conditions.\n\n## Off-Peak (Best Value)\nSeptember-November and February-April offer good weather, fewer crowds, and lower prices.\n\nAt Minhaajulhudaa Travels, we offer packages throughout the year. Contact us to find the best option for your schedule and budget.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      category: 'guides',
      tags: ['umrah', 'timing', 'tips'],
      authorName: 'Ustadh Dawud Okafor',
      status: 'published',
      publishedAt: daysAgo(14),
      views: 287,
    },
    {
      slug: 'hajj-vs-umrah-understanding',
      title: 'Hajj vs Umrah: Understanding the Differences',
      excerpt: 'A clear explanation of the differences between Hajj and Umrah.',
      content: 'While both Hajj and Umrah are pilgrimages to Makkah, there are significant differences:\n\n## Obligation\n- Hajj is obligatory once in a lifetime for those who can afford it (5th pillar)\n- Umrah is recommended (Sunnah) but not obligatory\n\n## Timing\n- Hajj has specific dates (8th-13th of Dhul-Hijjah)\n- Umrah can be performed any time of year\n\n## Rituals\n- Umrah: Ihram, Tawaf, Sa\'i, Halq/Taqseer\n- Hajj: All Umrah rituals + Arafat, Muzdalifah, Mina, Stoning the Jamarat\n\n## Duration\n- Umrah: A few hours to complete\n- Hajj: 5-6 days of rituals\n\n## Cost\n- Umrah is generally less expensive\n- Hajj costs more due to longer stay and additional arrangements\n\nAt Minhaajulhudaa Travels, we offer both Hajj and Umrah packages tailored to your needs.',
      featuredImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800',
      category: 'education',
      tags: ['hajj', 'umrah', 'education'],
      authorName: 'Ustadh Dawud Okafor',
      status: 'published',
      publishedAt: daysAgo(20),
      views: 356,
    },
  ],

  travels_resources: [
    {
      slug: 'visa-requirements-saudi-arabia',
      title: 'Saudi Arabia Visa Requirements for Nigerians',
      content: 'Complete guide to obtaining a Saudi visa for Hajj or Umrah from Nigeria.\n\n## Required Documents\n- Valid passport (6+ months validity)\n- Passport-size photographs (white background)\n- Meningitis vaccination certificate\n- Completed visa application form\n- Confirmed return ticket\n- Hotel booking confirmation\n\n## Process\n1. Register with a licensed travel agency (like Minhaajulhudaa)\n2. Submit required documents\n3. Wait for visa processing (5-7 business days)\n4. Receive e-visa\n\n## Important Notes\n- Visas are only issued through authorized agencies\n- Hajj visas have specific application windows\n- Umrah visas are available year-round (except during Hajj season)\n\nMinhaajulhudaa Travels handles all visa processing for our clients at no additional cost.',
      category: 'visa',
      tags: ['visa', 'saudi', 'requirements'],
      author: 'Minhaajulhudaa Travels Team',
      status: 'published',
      updatedAt: daysAgo(5),
    },
    {
      slug: 'packing-checklist-umrah',
      title: 'Complete Packing Checklist for Umrah',
      content: 'Everything you need to pack for a comfortable Umrah journey.\n\n## Documents\n- Passport\n- Visa\n- Flight tickets\n- Hotel booking confirmation\n- Vaccination certificate\n- Travel insurance\n\n## Clothing\n- 2 sets of Ihram (for men)\n- Modest clothing for women\n- Comfortable walking shoes\n- Sandals/flip-flops\n- Light jacket (for air conditioning)\n\n## Personal Items\n- Unscented toiletries\n- Medications\n- Prayer mat (travel)\n- Quran\n- Dua book\n- Water bottle\n- Umbrella\n\n## Electronics\n- Phone and charger\n- Power bank\n- Universal adapter\n- Headphones\n\n## Misc\n- Small backpack\n- Reusable shopping bag\n- Snacks\n- Tissues\n\nPack light - you will be carrying your luggage frequently.',
      category: 'packing',
      tags: ['packing', 'checklist', 'umrah'],
      author: 'Minhaajulhudaa Travels Team',
      status: 'published',
      updatedAt: daysAgo(10),
    },
    {
      slug: 'umrah-rituals-guide',
      title: 'Step-by-Step Guide to Umrah Rituals',
      content: 'A clear, step-by-step guide to performing Umrah correctly.\n\n## Step 1: Ihram\n- Purify yourself (ghusl)\n- Wear Ihram clothing\n- Make intention for Umrah\n- Recite Talbiyah\n\n## Step 2: Tawaf\n- Enter Masjid al-Haram\n- Start at the Black Stone\n- Circle Ka\'bah 7 times counterclockwise\n- Recite prayers during Tawaf\n- Pray 2 rak\'ahs near Maqam Ibrahim\n\n## Step 3: Sa\'i\n- Walk between Safa and Marwah\n- 7 laps (Safa to Marwah = 1, Marwah to Safa = 2, etc.)\n- Recite prayers\n- Men: run between green markers\n\n## Step 4: Halq or Taqseer\n- Men: Shave head (Halq) or trim hair (Taqseer)\n- Women: Trim a fingertip\'s length of hair\n- Umrah is now complete!\n\nImportant: Follow your guide for detailed instructions and avoid common mistakes.',
      category: 'rituals',
      tags: ['umrah', 'rituals', 'guide'],
      author: 'Ustadh Dawud Okafor',
      status: 'published',
      updatedAt: daysAgo(15),
    },
    {
      slug: 'health-tips-pilgrimage',
      title: 'Health Tips for Hajj and Umrah',
      content: 'Stay healthy during your pilgrimage with these essential tips.\n\n## Before Travel\n- Get required vaccinations (meningitis, flu)\n- Medical check-up\n- Pack necessary medications\n- Get travel insurance\n\n## During Travel\n- Stay hydrated (drink plenty of water)\n- Avoid direct sun when possible\n- Use sunscreen\n- Wear comfortable shoes\n- Wash hands frequently\n\n## Common Issues\n- Heat exhaustion: Rest, hydrate, seek shade\n- Dehydration: Drink water regularly\n- Blisters: Use proper footwear, bandages\n- Respiratory infections: Use mask in crowds\n\n## Emergency\n- Carry emergency contact numbers\n- Know your blood type\n- Keep medications in original packaging\n- Inform your guide of any health issues',
      category: 'health',
      tags: ['health', 'tips', 'safety'],
      author: 'Minhaajulhudaa Travels Team',
      status: 'published',
      updatedAt: daysAgo(8),
    },
  ],

  travels_courses: [
    {
      slug: 'umrah-complete-guide',
      title: 'Umrah: The Complete Guide',
      description: 'A comprehensive course covering everything you need to know about performing Umrah - from spiritual preparation to the rituals themselves.',
      shortDescription: 'Complete preparation course for Umrah pilgrims.',
      category: 'umrah-guide',
      level: 'beginner',
      instructor: 'Ustadh Dawud Okafor',
      price: 0,
      duration: '4 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800',
      lessonsCount: 10,
      enrolledCount: 234,
      rating: 4.9,
      status: 'published',
      publishedAt: daysAgo(30),
    },
    {
      slug: 'hajj-rituals-explained',
      title: 'Hajj Rituals Explained Step by Step',
      description: 'Detailed course on all Hajj rituals, their meanings, and how to perform them correctly according to the Sunnah.',
      shortDescription: 'Master all Hajj rituals with this step-by-step course.',
      category: 'hajj-rituals',
      level: 'intermediate',
      instructor: 'Ustadh Dawud Okafor',
      price: 0,
      duration: '6 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800',
      lessonsCount: 15,
      enrolledCount: 178,
      rating: 5.0,
      status: 'published',
      publishedAt: daysAgo(45),
    },
    {
      slug: 'makkah-history-significance',
      title: 'Makkah: History and Significance',
      description: 'Explore the rich history of Makkah, from the time of Ibrahim (AS) to the present day, and understand the significance of the holy city.',
      shortDescription: 'Discover the history and significance of the holy city of Makkah.',
      category: 'makkah-history',
      level: 'beginner',
      instructor: 'Ustadh Dawud Okafor',
      price: 0,
      duration: '3 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      lessonsCount: 8,
      enrolledCount: 145,
      rating: 4.8,
      status: 'published',
      publishedAt: daysAgo(20),
    },
    {
      slug: 'madinah-the-beloved-city',
      title: 'Madinah: The Beloved City of the Prophet',
      description: 'Learn about Madinah, the city of the Prophet Muhammad (PBUH), its history, and its significance in Islam.',
      shortDescription: 'Explore the history and beauty of Madinah.',
      category: 'madinah-history',
      level: 'beginner',
      instructor: 'Ustadh Dawud Okafor',
      price: 0,
      duration: '3 weeks',
      thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
      lessonsCount: 8,
      enrolledCount: 132,
      rating: 4.9,
      status: 'published',
      publishedAt: daysAgo(15),
    },
  ],

  travels_lessons: [
    { courseId: 'course-umrah-guide', title: 'Introduction to Umrah', content: 'What is Umrah and why is it important?', videoUrl: '', duration: 20, order: 1, resources: [], isPreview: true },
    { courseId: 'course-umrah-guide', title: 'Spiritual Preparation', content: 'How to prepare your heart and mind for Umrah.', videoUrl: '', duration: 25, order: 2, resources: [] },
    { courseId: 'course-umrah-guide', title: 'Ihram: The Sacred State', content: 'Understanding Ihram and how to enter it.', videoUrl: '', duration: 30, order: 3, resources: [] },
    { courseId: 'course-umrah-guide', title: 'Tawaf: Circling the Ka\'bah', content: 'How to perform Tawaf correctly.', videoUrl: '', duration: 35, order: 4, resources: [] },
    { courseId: 'course-umrah-guide', title: 'Sa\'i: The Walk of Hajar', content: 'Performing Sa\'i between Safa and Marwah.', videoUrl: '', duration: 30, order: 5, resources: [] },
    { courseId: 'course-hajj-rituals', title: 'Introduction to Hajj', content: 'Understanding the obligation of Hajj.', videoUrl: '', duration: 25, order: 1, resources: [], isPreview: true },
    { courseId: 'course-hajj-rituals', title: 'Day of Tarwiyah (8th Dhul-Hijjah)', content: 'The first day of Hajj - traveling to Mina.', videoUrl: '', duration: 30, order: 2, resources: [] },
  ],

  travels_enrollments: [
    { courseId: 'course-umrah-guide', customerId: 'customer-001', customerName: 'Muhammad Ali', enrolledAt: daysAgo(5), progress: 60, completedLessons: ['l1', 'l2', 'l3'], status: 'active' },
    { courseId: 'course-hajj-rituals', customerId: 'customer-002', customerName: 'Ibrahim Suleiman', enrolledAt: daysAgo(10), progress: 100, completedLessons: ['l1', 'l2', 'l3', 'l4', 'l5'], status: 'completed' },
    { courseId: 'course-makkah-history', customerId: 'customer-003', customerName: 'Abdullah Okafor', enrolledAt: daysAgo(2), progress: 20, completedLessons: ['l1'], status: 'active' },
  ],

  travels_gallery: [
    { title: 'Ka\'bah - Makkah', description: 'The Holy Ka\'bah in Masjid al-Haram.', imageUrl: 'https://images.unsplash.com/photo-1591456983933-0d29460ee5b6?w=800', category: 'holy-sites', destination: 'Makkah', createdAt: daysAgo(30) },
    { title: 'Masjid Nabawi - Madinah', description: 'The Prophet\'s Mosque in Madinah.', imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800', category: 'holy-sites', destination: 'Madinah', createdAt: daysAgo(30) },
    { title: 'Istanbul Mosque', description: 'Beautiful mosque in Istanbul during our Turkey tour.', imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800', category: 'tours', destination: 'Istanbul', createdAt: daysAgo(15) },
    { title: 'Group Photo - Umrah', description: 'Our December 2025 Umrah group.', imageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800', category: 'groups', destination: 'Makkah', createdAt: daysAgo(60) },
  ],

  travels_inquiries: [
    { name: 'Khadijah Mohammed', email: 'khadijah.m@example.com', phone: '+2348051111111', packageId: '', subject: 'Family Umrah inquiry', message: 'I am interested in the Umrah Standard Package for a family of 4 (2 adults, 2 children). Can you provide a custom quote?', preferredDate: '2026-12-15', travelerCount: 4, status: 'new', createdAt: daysAgo(1) },
    { name: 'Ahmed Ali', email: 'ahmed.ali@example.com', phone: '+2348052222222', packageId: '', subject: 'Hajj 2027 booking', message: 'When does registration for Hajj 2027 open? I would like to book early.', preferredDate: '2027-06-15', travelerCount: 2, status: 'new', createdAt: daysAgo(2) },
    { name: 'Fatima Bello', email: 'fatima.b@example.com', phone: '+2348053333333', packageId: '', subject: 'Turkey tour details', message: 'What is included in the Turkey tour package? Is the visa included?', preferredDate: '2026-11-01', travelerCount: 1, status: 'responded', createdAt: daysAgo(5) },
  ],

  travels_pricing_rules: [
    { packageId: '', type: 'early-bird', ruleName: 'Early Bird Discount - 3 months ahead', discountPercent: 10, surchargePercent: 0, minGroupSize: 1, daysBeforeDeparture: 90, active: true },
    { packageId: '', type: 'group-discount', ruleName: 'Group of 5+ discount', discountPercent: 5, surchargePercent: 0, minGroupSize: 5, active: true },
    { packageId: '', type: 'group-discount', ruleName: 'Group of 10+ discount', discountPercent: 10, surchargePercent: 0, minGroupSize: 10, active: true },
    { packageId: '', type: 'seasonal-surcharge', ruleName: 'Ramadan surcharge', discountPercent: 0, surchargePercent: 20, startDate: '2026-02-01', endDate: '2026-03-31', active: true },
    { packageId: '', type: 'last-minute', ruleName: 'Last minute - 2 weeks before', discountPercent: 5, surchargePercent: 0, daysBeforeDeparture: 14, active: true },
  ],
};
